
# 🔁 Daily Repo Loop for **Ego4d-LiteSTA** (Colab-first)

This block sets up SSH to GitHub (**Deploy Key stored in Drive**), pulls your repo, runs code, logs outputs, and pushes logs/artifacts back to GitHub.
- One-time: add your **Deploy Key** public key to your GitHub repo Deploy Keys with **write access**.
- Edit the variables (**GITHUB_USER**, **REPO_NAME**) below once; they persist per notebook.

In [16]:
# ⛳ Mount Drive and set variables
#!fusermount -u /content/drive

from google.colab import drive
drive.mount('/content/drive')

GITHUB_USER = "saeedzns"          # <<< EDIT ME
REPO_NAME   = "Ego4d-LiteSTA"             # <<< default as requested
REPO_SSH    = f"git@github.com:{GITHUB_USER}/{REPO_NAME}.git"
WORKDIR     = f"/content/drive/MyDrive/{REPO_NAME}"
SSH_DIR     = "/content/drive/MyDrive/.ssh"

print("Repo:", REPO_SSH)
print("Workdir:", WORKDIR)


# 🔐 SSH + git config + clone/pull
# 1) Git identity (optional but recommended)
!git config --global user.name "saeedzns"
!git config --global user.email "zns1992@gmail.com"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Repo: git@github.com:saeedzns/Ego4d-LiteSTA.git
Workdir: /content/drive/MyDrive/Ego4d-LiteSTA
  011eaceb-42c9-41b3-a038-87ea17c6e15d: wrote 56 jpgs → now=56/56 | total≈9480 | ok_cpu in 109.4s

In [2]:
# Git keepalive + sane pack settings for Colab
import os, subprocess
os.environ['GIT_SSH_COMMAND'] = 'ssh -o ServerAliveInterval=30 -o ServerAliveCountMax=10'
subprocess.run(['git','config','--global','core.compression','9'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
subprocess.run(['git','config','--global','pack.threads','2'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
print('Configured GIT_SSH_COMMAND and git pack settings')

Configured GIT_SSH_COMMAND and git pack settings

In [3]:
# 2) SSH agent and key from Drive (key filename: colab_egolite)
%%bash -s "$SSH_DIR"
SSH_DIR="$1"
mkdir -p "$SSH_DIR"
chmod 700 "$SSH_DIR"
eval "$(ssh-agent -s)"
ssh-add "$SSH_DIR/colab_egolite" >/dev/null 2>&1 || true
mkdir -p ~/.ssh && chmod 700 ~/.ssh
cat <<EOF > ~/.ssh/config
Host github.com
  HostName github.com
  User git
  IdentityFile $SSH_DIR/colab_egolite
  IdentitiesOnly yes
StrictHostKeyChecking accept-new
EOF
chmod 600 ~/.ssh/config
ssh-keyscan -t rsa,ed25519 github.com >> ~/.ssh/known_hosts 2>/dev/null || true
chmod 644 ~/.ssh/known_hosts

Agent pid 632

## Pull and Push — Daily Sync
Run after setting variables and SSH above.

In [ ]:
%cd "$WORKDIR"
!bash pull.sh

/content/drive/MyDrive/Ego4d-LiteSTA
Detached HEAD; please checkout a branch.

In [ ]:
%cd "$WORKDIR"
!bash push.sh

/content/drive/MyDrive/Ego4d-LiteSTA
[push] Staging all changes...

In [ ]:
!git status

Refresh index: 100% (8693/8693), done.
interactive rebase in progress; onto 46bae9c
Last command done (1 command done):
   pick 582db25 chore: daily sync 2025-11-05 18:30:11Z
Next commands to do (2 remaining commands):
   pick 582db25 chore: daily sync 2025-11-05 18:30:11Z
   pick 514cc95 chore: daily sync 2025-11-05 20:17:16Z
  (use "git rebase --edit-todo" to view and edit)
You are currently editing a commit while rebasing branch 'main' on '46bae9c'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   notebooks/Ego4D_STA_Colab_Starter.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [ ]:
!git add -A

In [ ]:
!git commit -m "last 12:03 11/06"

[detached HEAD 312859f] 12:03 11/06
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite notebooks/Ego4D_STA_Colab_Starter.ipynb (87%)

In [ ]:
!git push origin HEAD:main

Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 520 bytes | 74.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:saeedzns/Ego4d-LiteSTA.git
   cfe7fa9..312859f  HEAD -> main

In [ ]:
%cd "$WORKDIR"

/content/drive/MyDrive/Ego4d-LiteSTA

In [ ]:
%cd "$WORKDIR"
!git status

^C

In [ ]:
%cd "$WORKDIR"
!git pull origin main

/content/drive/MyDrive/Ego4d-LiteSTA
From github.com:saeedzns/Ego4d-LiteSTA
 * branch            main       -> FETCH_HEAD
Already up to date.

## Fast Push (Colab)
Uses /content SSD and rsyncs code-only for faster commits/pushes.
- Requires prior setup cells (Drive + SSH).
- Pushes only code/config (heavy artifacts excluded).

In [ ]:
%env FAST_PUSH_INCLUDE_HEAVY=1

In [ ]:
%cd ""
%env WORKDIR=
!FAST_PUSH=1 bash push.sh "colab fast push"

# Elimination

In [ ]:
# Replace '/path/to/your/directory' with the actual directory path you want to delete
#!rm -rf /content/drive/MyDrive/ego4d_data/v2/frames

# Demo change

### 🧾 Run ID + logger helpers (use these in your train/eval cells)

In [ ]:
# 🧾 Run ID + logger helpers (use these in your train/eval cells)
import os, json, traceback, datetime, shutil, glob

RUN_ID = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
LOG_DIR = "logs"; RUN_DIR = f"runs/{RUN_ID}"; OUT_DIR = "outputs"
os.makedirs(LOG_DIR, exist_ok=True); os.makedirs(RUN_DIR, exist_ok=True); os.makedirs(OUT_DIR, exist_ok=True)

LOG_PATH = f"{LOG_DIR}/{RUN_ID}.log"
ERR_FILE = "COLAB_ERRORS.md"

def log_write(msg):
    with open(LOG_PATH, "a", encoding="utf-8") as f:
        f.write(msg + "\n")
    print(msg)

def record_error(title, err_text):
    with open(ERR_FILE, "a", encoding="utf-8") as f:
        f.write(f"\n## {RUN_ID} — {title}\n\n```\n{err_text}\n```\n")

log_write(f"New run: {RUN_ID}")

New run: 20251106_144527


# 🧪 Ego4D STA — Colab Starter (Data Loading + Sanity Checks)

This notebook is designed to **run on Colab Free** with minimal setup. It focuses on:
- Mounting Google Drive and pointing to your **Ego4D STA** data (annotations + frames).
- Installing minimal dependencies and cloning the **Ego4D Forecasting** repo for official STA metrics.
- Loading a sample from the STA annotations and **visualizing the last frame** with a GT box overlay (val split).
- (Optional) Running the official **evaluation script** on a tiny subset to verify your setup.

> **Tip:** Keep runs short and save outputs to Drive frequently (Colab sessions can disconnect).

In [9]:

#@title 🔍 Check GPU
import torch, platform, sys
print("Python:", sys.version)
print("Platform:", platform.platform())
print("Torch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("CUDA device:", torch.cuda.get_device_name(0))

Python: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]
Platform: Linux-6.6.105+-x86_64-with-glibc2.35
Torch: 2.8.0+cu126
CUDA available: True
CUDA device: Tesla T4


## 📁 Set your base paths

Two scenarios:

- **A) You already have STA data in Drive** → set `EGO4D_DIR` to where `annotations/` and `frames/` live.
- **B) You want to download using the Ego4D CLI** (requires credentials) → see the optional download cell below.

In [5]:
import os
os.environ['AWS_ACCESS_KEY_ID'] = "AKIATEEVKTGZMBINY4C4"
os.environ['AWS_SECRET_ACCESS_KEY'] = "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"

In [5]:
# Download the AWS and Ego4D CLIs, then download the annotations locally
%%capture
%%bash

# Set up the AWS CLI
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip -o awscliv2.zip >/dev/null
sudo ./aws/install >/dev/null 2>&1
aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" && aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
rm "awscliv2.zip"

In [6]:
!pip install ego4d

Collecting ego4d
  Downloading ego4d-1.7.3.tar.gz (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.5/94.5 kB 8.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting boto3 (from ego4d)
  Downloading boto3-1.40.68-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from ego4d) (4.67.1)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from ego4d) (2024.11.6)
Collecting dataclasses_json (from ego4d)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting iopath (from ego4d)
  Downloading iopath-0.1.10.tar.gz (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting botocore<1.41.0,>=1.40.68 (from boto3->ego4d)
  Downloading botocore-1.40.68-py3-none-any.whl.metadata (5.7 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3->ego4d)
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.15.0,>=0.14.0 (from boto3->ego4d)
  Downloading s3transfer-0.14.0-py3-none-any.whl.metadata (1.7 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses_json->ego4d)
  Downloading marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses_json->ego4d)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.12/dist-packages (from iopath->ego4d) (4.15.0)
Collecting portalocker (from iopath->ego4d)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore<1.41.0,>=1.40.68->boto3->ego4d) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<1.41.0,>=1.40.68->boto3->ego4d) (2.5.0)
Requirement already satisfied: packaging>=17.0 in /usr/local/lib/python3.12/dist-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses_json->ego4d) (25.0)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses_json->ego4d)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.41.0,>=1.40.68->boto3->ego4d) (1.17.0)
Downloading boto3-1.40.68-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.4/139.4 kB 16.3 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading botocore-1.40.68-py3-none-any.whl (14.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 141.5 MB/s eta 0:00:00
Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Downloading marshmallow-3.26.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 6.0 MB/s eta 0:00:00
Downloading s3transfer-0.14.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 10.7 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading portalocker-3.2.0-py3-none-any.whl (22 kB)
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Building wheels for collected packages: ego4d, iopath
  Building wheel for ego4d (pyproject.toml) ... done
  Created wheel for ego4d: filename=ego4d-1.7.3-py3-none-any.whl size=118282 sha256=7baa50381ef2c571a54748c21c8471e19cd991c321620b06e7f46a6274a32f45
  Stored in directory: /root/.cache/pip/wheels/21/cb/71/5c67fe56e187aeb2d7566f197cd6987da12f7b718fd13a24be
  Building wheel for iopath (setup.py) ... done
  Created wheel for iopath: filename=iopath-0.1.10-py3-none-any.whl size=31527 sha256=95b3eb0be4405deb07b22f46c97c53cb6b34203c2f514e944bf0e5709b5a0677
  Stored in directory: /root/.cache/pip/wheels/7c/96/04/4f5f31ff812f684f69f40cb1634357812220aac58d4698048c
Successfully built ego4d iopath
Installing collected packages: portalocker, mypy-extensions, marshmallow, jmespath, typing-inspect, iopath, botocore, s3transfer, dataclasses_json, boto3, ego4d
Successfully installed boto3-1.40.68 botocore-1.40.68 dataclasses_json-0.6.7 ego4d-1.7.3 iopath-0.1.10 jmespath-1.0.1 marshmallow-3.26.1 mypy-extensions-1.1.0 portalocker-3.2.0 s3transfer-0.14.0 typing-inspect-0.9.0

In [ ]:
!ego4d --list-datasets

Downloading datasets.csv..

Available Ego4D datasets:
   annotations          	The full set of annotations for the majority of benchmarks.
   full_scale           	The full scale version of all videos.  (Provide `benchmarks` or `video_uids` filters to reduce the 5TB download size.)
   clips                	Clips available for benchmark training tasks.  (Provide `benchmarks` or `video_uids` filters to reduce the download size.)
   video_540ss          	The downscaled version of all videos - rescaled to 540px on the short side.  (Provide `benchmarks` or `video_uids` filters to reduce the 5TB download size.)
   annotations_540ss    	The annotations corresponding to the downscaled `video_540ss` videos - primarily differing only in spatial annotations (e.g. bounding boxes).
   3d                   	Annotations for the 3D VQ benchmark.
   3d_scans             	3D location scans for the 3D VQ benchmark.
   3d_scan_keypoints    	3D location scan keypoints for the 3D VQ benchmark.
   imu                  	IMU data for the subset of videos available
   slowfast8x8_r101_k400	Precomputed [action features](https://ego4d-data.org/docs/data/features/) for the Slowfast 8x8 (R101) model
   omnivore_video_swinl 	Precomputed [action features](https://ego4d-data.org/docs/data/features/) for the Omnivore Video model
   omnivore_image_swinl 	Precomputed [action features](https://ego4d-data.org/docs/data/features/) for the Omnivore Image model
   fut_loc              	Images and annotations for the future locomotion benchmark.
   av_models            	Model checkpoints for the AV/Social benchmark.
   lta_models           	Model checkpoints for the Long Term Anticipation benchmark.
   moments_models       	Model checkpoints for the Moments benchmark.
   nlq_models           	Model checkpoints for the NLQ benchmark.
   sta_models           	Model checkpoints for the Short Term Anticipation benchmark.
   vq2d_models          	Model checkpoints for the 2D VQ benchmark.
   clip_256ss           	Clips downscaled to 256px short side
   egotracks            	Egotracks dataset
   gaze                 	Eye gaze data
   imu                  	IMU data
   naq_datasets         	See https://github.com/srama2512/NaQ
   omnivore_video_swinl_fp16	Omnivore Video features in FP16 (half the size
   vq2d_detections      	VQ2D Preprocessed Detections

In [ ]:
!ego4d --output_directory="/content/540" --datasets annotations_540ss -y

Warning: Non-standard Dataset Specfied (Allowed, will attempt download): ['annotations_540ss']
Datasets to download: {'annotations_540ss'}
Download Path: /content/540/v2
Downloading Ego4D metadata json..
Ego4D Metadata: /content/540/ego4d.json
Checking requested datasets and versions...
Created download directory for version 'v2_1' of dataset: 'annotations_540ss' at: /content/540/v2/annotations_540ss
Traceback (most recent call last):
  File "/usr/local/bin/ego4d", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ego4d/cli/cli.py", line 251, in main
    main_cfg(config)
  File "/usr/local/lib/python3.12/dist-packages/ego4d/cli/cli.py", line 119, in main_cfg
    manifest_path = download_manifest_for_version(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ego4d/cli/manifest.py", line 159, in download_manifest_for_version
    _manifest_object(version, dataset, s3).download_file(str(download_path))
  File "/usr/local/lib/python3.12/dist-packages/boto3/s3/inject.py", line 392, in object_download_file
    return self.meta.client.download_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/botocore/context.py", line 123, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/boto3/s3/inject.py", line 223, in download_file
    return transfer.download_file(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/boto3/s3/transfer.py", line 407, in download_file
    future.result()
  File "/usr/local/lib/python3.12/dist-packages/s3transfer/futures.py", line 111, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/s3transfer/futures.py", line 287, in result
    raise self._exception
  File "/usr/local/lib/python3.12/dist-packages/s3transfer/tasks.py", line 272, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/s3transfer/download.py", line 359, in _submit
    response = client.head_object(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/botocore/client.py", line 602, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/botocore/context.py", line 123, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/botocore/client.py", line 1078, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

In [ ]:
# Download the Ego4D Annotations to ego4d_data/

version = "v2" # <<< EDIT ME to download v2 or v1

!ego4d --output_directory="/content/drive/MyDrive/ego4d_data/" --datasets annotations sta_models omnivore_video_swinl_fp16 --benchmarks FHO --version {version} -y

Warning: Non-standard Dataset Specfied (Allowed, will attempt download): ['omnivore_video_swinl_fp16']
Datasets to download: {'annotations', 'sta_models', 'omnivore_video_swinl_fp16'}
Download Path: /content/drive/MyDrive/ego4d_data/v2
Ego4D Metadata: /content/drive/MyDrive/ego4d_data/ego4d.json
Checking requested datasets and versions...
Created download directory for version 'v2' of dataset: 'annotations' at: /content/drive/MyDrive/ego4d_data/v2/annotations
Benchmarks specified but ignored without a benchmarks field in manifest.
Created download directory for version 'v2' of dataset: 'sta_models' at: /content/drive/MyDrive/ego4d_data/v2/sta_models
Benchmarks specified but ignored without a benchmarks field in manifest.
Created download directory for version 'v2' of dataset: 'omnivore_video_swinl_fp16' at: /content/drive/MyDrive/ego4d_data/v2/omnivore_video_swinl_fp16
Filtering by benchmarks: ['fho']
Retrieving object metadata from S3...
100% 1130/1130 [00:01<00:00, 811.05object/s]
Checking if latest file versions are already downloaded...
  0% 0/1130 [00:00<?, ?file/s]already_downloaded: no version entry for existing file: /content/drive/MyDrive/ego4d_data/v2/annotations/fho_main.json
already_downloaded: no version entry for existing file: /content/drive/MyDrive/ego4d_data/v2/annotations/fho_hands_test_unannotated.json
already_downloaded: no version entry for existing file: /content/drive/MyDrive/ego4d_data/v2/annotations/fho_lta_train.json
already_downloaded: no version entry for existing file: /content/drive/MyDrive/ego4d_data/v2/annotations/fho_lta_val.json
already_downloaded: no version entry for existing file: /content/drive/MyDrive/ego4d_data/v2/annotations/fho_lta_test_unannotated.json
already_downloaded: no version entry for existing file: /content/drive/MyDrive/ego4d_data/v2/annotations/fho_lta_taxonomy.json
already_downloaded: no version entry for existing file: /content/drive/MyDrive/ego4d_data/v2/annotations/fho_oscc-pnr_test_unannotated.json
already_downloaded: no version entry for existing file: /content/drive/MyDrive/ego4d_data/v2/annotations/fho_oscc-pnr_train.json
already_downloaded: no version entry for existing file: /content/drive/MyDrive/ego4d_data/v2/annotations/fho_oscc-pnr_val.json
already_downloaded: no version entry for existing file: /content/drive/MyDrive/ego4d_data/v2/annotations/fho_sta_train.json
already_downloaded: no version entry for existing file: /content/drive/MyDrive/ego4d_data/v2/annotations/fho_sta_val.json
  0% 2/1130 [00:00<06:44,  2.79file/s]already_downloaded: no version entry for existing file: /content/drive/MyDrive/ego4d_data/v2/annotations/fho_sta_test_unannotated.json
already_downloaded: no version entry for existing file: /content/drive/MyDrive/ego4d_data/v2/annotations/fho_main_taxonomy.json
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-consortium-sharing.s3.us-west-1.amazonaws.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-consortium-sharing.s3.us-west-1.amazonaws.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-consortium-sharing.s3.us-west-1.amazonaws.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-consortium-sharing.s3.us-west-1.amazonaws.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-consortium-sharing.s3.us-west-1.amazonaws.com. Connection pool size: 10
 75% 853/1130 [00:11<00:02, 127.35file/s]WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-iiith.s3.ap-south-1.amazonaws.com. Connection pool size: 10
 98% 1112/1130 [00:13<00:00, 138.31file/s]WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict-milan.s3.eu-south-1.amazonaws.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict-milan.s3.eu-south-1.amazonaws.com. Connection pool size: 10
100% 1130/1130 [00:13<00:00, 82.59file/s]
No existing videos to filter.
Downloading 1130 files..
100% 16.7G/16.7G [07:54<00:00, 11.9MiB/s]Checking file integrity...
100% 16.7G/16.7G [07:54<00:00, 37.8MiB/s]

In [ ]:
!ego4d --output_directory="/content/drive/MyDrive/ego4d_data" \
      --datasets annotations_540ss \
      --benchmarks FHO \
      -y

Warning: Non-standard Dataset Specfied (Allowed, will attempt download): ['annotations_540ss']
Datasets to download: {'annotations_540ss'}
Download Path: /content/drive/MyDrive/ego4d_data/v2
Ego4D Metadata: /content/drive/MyDrive/ego4d_data/ego4d.json
Checking requested datasets and versions...
Created download directory for version 'v2_1' of dataset: 'annotations_540ss' at: /content/drive/MyDrive/ego4d_data/v2/annotations_540ss
Traceback (most recent call last):
  File "/usr/local/bin/ego4d", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ego4d/cli/cli.py", line 251, in main
    main_cfg(config)
  File "/usr/local/lib/python3.12/dist-packages/ego4d/cli/cli.py", line 119, in main_cfg
    manifest_path = download_manifest_for_version(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ego4d/cli/manifest.py", line 159, in download_manifest_for_version
    _manifest_object(version, dataset, s3).download_file(str(download_path))
  File "/usr/local/lib/python3.12/dist-packages/boto3/s3/inject.py", line 392, in object_download_file
    return self.meta.client.download_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/botocore/context.py", line 123, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/boto3/s3/inject.py", line 223, in download_file
    return transfer.download_file(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/boto3/s3/transfer.py", line 407, in download_file
    future.result()
  File "/usr/local/lib/python3.12/dist-packages/s3transfer/futures.py", line 111, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/s3transfer/futures.py", line 287, in result
    raise self._exception
  File "/usr/local/lib/python3.12/dist-packages/s3transfer/tasks.py", line 272, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/s3transfer/download.py", line 359, in _submit
    response = client.head_object(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/botocore/client.py", line 602, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/botocore/context.py", line 123, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/botocore/client.py", line 1078, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden


## 📚 Get official STA metrics (Ego4D Forecasting repo)

In [ ]:
%%bash

git clone https://github.com/EGO4D/forecasting

Cloning into 'forecasting'...

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import pandas as pd

def get_directory_structure(startpath):
    data = []
    for dirpath, dirnames, filenames in os.walk(startpath):
        for f in filenames:
            filepath = os.path.join(dirpath, f)
            try:
                file_size = os.path.getsize(filepath)
                # Convert bytes to human-readable format
                for unit in ['bytes', 'KB', 'MB', 'GB', 'TB']:
                    if file_size < 1024.0:
                        human_readable_size = f"{file_size:.2f} {unit}"
                        break
                    file_size /= 1024.0
                data.append({'Path': filepath, 'Type': 'File', 'Size': human_readable_size})
            except FileNotFoundError:
                pass # Skip if file not found (e.g., broken symlink)
        for d in dirnames:
            dirpath_full = os.path.join(dirpath, d)
            data.append({'Path': dirpath_full, 'Type': 'Directory', 'Size': ''}) # Directories don't have file size in this context
    return pd.DataFrame(data)

# Set the directory to list
ego4d_data_path = "/content/drive/MyDrive/ego4d_data"

# Get the directory structure
df = get_directory_structure(ego4d_data_path)

# Define the output path in your repo
output_dir = "/content/drive/MyDrive/Ego4d-LiteSTA/file_listings"
os.makedirs(output_dir, exist_ok=True)
output_file = os.path.join(output_dir, "ego4d_file_listing.csv")

# Save the DataFrame to a CSV file
df.to_csv(output_file, index=False)

print(f"File listing saved to: {output_file}")

File listing saved to: /content/drive/MyDrive/Ego4d-LiteSTA/file_listings/ego4d_file_listing.csv

In [ ]:
import pandas as pd

output_file = "/content/drive/MyDrive/Ego4d-LiteSTA/file_listings/ego4d_file_listing.csv"

try:
    df_listing = pd.read_csv(output_file)
    display(df_listing)
except FileNotFoundError:
    print(f"File not found: {output_file}")
except Exception as e:
    print(f"An error occurred while reading the file: {e}")

,Path,Type,Size
0,/content/drive/MyDrive/ego4d_data/ego4d.json,File,85.05 MB
1,/content/drive/MyDrive/ego4d_data/v2,Directory,NaN
2,/content/drive/MyDrive/ego4d_data/v1,Directory,NaN
3,/content/drive/MyDrive/ego4d_data/v2/annotations,Directory,NaN
4,/content/drive/MyDrive/ego4d_data/v2/sta_models,Directory,NaN
...,...,...,...
2275,/content/drive/MyDrive/ego4d_data/v1/sta_model...,File,383.00 bytes
2276,/content/drive/MyDrive/ego4d_data/v1/sta_model...,File,70.83 MB
2277,/content/drive/MyDrive/ego4d_data/v1/sta_model...,File,258.61 MB
2278,/content/drive/MyDrive/ego4d_data/v1/sta_model...,File,318.12 MB
2279,/content/drive/MyDrive/ego4d_data/v1/sta_model...,File,122.12 KB


## 🧰 Load STA annotations and metadata
This cell parses the JSONs and prints a sample entry.


Annotation data documentation: https://ego4d-data.org/docs/data/annotations-schemas/

In [ ]:
import json

In [ ]:
STA_TRAIN_PATH = "/content/drive/MyDrive/ego4d_data/v1/annotations/fho_sta_train.json"
STA_VAL_PATH = "/content/drive/MyDrive/ego4d_data/v1/annotations/fho_sta_val.json"
STA_TEST_PATH = "/content/drive/MyDrive/ego4d_data/v1/annotations/fho_sta_test_unannotated.json"
OBJ_DET_PATH = "/content/drive/MyDrive/ego4d_data/v1/sta_models/object_detections.json"

In [ ]:
metadata_file_path = "/content/drive/MyDrive/ego4d_data/ego4d.json"
ego4d_meta = json.load(open(metadata_file_path))

In [ ]:
video_to_dims = {
    v["video_uid"]: {
        "frame_height": v["video_metadata"]["display_resolution_height"],
        "frame_width": v["video_metadata"]["display_resolution_width"],
    }
    for v in ego4d_meta["videos"]
}
len(video_to_dims)

9821

In [ ]:
import json
sta_train = json.load(open(STA_TRAIN_PATH))
train_video_uids = set(x.get("video_id", x.get("video_uid", None)) for x in sta_train["annotations"])

sta_val = json.load(open(STA_VAL_PATH))
val_video_uids = set(x.get("video_id", x.get("video_uid", None)) for x in sta_val["annotations"])

sta_test = json.load(open(STA_TEST_PATH))
test_video_uids = set(x.get("video_id", x.get("video_uid", None)) for x in sta_test["annotations"])

In [ ]:
#@title Load annotations & metadata
import json, random
from pathlib import Path
import os

def read_json(p):
    with open(p, "r") as f:
        return json.load(f)

assert os.path.exists(STA_VAL_PATH), f"Missing {STA_VAL_PATH}"
sta_val = read_json(STA_VAL_PATH)
sta_train = read_json(STA_TRAIN_PATH) if os.path.exists(STA_TRAIN_PATH) else {"annotations":[]}
obj_det = read_json(OBJ_DET_PATH) if os.path.exists(OBJ_DET_PATH) else {} # Use OBJ_DET_PATH instead of METADATA_JSON

def pick_sample(sta):
    anns = sta.get("annotations") or sta.get("results") or []
    if not anns:
        return None
    for a in anns:
        if a.get("clip_uid") and (a.get("video_id") or a.get("video_uid")):
            objs = a.get("objects") or a.get("targets") or []
            if objs:
                return a
    return random.choice(anns) if anns else None

sample = pick_sample(sta_val) or pick_sample(sta_train)
print("Entries — train:", len(sta_train.get("annotations",[])), "val:", len(sta_val.get("annotations",[])))
print("Picked sample keys:", list(sample.keys()) if sample else None)
if sample:
    short = {k: sample[k] for k in sample.keys() if k in ["clip_uid","video_id","video_uid","timestamp","objects"]}
    print(json.dumps(short, indent=2)[:800])

Entries — train: 27801 val: 17217
Picked sample keys: ['uid', 'video_id', 'frame', 'clip_id', 'clip_uid', 'clip_frame', 'objects']
{
  "video_id": "cde41c4f-50d1-4910-9f2a-4c7b6987df92",
  "clip_uid": "8d686451-cac9-4526-a022-b6eaf7d467b4",
  "objects": [
    {
      "box": [
        938.09,
        1350.28,
        1138.58,
        1441.4099999999999
      ],
      "verb_category_id": 62,
      "noun_category_id": 66,
      "time_to_contact": 0.9666666666666667
    }
  ]
}


## 👀 Visualize a validation sample
- Finds the **last frame** path if your `FRAMES_DIR` follows `<video_uid>/*.jpg` (adjust if your naming differs).
- Draws **one** GT box (if present) for sanity.

In [ ]:

#@title Show last frame + one GT box (val)
import os, glob, cv2, numpy as np, matplotlib.pyplot as plt

def find_last_frame_path(video_uid: str, frames_root: Path):
    folder = frames_root / video_uid
    if not folder.exists():
        return None
    jpgs = sorted(glob.glob(str(folder / "*.jpg")))
    pngs = sorted(glob.glob(str(folder / "*.png")))
    imgs = jpgs if jpgs else pngs
    return imgs[-1] if imgs else None

def draw_box(img, box, thick=2):
    x1, y1, x2, y2 = map(int, box)
    import cv2
    cv2.rectangle(img, (x1,y1), (x2,y2), (255,255,255), thickness=thick)

ann = sample
if ann is None:
    raise SystemExit("No sample available. Check your annotation files.")

video_uid = ann.get("video_id") or ann.get("video_uid")
last_frame = find_last_frame_path(video_uid, FRAMES_DIR)

print("video_uid:", video_uid)
print("Last frame path:", last_frame, "exists:", os.path.exists(last_frame) if last_frame else None)

if last_frame and os.path.exists(last_frame):
    img = cv2.imread(last_frame)[:, :, ::-1]
    H, W = img.shape[:2]
    objs = ann.get("objects", [])
    box = None
    for o in objs:
        if "box" in o:
            box = o["box"]
            break
    if box is not None:
        draw_box(img, box, thick=3)
    plt.figure(figsize=(7,7))
    plt.title(f"{video_uid} — last frame ({W}x{H})")
    plt.axis("off")
    plt.imshow(img)
    plt.show()
else:
    print("Could not locate last frame. Adjust FRAMES_DIR or naming pattern.")

NameError: name 'FRAMES_DIR' is not defined


## ✅ (Optional) Mini evaluation scaffold
If you already have a **predictions JSON** in the official format, you can run the repo’s evaluator.  
For now, we’ll create a tiny *dummy* prediction dict aligned to the val split, just to test the path.

In [ ]:

#@title Build a dummy prediction file (format only) and run evaluator
import json

val_anns = sta_val.get("annotations", [])
dummy = {"results": {}}
for a in val_anns[:50]:  # tiny subset
    clip_uid = a.get("clip_uid","unknown")
    dummy["results"][clip_uid] = []

pred_path = "/content/dummy_val_preds.json"
with open(pred_path, "w") as f:
    json.dump(dummy, f)
print("Wrote dummy file:", pred_path)
print("Next: follow forecasting/SHORT_TERM_ANTICIPATION.md to run the official evaluation on your preds.")


## ▶️ Next steps (after data works)
1. Add a lightweight backbone (e.g., **MViTv2-Tiny/Small** or **VideoMAE-S**) and a **simple STA head** that predicts **bbox + verb + noun + TTC** on the last frame.
2. (Optional) Add **hand heatmaps**/**hotspot prior** as extra channels for the last-frame head.
3. (Optional) Implement **training-free token pruning** (temporal static merge + rollout-guided keep set) to cut compute and measure **FPS vs. mAP**.
4. Always save checkpoints to **Drive** and keep runs short.

# Task
Read the file listing from "/content/drive/MyDrive/Ego4d-LiteSTA/file_listings/ego4d_file_listing.csv", then read all listed json/csv files, extract 2 samples from each, and save them as .csv files in a new folder named "ego4d_samples" within the repository.

## Load the file listing

### Subtask:
Read the `ego4d_file_listing.csv` file into a pandas DataFrame.

**Reasoning**:
The subtask is to read the `ego4d_file_listing.csv` file into a pandas DataFrame. This requires importing pandas, defining the file path, and using `pd.read_csv` to load the data.

In [ ]:
import pandas as pd

output_file = "/content/drive/MyDrive/Ego4d-LiteSTA/file_listings/ego4d_file_listing.csv"
df_listing = pd.read_csv(output_file)
display(df_listing.head())

                                               Path       Type      Size
0      /content/drive/MyDrive/ego4d_data/ego4d.json       File  85.05 MB
1              /content/drive/MyDrive/ego4d_data/v2  Directory       NaN
2              /content/drive/MyDrive/ego4d_data/v1  Directory       NaN
3  /content/drive/MyDrive/ego4d_data/v2/annotations  Directory       NaN
4   /content/drive/MyDrive/ego4d_data/v2/sta_models  Directory       NaN

## Identify json and csv files

### Subtask:
Filter the DataFrame to get a list of paths for JSON and CSV files.

**Reasoning**:
Filter the DataFrame to get a list of paths for JSON and CSV files.

In [ ]:
file_paths_df = df_listing[df_listing['Type'] == 'File']['Path']
file_paths_list = file_paths_df.tolist()
json_csv_files = [f for f in file_paths_list if f.endswith('.json') or f.endswith('.csv')]
print(json_csv_files[:10]) # Print first 10 to check

['/content/drive/MyDrive/ego4d_data/ego4d.json', '/content/drive/MyDrive/ego4d_data/v2/annotations/fho_lta_taxonomy.json', '/content/drive/MyDrive/ego4d_data/v2/annotations/fho_hands_test_unannotated.json', '/content/drive/MyDrive/ego4d_data/v2/annotations/fho_lta_test_unannotated.json', '/content/drive/MyDrive/ego4d_data/v2/annotations/fho_oscc-pnr_test_unannotated.json', '/content/drive/MyDrive/ego4d_data/v2/annotations/fho_oscc-pnr_val.json', '/content/drive/MyDrive/ego4d_data/v2/annotations/fho_lta_val.json', '/content/drive/MyDrive/ego4d_data/v2/annotations/fho_main_taxonomy.json', '/content/drive/MyDrive/ego4d_data/v2/annotations/fho_lta_train.json', '/content/drive/MyDrive/ego4d_data/v2/annotations/fho_oscc-pnr_train.json']

## Create output directory

### Subtask:
Create a new directory named `ego4d_samples` inside the repository to save the sample files.

**Reasoning**:
Create the new directory `ego4d_samples` within the repository's working directory.

In [ ]:
import os

# Define the repository's working directory (assuming it's WORKDIR as defined earlier)
repo_workdir = WORKDIR # WORKDIR is defined in a previous cell

# Define the path for the new directory
samples_dir = os.path.join(repo_workdir, "ego4d_samples")

# Create the directory if it doesn't exist
os.makedirs(samples_dir, exist_ok=True)

# Print confirmation
if os.path.exists(samples_dir):
    print(f"Directory '{samples_dir}' already exists or was created successfully.")
else:
    print(f"Failed to create directory '{samples_dir}'.")

Directory '/content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples' already exists or was created successfully.

## Process each file

### Subtask:
Iterate through the list of JSON and CSV file paths and extract 2 samples from each.

**Reasoning**:
Iterate through the list of JSON and CSV file paths and extract 2 samples from each.

In [ ]:
import json
import pandas as pd

extracted_samples = {}

for file_path in json_csv_files:
    try:
        if file_path.endswith('.csv'):
            df = pd.read_csv(file_path)
            extracted_samples[file_path] = df.head(2).to_dict(orient='records')
        elif file_path.endswith('.json'):
            with open(file_path, 'r') as f:
                data = json.load(f)

            # Attempt to extract samples based on common JSON structures
            if isinstance(data, list) and len(data) > 0:
                extracted_samples[file_path] = data[:2]
            elif isinstance(data, dict):
                # Look for a key that is a list and take samples from there
                sample_found = False
                for key, value in data.items():
                    if isinstance(value, list) and len(value) > 0:
                        extracted_samples[file_path] = {key: value[:2]}
                        sample_found = True
                        break
                if not sample_found:
                     # If no list found, just take the first 2 key-value pairs
                    extracted_samples[file_path] = dict(list(data.items())[:2])

    except Exception as e:
        print(f"Error processing file {file_path}: {e}")

print(f"Extracted samples from {len(extracted_samples)} files.")

Extracted samples from 69 files.

**Reasoning**:
Save the extracted samples as individual CSV files in the designated output directory.

In [ ]:
import os
import pandas as pd

# Define the output directory (samples_dir is already defined)
# samples_dir = os.path.join(WORKDIR, "ego4d_samples")

for file_path, samples in extracted_samples.items():
    try:
        # Create a safe filename from the original path
        base_name = os.path.basename(file_path)
        name, ext = os.path.splitext(base_name)

        # Determine the format extension for the output filename
        if file_path.endswith('.csv'):
            format_ext = 'csv'
        elif file_path.endswith('.json'):
            format_ext = 'json'
        else:
            # Skip if the file is neither json nor csv
            print(f"Skipping file {file_path} as it is not a .json or .csv file.")
            continue

        output_filename = f"{name}_{format_ext}.csv"


        # Construct the relative path from the ego4d_data directory
        # Assuming file_path starts with /content/drive/MyDrive/ego4d_data/
        relative_path = os.path.relpath(file_path, "/content/drive/MyDrive/ego4d_data/")

        # Construct the output directory path within ego4d_samples, mirroring the original structure
        output_subdir = os.path.join(samples_dir, os.path.dirname(relative_path))

        # Create the output subdirectory if it doesn't exist
        os.makedirs(output_subdir, exist_ok=True)

        # Construct the full output path
        output_path = os.path.join(output_subdir, output_filename)


        # Convert the samples (whether from JSON or CSV) into a DataFrame
        # This handles both list of dicts (from json list or csv head) and dict of lists (from json dict)
        if isinstance(samples, list):
             df_samples = pd.DataFrame(samples)
        elif isinstance(samples, dict):
             df_samples = pd.DataFrame.from_dict(samples, orient='index').transpose() # handle dict of lists
        else:
             print(f"Unexpected sample format for {file_path}. Skipping save.")
             continue


        # Save the DataFrame to a CSV file
        df_samples.to_csv(output_path, index=False)

        print(f"Saved samples from {base_name} to {output_path}")

    except Exception as e:
        print(f"Error saving samples for file {file_path}: {e}")

Saved samples from ego4d.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/ego4d_json.csv
Saved samples from fho_lta_taxonomy.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/fho_lta_taxonomy_json.csv
Saved samples from fho_hands_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/fho_hands_test_unannotated_json.csv
Saved samples from fho_lta_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/fho_lta_test_unannotated_json.csv
Saved samples from fho_oscc-pnr_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/fho_oscc-pnr_test_unannotated_json.csv
Saved samples from fho_oscc-pnr_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/fho_oscc-pnr_val_json.csv
Saved samples from fho_lta_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/fho_lta_val_json.csv
Saved samples from fho_main_taxonomy.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/fho_main_taxonomy_json.csv
Saved samples from fho_lta_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/fho_lta_train_json.csv
Saved samples from fho_oscc-pnr_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/fho_oscc-pnr_train_json.csv
Saved samples from fho_sta_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/fho_sta_test_unannotated_json.csv
Saved samples from fho_sta_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/fho_sta_val_json.csv
Saved samples from manifest.csv to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/manifest_csv.csv
Saved samples from narration_verb_taxonomy.csv to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/narration_verb_taxonomy_csv.csv
Saved samples from narration_noun_taxonomy.csv to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/narration_noun_taxonomy_csv.csv
Saved samples from all_narrations_redacted.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/all_narrations_redacted_json.csv
Saved samples from av_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/av_test_unannotated_json.csv
Saved samples from narration.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/narration_json.csv
Saved samples from av_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/av_train_json.csv
Saved samples from av_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/av_val_json.csv
Saved samples from moments_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/moments_test_unannotated_json.csv
Saved samples from moments_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/moments_val_json.csv
Saved samples from moments_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/moments_train_json.csv
Saved samples from nlq_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/nlq_train_json.csv
Saved samples from nlq_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/nlq_val_json.csv
Saved samples from nlq_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/nlq_test_unannotated_json.csv
Saved samples from vq_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/vq_train_json.csv
Saved samples from vq_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/vq_val_json.csv
Saved samples from vq_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/vq_test_unannotated_json.csv
Saved samples from fho_main.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/fho_main_json.csv
Saved samples from fho_sta_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/annotations/fho_sta_train_json.csv
Saved samples from manifest.csv to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/sta_models/manifest_csv.csv
Saved samples from object_detections.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/sta_models/object_detections_json.csv
Saved samples from manifest.csv to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v2/omnivore_video_swinl_fp16/manifest_csv.csv
Saved samples from manifest.csv to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/omnivore_video_swinl_fp16/manifest_csv.csv
Saved samples from manifest.csv to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/manifest_csv.csv
Saved samples from narration.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/narration_json.csv
Saved samples from narration_verb_taxonomy.csv to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/narration_verb_taxonomy_csv.csv
Saved samples from av_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/av_train_json.csv
Saved samples from narration_noun_taxonomy.csv to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/narration_noun_taxonomy_csv.csv
Saved samples from av_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/av_test_unannotated_json.csv
Saved samples from av_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/av_val_json.csv
Saved samples from moments_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/moments_test_unannotated_json.csv
Saved samples from moments_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/moments_train_json.csv
Saved samples from nlq_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/nlq_val_json.csv
Saved samples from moments_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/moments_val_json.csv
Saved samples from nlq_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/nlq_train_json.csv
Saved samples from nlq_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/nlq_test_unannotated_json.csv
Saved samples from vq_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/vq_val_json.csv
Saved samples from vq_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/vq_train_json.csv
Saved samples from vq_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/vq_test_unannotated_json.csv
Saved samples from fho_scod_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_scod_train_json.csv
Saved samples from fho_scod_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_scod_val_json.csv
Saved samples from fho_hands_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_hands_train_json.csv
Saved samples from fho_hands_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_hands_val_json.csv
Saved samples from fho_sta_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_sta_val_json.csv
Saved samples from fho_sta_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_sta_train_json.csv
Saved samples from fho_lta_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_lta_train_json.csv
Saved samples from fho_lta_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_lta_val_json.csv
Saved samples from fho_lta_taxonomy.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_lta_taxonomy_json.csv
Saved samples from fho_oscc-pnr_train.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_oscc-pnr_train_json.csv
Saved samples from fho_oscc-pnr_val.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_oscc-pnr_val_json.csv
Saved samples from fho_sta_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_sta_test_unannotated_json.csv
Saved samples from fho_oscc-pnr_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_oscc-pnr_test_unannotated_json.csv
Saved samples from fho_lta_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_lta_test_unannotated_json.csv
Saved samples from fho_hands_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_hands_test_unannotated_json.csv
Saved samples from fho_scod_test_unannotated.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/annotations/fho_scod_test_unannotated_json.csv
Saved samples from manifest.csv to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/sta_models/manifest_csv.csv
Saved samples from object_detections.json to /content/drive/MyDrive/Ego4d-LiteSTA/ego4d_samples/v1/sta_models/object_detections_json.csv

## Summary:

### Data Analysis Key Findings

*   The analysis successfully loaded a file listing from `ego4d_file_listing.csv`, identifying 69 JSON and CSV files.
*   A new directory named `ego4d_samples` was created within the repository's working directory.
*   The process iterated through the identified files, extracting the first two rows from each CSV file and attempting to extract two samples from JSON files by handling list and dictionary structures.
*   Samples from all 69 files were successfully extracted and converted into pandas DataFrames.
*   Each set of extracted samples was saved as a separate CSV file in the `ego4d_samples` directory, using a derived filename format (e.g., `original_file_samples.csv`).

### Insights or Next Steps

*   The generated sample files can be used for initial exploration and understanding of the data structure and content within the large Ego4D dataset without needing to load the full files.
*   Further analysis could involve examining the content of these sample files to identify common data fields and structures across different file types, which could inform the design of a unified data processing pipeline.

In [ ]:
import json
import os

STA_TRAIN_PATH_V2 = "/content/drive/MyDrive/ego4d_data/v2/annotations/fho_sta_train.json"
STA_VAL_PATH_V2 = "/content/drive/MyDrive/ego4d_data/v2/annotations/fho_sta_val.json"
OUTPUT_JSON_PATH = "/content/drive/MyDrive/ego4d_data/extracted_sta_data.json"

extracted_data = []

# Process train data
if os.path.exists(STA_TRAIN_PATH_V2):
    with open(STA_TRAIN_PATH_V2, 'r') as f:
        train_data = json.load(f)
        for annotation in train_data.get("annotations", []):
            for obj in annotation.get("objects", []):
                extracted_data.append({
                    "video_uid": annotation.get("video_uid", annotation.get("video_id")),
                    "frame": annotation.get("frame"),
                    "box": obj.get("box"),
                    "verb_category_id": obj.get("verb_category_id"),
                    "noun_category_id": obj.get("noun_category_id"),
                    "time_to_contact": obj.get("time_to_contact")
                })
else:
    print(f"Train data not found at {STA_TRAIN_PATH_V2}")

# Process val data
if os.path.exists(STA_VAL_PATH_V2):
    with open(STA_VAL_PATH_V2, 'r') as f:
        val_data = json.load(f)
        for annotation in val_data.get("annotations", []):
             for obj in annotation.get("objects", []):
                extracted_data.append({
                    "video_uid": annotation.get("video_uid", annotation.get("video_id")),
                    "frame": annotation.get("frame"),
                    "box": obj.get("box"),
                    "verb_category_id": obj.get("verb_category_id"),
                    "noun_category_id": obj.get("noun_category_id"),
                    "time_to_contact": obj.get("time_to_contact")
                })
else:
    print(f"Validation data not found at {STA_VAL_PATH_V2}")


# Save the extracted data to a new JSON file, one object per line
with open(OUTPUT_JSON_PATH, 'w') as f:
    for record in extracted_data:
        json.dump(record, f)
        f.write('\n') # Write each JSON object on a new line

print(f"Extracted data saved to {OUTPUT_JSON_PATH} in NDJSON format.")
print(f"Number of records extracted: {len(extracted_data)}")

Extracted data saved to /content/drive/MyDrive/ego4d_data/extracted_sta_data.json in NDJSON format.
Number of records extracted: 152075

In [ ]:
import json
import os

INPUT_JSON_PATH = "/content/drive/MyDrive/ego4d_data/extracted_sta_data.json"
OUTPUT_UIDS_PATH = "/content/drive/MyDrive/ego4d_data/sta_uids.txt"

# Load the extracted data line by line
extracted_data = []
if os.path.exists(INPUT_JSON_PATH):
    try:
        with open(INPUT_JSON_PATH, 'r') as f:
            for line in f:
                try:
                    # Attempt to load each line as a JSON object
                    item = json.loads(line)
                    extracted_data.append(item)
                except json.JSONDecodeError:
                    # Skip lines that are not valid JSON
                    continue
    except Exception as e:
        print(f"An error occurred while reading the file line by line: {e}")
else:
    print(f"Input data not found at {INPUT_JSON_PATH}")


# Extract unique video UIDs
video_uids = sorted(list(set([item.get("video_uid") for item in extracted_data if isinstance(item, dict) and item.get("video_uid")])))


# Save the unique video UIDs to a text file
with open(OUTPUT_UIDS_PATH, 'w') as f:
    for uid in video_uids:
        f.write(uid + "\n")

print(f"Unique video UIDs saved to {OUTPUT_UIDS_PATH}")
print(f"Number of unique video UIDs: {len(video_uids)}")

Unique video UIDs saved to /content/drive/MyDrive/ego4d_data/sta_uids.txt
Number of unique video UIDs: 1311

In [ ]:
import json
import os

INPUT_JSON_PATH = "/content/drive/MyDrive/ego4d_data/extracted_sta_data.json"
OUT_LISTS = "/content/drive/MyDrive/ego4d_data/v2/tmp_frame_lists"

# Create the output directory if it doesn't exist
os.makedirs(OUT_LISTS, exist_ok=True)

# Load the extracted data line by line
extracted_data = []
if os.path.exists(INPUT_JSON_PATH):
    try:
        with open(INPUT_JSON_PATH, 'r') as f:
            for line in f:
                try:
                    # Attempt to load each line as a JSON object
                    item = json.loads(line)
                    extracted_data.append(item)
                except json.JSONDecodeError:
                    # Skip lines that are not valid JSON
                    continue
    except Exception as e:
        print(f"An error occurred while reading the file line by line: {e}")
else:
    print(f"Input data not found at {INPUT_JSON_PATH}")

# Group frames by video UID
video_frames = {}
for record in extracted_data:
    video_uid = record.get("video_uid")
    frame = record.get("frame")
    if video_uid and frame is not None:
        if video_uid not in video_frames:
            video_frames[video_uid] = []
        video_frames[video_uid].append(frame)

# Sort frames and write to files
for video_uid, frames in video_frames.items():
    sorted_frames = sorted(list(set(frames))) # Get unique and sorted frames
    output_file = os.path.join(OUT_LISTS, f"{video_uid}.txt")
    with open(output_file, 'w') as f:
        for frame in sorted_frames:
            f.write(str(frame) + "\n")

print(f"Per-video frame lists saved to {OUT_LISTS}")
print(f"Generated frame lists for {len(video_frames)} videos.")

Per-video frame lists saved to /content/drive/MyDrive/ego4d_data/v2/tmp_frame_lists
Generated frame lists for 1311 videos.

In [ ]:
# Download video, extract frames, verify, and delete video to save storage
import os
import subprocess
import random
import time
import shutil

# =======================
# Config (edit as needed)
# =======================
UID_LIST_FILE = "/content/drive/MyDrive/ego4d_data/sta_uids.txt"          # File with one video_uid per line
VERSION = "v2"                                                            # Ego4D version
OUTPUT_DIR_BASE = "/content/drive/MyDrive/ego4d_data"                     # Ego4D root
VIDEO_DIR = os.path.join(OUTPUT_DIR_BASE, VERSION, "full_scale")          # Where CLI stores videos
FRAMES_ROOT = os.path.join(OUTPUT_DIR_BASE, VERSION, "frames")            # Where we save extracted frames
FRAME_LISTS_DIR = os.path.join(OUTPUT_DIR_BASE, VERSION, "tmp_frame_lists")  # Per-video *_frames.txt
DEMO_MODE = True
NUM_DEMO_VIDEOS = 1
FFMPEG_TIMEOUT_SECS = 1800
DOWNLOAD_TIMEOUT_SECS = 3600

# Ensure output directories exist
os.makedirs(OUTPUT_DIR_BASE, exist_ok=True)
os.makedirs(VIDEO_DIR, exist_ok=True)
os.makedirs(FRAMES_ROOT, exist_ok=True)
os.makedirs(FRAME_LISTS_DIR, exist_ok=True)

def which_or_msg(cmd):
    """Return True if binary exists, else print a hint."""
    path = shutil.which(cmd)
    if not path:
        print(f"Error: '{cmd}' not found on PATH. Please install it.")
        return False
    return True

def read_uid_list(path):
    with open(path, "r") as f:
        return [line.strip() for line in f if line.strip()]

def read_frame_list(path):
    with open(path, "r") as f:
        return [int(x.strip()) for x in f if x.strip()]

def download_video_with_cli(video_uid):
    """
    Use ego4d CLI to download just one video (full_scale) and annotations bucket (cheap),
    constrained to the given UID.
    """
    cmd = [
        "ego4d",
        "--output_directory", OUTPUT_DIR_BASE,
        "--datasets", "full_scale",
        "--version", VERSION,
        "--video_uids", video_uid,
        "-y",
    ]
    print("  Running:", " ".join(cmd))
    start = time.time()
    res = subprocess.run(cmd, text=True, capture_output=True, check=True, timeout=DOWNLOAD_TIMEOUT_SECS)
    dur = time.time() - start
    print(f"  Download OK in {dur:.1f}s")
    # Uncomment for debugging:
    # print(res.stdout)
    # print(res.stderr)

def extract_selected_frames(video_path, frame_list_path, out_dir):
    """
    Extract exactly the frames listed in frame_list_path using ffmpeg 'select'.
    We build the comma-separated list in Python → no need for shell tricks/backticks.
    """
    frames = read_frame_list(frame_list_path)
    if not frames:
        print("  Warning: frame list is empty, skipping extraction.")
        return 0, 0

    frames_csv = ",".join(str(x) for x in frames)
    select_expr = f"select='in(n\\,{frames_csv})',setpts=N/FRAME_RATE/TB"

    os.makedirs(out_dir, exist_ok=True)
    cmd = [
        "ffmpeg",
        "-i", video_path,
        "-vf", select_expr,
        "-vsync", "0",
        os.path.join(out_dir, "%07d.jpg"),
    ]

    print("  Running:", " ".join(cmd))
    start = time.time()
    res = subprocess.run(cmd, text=True, capture_output=True, check=True, timeout=FFMPEG_TIMEOUT_SECS)
    dur = time.time() - start
    print(f"  Extraction OK in {dur:.1f}s")
    # Uncomment to debug:
    # print(res.stdout)
    # print(res.stderr)

    extracted = len([f for f in os.listdir(out_dir) if f.lower().endswith(".jpg")])
    requested = len(frames)
    return extracted, requested

def print_free_storage():
    total, used, free = shutil.disk_usage("/content/drive")
    free_gb = free / (1024**3)
    print(f"  Remaining Google Drive storage: {free_gb:.2f} GB")

# ==========================
# Main guarded control flow
# ==========================
if os.path.exists(UID_LIST_FILE):
    try:
        # Pre-flight checks
        if not which_or_msg("ffmpeg") or not which_or_msg("ego4d"):
            raise RuntimeError("Required binaries missing (ffmpeg and/or ego4d).")

        all_uids = read_uid_list(UID_LIST_FILE)
        print(f"Loaded {len(all_uids)} UIDs from: {UID_LIST_FILE}")

        # Only process UIDs for which we have *_frames.txt prepared
        lists = [f for f in os.listdir(FRAME_LISTS_DIR) if f.endswith("_frames.txt")]
        uids_with_lists = {f.replace("_frames.txt", "") for f in lists}
        processable = [uid for uid in all_uids if uid in uids_with_lists]

        if not processable:
            print("No processable UIDs found (no matching *_frames.txt). Nothing to do.")
        else:
            if DEMO_MODE and len(processable) > NUM_DEMO_VIDEOS:
                print(f"Demo mode: selecting {NUM_DEMO_VIDEOS} random videos out of {len(processable)}.")
                import random
                uids_to_process = random.sample(processable, NUM_DEMO_VIDEOS)
            else:
                uids_to_process = processable
                if DEMO_MODE:
                    print(f"Demo mode: fewer than {NUM_DEMO_VIDEOS} available; processing {len(uids_to_process)}.")

            print(f"Selected {len(uids_to_process)} video(s): {uids_to_process}")

            for idx, vid in enumerate(uids_to_process, 1):
                print(f"\nProcessing {idx}/{len(uids_to_process)}: {vid}")
                video_path = os.path.join(VIDEO_DIR, f"{vid}.mp4")
                frame_list_path = os.path.join(FRAME_LISTS_DIR, f"{vid}_frames.txt")
                out_dir = os.path.join(FRAMES_ROOT, vid)

                # 1) Download video if missing
                if not os.path.exists(video_path):
                    print(f"  Video not found. Downloading: {vid}")
                    try:
                        download_video_with_cli(vid)
                        print_free_storage()
                    except subprocess.TimeoutExpired:
                        print("  ERROR: Download timed out.")
                        continue
                    except subprocess.CalledProcessError as e:
                        print("  ERROR: ego4d CLI failed.")
                        print("  stdout:", e.stdout)
                        print("  stderr:", e.stderr)
                        continue
                    except FileNotFoundError:
                        print("  ERROR: ego4d CLI not found on PATH.")
                        break
                    except Exception as e:
                        print(f"  ERROR: Unexpected download error: {e}")
                        continue
                else:
                    print("  Video already present; skipping download.")

                # 2) Extract frames
                if not os.path.exists(frame_list_path):
                    print(f"  ERROR: Missing frame list: {frame_list_path}. Skipping.")
                    continue

                try:
                    extracted, requested = extract_selected_frames(video_path, frame_list_path, out_dir)
                    print(f"  Verification: extracted={extracted}, requested={requested}")
                    if extracted < requested:
                        print("  WARNING: Fewer frames extracted than requested (check logs).")
                except subprocess.TimeoutExpired:
                    print("  ERROR: ffmpeg extraction timed out.")
                    continue
                except subprocess.CalledProcessError as e:
                    print("  ERROR: ffmpeg failed.")
                    print("  stdout:", e.stdout)
                    print("  stderr:", e.stderr)
                    continue
                except FileNotFoundError:
                    print("  ERROR: ffmpeg not found on PATH.")
                    continue
                except Exception as e:
                    print(f"  ERROR: Unexpected extraction error: {e}")
                    continue

                # 3) Delete .mp4 to save storage
                if os.path.exists(video_path):
                    try:
                        os.remove(video_path)
                        print(f"  Deleted video: {video_path}")
                        print_free_storage()
                    except Exception as e:
                        print(f"  WARNING: Could not delete {video_path}: {e}")

        print("\nDemo video processing (download, extract, verify, delete) complete.")

    except Exception as e:
        print(f"Error loading UIDs from {UID_LIST_FILE}: {e}")
else:
    print(f"Error: UID list file not found at {UID_LIST_FILE}.")

# Frame extraction

In [ ]:
# Download video, extract frames, verify, and delete video to save storage
import os
import subprocess
import random
import time
import shutil

# =======================
# Config (edit as needed)
# =======================
UID_LIST_FILE = "/content/drive/MyDrive/ego4d_data/sta_uids.txt"          # File with one video_uid per line
VERSION = "v2"                                                            # Ego4D version
OUTPUT_DIR_BASE = "/content/drive/MyDrive/ego4d_data"                     # Ego4D root
VIDEO_DIR = os.path.join(OUTPUT_DIR_BASE, VERSION, "full_scale")          # Where CLI stores videos
FRAMES_ROOT = os.path.join(OUTPUT_DIR_BASE, VERSION, "frames")            # Where we save extracted frames
FRAME_LISTS_DIR = os.path.join(OUTPUT_DIR_BASE, VERSION, "tmp_frame_lists")  # Per-video *.txt
DEMO_MODE = True
NUM_DEMO_VIDEOS = 2
FFMPEG_TIMEOUT_SECS = 1800
DOWNLOAD_TIMEOUT_SECS = 3600

# Frame extraction configuration
# Set to a number for a fixed number of frames, or set to "all" to extract all frames
FRAME_EXTRACTION_MODE = "1" # <<< EDIT ME: "all" or number of frames (e.g., 10)


# Ensure output directories exist
os.makedirs(OUTPUT_DIR_BASE, exist_ok=True)
os.makedirs(VIDEO_DIR, exist_ok=True)
os.makedirs(FRAMES_ROOT, exist_ok=True)
os.makedirs(FRAME_LISTS_DIR, exist_ok=True)

def which_or_msg(cmd):
    """Return True if binary exists, else print a hint."""
    path = shutil.which(cmd)
    if not path:
        print(f"Error: '{cmd}' not found on PATH. Please install it.")
        return False
    return True

def read_uid_list(path):
    with open(path, "r") as f:
        return [line.strip() for line in f if line.strip()]

def read_frame_list(path):
    with open(path, "r") as f:
        return [int(x.strip()) for x in f if x.strip()]

def download_video_with_cli(video_uid):
    """
    Use ego4d CLI to download just one video (full_scale),
    constrained to the given UID.
    """
    cmd = [
        "ego4d",
        "--output_directory", OUTPUT_DIR_BASE,
        "--datasets", "full_scale",
        "--version", VERSION,
        "--video_uids", video_uid,
        "-y",
    ]
    print("  Running:", " ".join(cmd))
    start = time.time()

    # Configure AWS CLI temporarily
    aws_access_key_id = os.environ.get('AWS_ACCESS_KEY_ID', '')
    aws_secret_access_key = os.environ.get('AWS_SECRET_ACCESS_KEY', '')

    if not aws_access_key_id or not aws_secret_access_key:
        print("  WARNING: AWS credentials not found in environment variables. Download might fail.")
        # Attempt to run without explicit configuration if credentials are not set
        res = subprocess.run(cmd, text=True, capture_output=True, check=True, timeout=DOWNLOAD_TIMEOUT_SECS)

    else:
        # Create a temporary AWS config file
        aws_config_dir = os.path.join(os.path.expanduser("~"), ".aws")
        os.makedirs(aws_config_dir, exist_ok=True)
        aws_config_path = os.path.join(aws_config_dir, "credentials")

        with open(aws_config_path, "w") as f:
            f.write("[default]\n")
            f.write(f"aws_access_key_id = {aws_access_key_id}\n")
            f.write(f"aws_secret_access_key = {aws_secret_access_key}\n")

        # Unset AWS environment variables before calling ego4d to ensure it uses the config file
        env_vars = os.environ.copy()
        if 'AWS_ACCESS_KEY_ID' in env_vars:
            del env_vars['AWS_ACCESS_KEY_ID']
        if 'AWS_SECRET_ACCESS_KEY' in env_vars:
            del env_vars['AWS_SECRET_ACCESS_KEY']

        try:
            res = subprocess.run(cmd, text=True, capture_output=True, check=True, timeout=DOWNLOAD_TIMEOUT_SECS, env=env_vars)
        finally:
            # Clean up the temporary AWS config file
            if os.path.exists(aws_config_path):
                os.remove(aws_config_path)

    dur = time.time() - start
    print(f"  Download OK in {dur:.1f}s")
    # Uncomment for debugging:
    # print(res.stdout)
    # print(res.stderr)


def extract_frames(video_path, frames_to_extract, out_dir):
    """
    Extract the specified frames using ffmpeg.
    Handles extracting all frames or a specific list of frame numbers.
    """
    os.makedirs(out_dir, exist_ok=True)

    if frames_to_extract == "all":
        # Extract all frames
        ffmpeg_command = [
            "ffmpeg",
            "-i", video_path,
            os.path.join(out_dir, "%07d.jpg"),
        ]
        print(f"  Running ffmpeg command to extract all frames: {' '.join(ffmpeg_command)}")
        start = time.time()
        res = subprocess.run(ffmpeg_command, check=True, capture_output=True, text=True, timeout=FFMPEG_TIMEOUT_SECS)
        dur = time.time() - start
        print(f"  Extraction OK in {dur:.1f}s")

    elif isinstance(frames_to_extract, list):
        # Extract specific frames by index
        # Use a more robust method for potentially large lists of frames
        extracted_count = 0
        for frame_num in frames_to_extract:
            output_frame_path = os.path.join(out_dir, f"{frame_num:07d}.jpg")
            ffmpeg_command = [
                "ffmpeg",
                "-i", video_path,
                "-vf", f"select='eq(n,{frame_num})'",
                "-vframes", "1",
                "-vsync", "0",
                output_frame_path
            ]
            # print(f"  Running ffmpeg command for frame {frame_num}: {' '.join(ffmpeg_command)}")
            try:
                subprocess.run(ffmpeg_command, check=True, capture_output=True, text=True, timeout=FFMPEG_TIMEOUT_SECS)
                if os.path.exists(output_frame_path):
                     extracted_count += 1
            except subprocess.TimeoutExpired:
                 print(f"  ERROR: ffmpeg extraction timed out for frame {frame_num}.")
                 continue
            except subprocess.CalledProcessError as e:
                 print(f"  ERROR: ffmpeg failed for frame {frame_num}.")
                 # print("  stdout:", e.stdout)
                 # print("  stderr:", e.stderr)
                 continue
            except FileNotFoundError:
                 print("  ERROR: ffmpeg not found on PATH. Cannot extract frames.")
                 break # Stop processing this video if ffmpeg is not found
            except Exception as e:
                 print(f"  ERROR: Unexpected extraction error for frame {frame_num}: {e}")
                 continue

        return extracted_count

    else:
        print(f"  ERROR: Invalid frames_to_extract type: {type(frames_to_extract)}. Skipping extraction.")
        return 0

    extracted_count = len([f for f in os.listdir(out_dir) if f.lower().endswith(".jpg")])
    return extracted_count


def print_free_storage():
    total, used, free = shutil.disk_usage("/content/drive")
    free_gb = free / (1024**3)
    print(f"  Remaining Google Drive storage: {free_gb:.2f} GB")

# ==========================
# Main guarded control flow
# ==========================
if os.path.exists(UID_LIST_FILE):
    try:
        # Pre-flight checks
        if not which_or_msg("ffmpeg") or not which_or_msg("ego4d"):
            raise RuntimeError("Required binaries missing (ffmpeg and/or ego4d).")

        all_uids = read_uid_list(UID_LIST_FILE)
        print(f"Loaded {len(all_uids)} UIDs from: {UID_LIST_FILE}")

        # Only process UIDs for which we have *.txt prepared
        lists = [f for f in os.listdir(FRAME_LISTS_DIR) if f.endswith(".txt")]
        uids_with_lists = {f.replace(".txt", "") for f in lists}
        processable = [uid for uid in all_uids if uid in uids_with_lists]

        if not processable:
            print("No processable UIDs found (no matching *.txt). Nothing to do.")
        else:
            if DEMO_MODE and len(processable) > NUM_DEMO_VIDEOS:
                print(f"Demo mode: selecting {NUM_DEMO_VIDEOS} random videos out of {len(processable)}.")
                import random
                uids_to_process = random.sample(processable, NUM_DEMO_VIDEOS)
            else:
                uids_to_process = processable
                if DEMO_MODE:
                    print(f"Demo mode: fewer than {NUM_DEMO_VIDEOS} available; processing {len(uids_to_process)}.")


            print(f"Selected {len(uids_to_process)} video(s): {uids_to_process}")

            for idx, vid in enumerate(uids_to_process, 1):
                print(f"\nProcessing {idx}/{len(uids_to_process)}: {vid}")
                video_path = os.path.join(VIDEO_DIR, f"{vid}.mp4")
                frame_list_path = os.path.join(FRAME_LISTS_DIR, f"{vid}.txt")
                out_dir = os.path.join(FRAMES_ROOT, vid)


                # 1) Download video if missing
                if not os.path.exists(video_path):
                    print(f"  Video not found. Downloading: {vid}")
                    try:
                        download_video_with_cli(vid)
                        print_free_storage()
                    except subprocess.TimeoutExpired:
                        print("  ERROR: Download timed out.")
                        continue
                    except subprocess.CalledProcessError as e:
                        print("  ERROR: ego4d CLI failed.")
                        print("  stdout:", e.stdout)
                        print("  stderr:", e.stderr)
                        continue
                    except FileNotFoundError:
                        print("  ERROR: ego4d CLI not found on PATH.")
                        break
                    except Exception as e:
                        print(f"  ERROR: Unexpected download error: {e}")
                        continue
                else:
                    print("  Video already present; skipping download.")

                # 2) Determine frames to extract based on configuration
                frames_to_extract = []
                requested_count = 0
                if FRAME_EXTRACTION_MODE == "all":
                    frames_to_extract = "all" # Indicate to extract all frames
                    requested_count = "all"
                elif os.path.exists(frame_list_path):
                    frames_from_list = read_frame_list(frame_list_path)
                    if isinstance(FRAME_EXTRACTION_MODE, int) and FRAME_EXTRACTION_MODE > 0:
                         # Extract a specific number of frames from the list
                         # If FRAME_EXTRACTION_MODE is 1, just take the first frame
                         if FRAME_EXTRACTION_MODE == 1 and frames_from_list:
                             frames_to_extract = [frames_from_list[0]]
                         else:
                             frames_to_extract = random.sample(frames_from_list, min(FRAME_EXTRACTION_MODE, len(frames_from_list)))
                         requested_count = len(frames_to_extract)
                    else:
                         # Extract all frames from the list if FRAME_EXTRACTION_MODE is not a positive integer
                         frames_to_extract = frames_from_list
                         requested_count = len(frames_to_extract)

                    if not frames_to_extract:
                         print(f"  Warning: No frames selected for extraction from {frame_list_path}. Skipping.")
                         continue

                else:
                    print(f"  ERROR: Missing frame list: {frame_list_path} and FRAME_EXTRACTION_MODE is not 'all'. Skipping.")
                    continue


                print(f"  Extracting frames...")
                extracted_count = extract_frames(video_path, frames_to_extract, out_dir)

                if FRAME_EXTRACTION_MODE != "all":
                    print(f"  Verification: extracted={extracted_count}, requested={requested_count}")
                    if extracted_count < requested_count:
                        print("  WARNING: Fewer frames extracted than requested (check logs).")
                else:
                    print(f"  Extracted all available frames: {extracted_count}")


                # 3) Delete .mp4 to save storage
                if os.path.exists(video_path):
                    try:
                        os.remove(video_path)
                        print(f"  Deleted video: {video_path}")
                        print_free_storage()
                    except Exception as e:
                        print(f"  WARNING: Could not delete {video_path}: {e}")

        print("\nDemo video processing (download, extract, verify, delete) complete.")

    except Exception as e:
        print(f"An error occurred during processing: {e}")
else:
    print(f"Error: UID list file not found at {UID_LIST_FILE}.")

Loaded 1311 UIDs from: /content/drive/MyDrive/ego4d_data/sta_uids.txt
Demo mode: selecting 2 random videos out of 1311.
Selected 2 video(s): ['b4a8cf83-6f0e-40ca-811a-f1e1435d501f', '5d8ebbea-6371-4be5-b611-751fb49ec294']

Processing 1/2: b4a8cf83-6f0e-40ca-811a-f1e1435d501f
  Video not found. Downloading: b4a8cf83-6f0e-40ca-811a-f1e1435d501f
  Running: ego4d --output_directory /content/drive/MyDrive/ego4d_data --datasets full_scale --version v2 --video_uids b4a8cf83-6f0e-40ca-811a-f1e1435d501f -y
  Download OK in 7.1s
  Remaining Google Drive storage: 58.79 GB
  Extracting frames...

KeyboardInterrupt:

In [ ]:
import subprocess
import os

# Define the input video path
input_video_path = "/content/drive/MyDrive/ego4d_data/v2/full_scale/c0ca834d-5e1b-4150-97b0-7a8170f0094c.mp4"

# Define the output directory and filename
output_dir = "/content/drive/MyDrive/ego4d_data/v2/extracted_frames"
os.makedirs(output_dir, exist_ok=True)
output_frame_path = os.path.join(output_dir, "%07d.jpg")

# Define the frame number to extract (replace with your desired frame number)
frame_number = 0 # <<< EDIT ME: Specify the frame number you want to extract

# Construct the ffmpeg command
# -vf select='eq(n,FRAME_NUMBER)' selects the frame by its index (0-based)
# -vframes 1 extracts only one frame
# -vsync 0 ensures that frames are not duplicated or dropped
ffmpeg_command = [
    "ffmpeg",
    "-i", input_video_path,
    "-vf", f"select='eq(n,{frame_number})'",
    "-vframes", "10",
    "-vsync", "0",
    output_frame_path
]

print(f"Running ffmpeg command: {' '.join(ffmpeg_command)}")

# Execute the ffmpeg command
try:
    subprocess.run(ffmpeg_command, check=True, capture_output=True, text=True)
    print(f"Successfully extracted frame {frame_number} to {output_frame_path}")
except subprocess.CalledProcessError as e:
    print(f"Error extracting frame: {e}")
    print(f"Stderr: {e.stderr}")
except FileNotFoundError:
    print("Error: ffmpeg command not found. Please ensure ffmpeg is installed.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

Running ffmpeg command: ffmpeg -i /content/drive/MyDrive/ego4d_data/v2/full_scale/c0ca834d-5e1b-4150-97b0-7a8170f0094c.mp4 -vf select='eq(n,0)' -vframes 10 -vsync 0 /content/drive/MyDrive/ego4d_data/v2/extracted_frames/%07d.jpg
Successfully extracted frame 0 to /content/drive/MyDrive/ego4d_data/v2/extracted_frames/%07d.jpg

In [ ]:
import os
import multiprocessing
import torch

print("--- System Information ---")

# Number of CPU cores
num_cpu_cores = multiprocessing.cpu_count()
print(f"Number of CPU cores available: {num_cpu_cores}")

# GPU Information (if available)
if torch.cuda.is_available():
    print("\n--- GPU Information ---")
    print(f"CUDA available: {torch.cuda.is_available()}")
    print(f"CUDA device count: {torch.cuda.device_count()}")
    for i in range(torch.cuda.device_count()):
        print(f"  Device {i}: {torch.cuda.get_device_name(i)}")
        print(f"    Capability: {torch.cuda.get_device_capability(i)}")
        print(f"    Total memory: {torch.cuda.get_device_properties(i).total_memory / (1024**3):.2f} GB")
else:
    print("\n--- GPU Information ---")
    print("No GPU available.")

print("\n--- Recommendation for NUM_WORKERS ---")
print(f"A common starting point for NUM_WORKERS is the number of CPU cores ({num_cpu_cores}).")
print("However, the optimal number can depend on the task (CPU-bound vs I/O-bound) and available memory.")
print("You might experiment with values around the number of CPU cores to find the best performance.")

--- System Information ---
Number of CPU cores available: 2

--- GPU Information ---
No GPU available.

--- Recommendation for NUM_WORKERS ---
A common starting point for NUM_WORKERS is the number of CPU cores (2).
However, the optimal number can depend on the task (CPU-bound vs I/O-bound) and available memory.
You might experiment with values around the number of CPU cores to find the best performance.

In [ ]:
import subprocess
import os
import concurrent.futures
import time

# --- Configuration ---
# Define the input video path
input_video_path = "/content/drive/MyDrive/ego4d_data/v2/full_scale/0aec2b0c-18e1-453b-a6ed-e484698d41df.mp4" # <<< EDIT ME: Replace with your video path

# Define the output directory
output_base_dir = "/content/drive/MyDrive/ego4d_data/v2/extracted_multiple_frames_parallel" # <<< EDIT ME: Define your base output directory
os.makedirs(output_base_dir, exist_ok=True)

# *** Placeholder for Video UID (In the main loop, this would be the actual video UID) ***
# Replace with a sample video UID for testing this cell
video_uid = "0aec2b0c-18e1-453b-a6ed-e484698d41df" # <<< EDIT ME for testing this cell

# Define the video-specific output directory
output_video_dir = os.path.join(output_base_dir, video_uid)
os.makedirs(output_video_dir, exist_ok=True)


# Define the list of frame numbers you want to extract
# Replace with your desired frame numbers
desired_frame_indices = list(range(0,30)) # <<< EDIT ME: Specify the frame numbers you want to extract


# Set the number of worker threads for parallel processing
# Adjust based on your system's capabilities and the nature of the task
NUM_WORKERS = 4 # <<< EDIT ME: Number of parallel processes/threads

# --- Frame Extraction Function ---
def extract_single_frame_parallel(video_path, frame_num, out_dir):
    """Extract a single frame using ffmpeg in a separate process/thread."""
    output_frame_path = os.path.join(out_dir, f"{frame_num:07d}.jpg")
    ffmpeg_command = [
        "ffmpeg",
        "-i", video_path,
        "-vf", f"select='eq(n,{frame_num})'",
        "-vframes", "1",
        "-vsync", "0",
        output_frame_path
    ]

    try:
        # print(f"  Running ffmpeg command for frame {frame_num}: {' '.join(ffmpeg_command)}")
        subprocess.run(ffmpeg_command, check=True, capture_output=True, text=True, timeout=60) # Added a timeout for individual frame extraction
        if os.path.exists(output_frame_path):
            # print(f"Successfully extracted frame {frame_num}")
            return True, frame_num, None
        else:
            # print(f"Warning: Frame {frame_num} was not extracted successfully.")
            return False, frame_num, f"Frame {frame_num} not found after extraction."

    except subprocess.TimeoutExpired:
        return False, frame_num, f"Extraction timed out for frame {frame_num}."
    except subprocess.CalledProcessError as e:
        return False, frame_num, f"ffmpeg failed for frame {frame_num}: {e.stderr}"
    except FileNotFoundError:
        return False, frame_num, "Error: ffmpeg command not found."
    except Exception as e:
        return False, frame_num, f"An unexpected error occurred for frame {frame_num}: {e}"


# --- Parallel Frame Extraction ---
print(f"Attempting to extract {len(desired_frame_indices)} frames for video {video_uid} using {NUM_WORKERS} workers...")
extracted_count = 0
failed_frames = []

start_time = time.time()

# Use ThreadPoolExecutor for parallel execution
with concurrent.futures.ThreadPoolExecutor(max_workers=NUM_WORKERS) as executor:
    # Submit extraction tasks for each frame
    future_to_frame = {executor.submit(extract_single_frame_parallel, input_video_path, frame_num, output_video_dir): frame_num for frame_num in desired_frame_indices}

    # Process the results as they complete
    for future in concurrent.futures.as_completed(future_to_frame):
        frame_num = future_to_frame[future]
        try:
            success, frame, error_msg = future.result()
            if success:
                extracted_count += 1
            else:
                print(f"Failed to extract frame {frame}: {error_msg}")
                failed_frames.append(frame)
        except Exception as exc:
            print(f"Frame {frame_num} generated an exception: {exc}")
            failed_frames.append(frame_num)

end_time = time.time()
duration = end_time - start_time

print(f"\nFinished extracting frames for video {video_uid}.")
print(f"Total successfully extracted: {extracted_count} out of {len(desired_frame_indices)}")
if failed_frames:
    print(f"Failed to extract the following frames: {failed_frames}")

print(f"Total extraction time: {duration:.2f} seconds")

Attempting to extract 30 frames for video 0aec2b0c-18e1-453b-a6ed-e484698d41df using 4 workers...
Failed to extract frame 3: ffmpeg failed for frame 3: ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/content/drive/MyDrive/ego4d_data/v2/full_scale/0aec2b0c-18e1-453b-a6ed-e484698d41df.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.20.100
  Duration: 00:48:13.69, start: 0.000000, bitrate: 2427 kb/s
  Stream #0:0(und): Video: vp9 (Profile 1) (vp09 / 0x39307076), yuv444p(tv, progressive), 1440x1080, 2337 kb/s, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 15360 tbn, 15360 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 82 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
File '/content/drive/MyDrive/ego4d_data/v2/extracted_multiple_frames_parallel/0aec2b0c-18e1-453b-a6ed-e484698d41df/0000003.jpg' already exists. Overwrite? [y/N] Not overwriting - exiting

Failed to extract frame 1: ffmpeg failed for frame 1: ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/content/drive/MyDrive/ego4d_data/v2/full_scale/0aec2b0c-18e1-453b-a6ed-e484698d41df.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.20.100
  Duration: 00:48:13.69, start: 0.000000, bitrate: 2427 kb/s
  Stream #0:0(und): Video: vp9 (Profile 1) (vp09 / 0x39307076), yuv444p(tv, progressive), 1440x1080, 2337 kb/s, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 15360 tbn, 15360 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 82 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
File '/content/drive/MyDrive/ego4d_data/v2/extracted_multiple_frames_parallel/0aec2b0c-18e1-453b-a6ed-e484698d41df/0000001.jpg' already exists. Overwrite? [y/N] Not overwriting - exiting

Failed to extract frame 2: ffmpeg failed for frame 2: ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/content/drive/MyDrive/ego4d_data/v2/full_scale/0aec2b0c-18e1-453b-a6ed-e484698d41df.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.20.100
  Duration: 00:48:13.69, start: 0.000000, bitrate: 2427 kb/s
  Stream #0:0(und): Video: vp9 (Profile 1) (vp09 / 0x39307076), yuv444p(tv, progressive), 1440x1080, 2337 kb/s, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 15360 tbn, 15360 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 82 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
File '/content/drive/MyDrive/ego4d_data/v2/extracted_multiple_frames_parallel/0aec2b0c-18e1-453b-a6ed-e484698d41df/0000002.jpg' already exists. Overwrite? [y/N] Not overwriting - exiting

Failed to extract frame 0: ffmpeg failed for frame 0: ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/content/drive/MyDrive/ego4d_data/v2/full_scale/0aec2b0c-18e1-453b-a6ed-e484698d41df.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.20.100
  Duration: 00:48:13.69, start: 0.000000, bitrate: 2427 kb/s
  Stream #0:0(und): Video: vp9 (Profile 1) (vp09 / 0x39307076), yuv444p(tv, progressive), 1440x1080, 2337 kb/s, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 15360 tbn, 15360 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 82 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
File '/content/drive/MyDrive/ego4d_data/v2/extracted_multiple_frames_parallel/0aec2b0c-18e1-453b-a6ed-e484698d41df/0000000.jpg' already exists. Overwrite? [y/N] Not overwriting - exiting

Failed to extract frame 4: ffmpeg failed for frame 4: ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/content/drive/MyDrive/ego4d_data/v2/full_scale/0aec2b0c-18e1-453b-a6ed-e484698d41df.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.20.100
  Duration: 00:48:13.69, start: 0.000000, bitrate: 2427 kb/s
  Stream #0:0(und): Video: vp9 (Profile 1) (vp09 / 0x39307076), yuv444p(tv, progressive), 1440x1080, 2337 kb/s, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 15360 tbn, 15360 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 82 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
File '/content/drive/MyDrive/ego4d_data/v2/extracted_multiple_frames_parallel/0aec2b0c-18e1-453b-a6ed-e484698d41df/0000004.jpg' already exists. Overwrite? [y/N] Not overwriting - exiting

Failed to extract frame 6: ffmpeg failed for frame 6: ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/content/drive/MyDrive/ego4d_data/v2/full_scale/0aec2b0c-18e1-453b-a6ed-e484698d41df.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.20.100
  Duration: 00:48:13.69, start: 0.000000, bitrate: 2427 kb/s
  Stream #0:0(und): Video: vp9 (Profile 1) (vp09 / 0x39307076), yuv444p(tv, progressive), 1440x1080, 2337 kb/s, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 15360 tbn, 15360 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 82 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
File '/content/drive/MyDrive/ego4d_data/v2/extracted_multiple_frames_parallel/0aec2b0c-18e1-453b-a6ed-e484698d41df/0000006.jpg' already exists. Overwrite? [y/N] Not overwriting - exiting

Failed to extract frame 7: ffmpeg failed for frame 7: ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/content/drive/MyDrive/ego4d_data/v2/full_scale/0aec2b0c-18e1-453b-a6ed-e484698d41df.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.20.100
  Duration: 00:48:13.69, start: 0.000000, bitrate: 2427 kb/s
  Stream #0:0(und): Video: vp9 (Profile 1) (vp09 / 0x39307076), yuv444p(tv, progressive), 1440x1080, 2337 kb/s, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 15360 tbn, 15360 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 82 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
File '/content/drive/MyDrive/ego4d_data/v2/extracted_multiple_frames_parallel/0aec2b0c-18e1-453b-a6ed-e484698d41df/0000007.jpg' already exists. Overwrite? [y/N] Not overwriting - exiting

Failed to extract frame 5: ffmpeg failed for frame 5: ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)

# New Era

In [ ]:
# ===========================
# Ego4D STA — single Colab cell
# Build frame lists (+ optional extract, yolo labels, head manifests)
# ===========================
import os, json, collections, subprocess, time, shutil
from dataclasses import dataclass
from typing import List, Dict, Tuple

# ---------- Paths & toggles ----------
EGO4D_ROOT = "/content/drive/MyDrive/ego4d_data"
VERSION = "v2"
ANN_DIR = f"{EGO4D_ROOT}/{VERSION}/annotations"
FRAMES_ROOT = f"{EGO4D_ROOT}/{VERSION}/frames"
VIDEO_DIR = f"{EGO4D_ROOT}/{VERSION}/full_scale"   # for full_scale videos
FRAME_LISTS_DIR = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists"
UID_LIST_FILE = f"{EGO4D_ROOT}/sta_uids.txt"
YOLO_LABELS_DIR = f"{EGO4D_ROOT}/yolo_labels"
LITESTA_DIR = "/content/drive/MyDrive/Ego4d-LiteSTA"
HEAD_TRAIN_JSON = f"{LITESTA_DIR}/head_train.json"
HEAD_VAL_JSON   = f"{LITESTA_DIR}/head_val.json"

# Use your pre-built, filtered file (fast) or read full STA JSONs:
USE_EXTRACTED_JSON = False
EXTRACTED_JSON = "/content/drive/MyDrive/ego4d_data/extracted_sta_data.json"

# Optional steps:
EXTRACT_FRAMES = False         # set True to extract images now
DELETE_VIDEO_AFTER = True      # delete .mp4 after successful extraction
DEMO_MODE = True               # limit to a few videos
NUM_DEMO_VIDS = 1

GENERATE_YOLO_LABELS = False   # create YOLO .txt (requires frames present)
DETECTOR_CLASS_POLICY = "noun" # "noun" or "single"

GENERATE_HEAD_MANIFESTS = False # write head_train.json / head_val.json

FFMPEG_TIMEOUT = 1800
DOWNLOAD_TIMEOUT = 3600

# ---------- Helpers ----------
def which_or_msg(cmd):
    path = shutil.which(cmd)
    if not path:
        print(f"  ERROR: '{cmd}' not found on PATH.")
        return False
    return True

@dataclass
class StaItem:
    video_uid: str
    frame: int
    box: List[float]
    verb_id: int
    noun_id: int
    ttc: float
    split: str  # "train" or "val"

def load_sta_from_full() -> List[StaItem]:
    def load_one(path:str, split:str):
        data = json.load(open(path,"r"))
        out = []
        for ann in data.get("annotations", []):
            vid = ann["video_uid"]
            fidx = int(ann["frame"])
            for obj in ann.get("objects", []):
                out.append(StaItem(
                    video_uid=vid, frame=fidx, box=obj["box"],
                    verb_id=int(obj["verb_category_id"]),
                    noun_id=int(obj["noun_category_id"]),
                    ttc=float(obj.get("time_to_contact", 0.0)),
                    split=split
                ))
        return out
    train = load_one(os.path.join(ANN_DIR, "fho_sta_train.json"), "train")
    val   = load_one(os.path.join(ANN_DIR, "fho_sta_val.json"), "val")
    return train + val

def load_sta_from_extracted() -> List[StaItem]:
    data = json.load(open(EXTRACTED_JSON, "r"))
    items = []
    # If 'split' is missing in your extracted file, default to "train"
    for it in data:
        items.append(StaItem(
            video_uid=it["video_uid"],
            frame=int(it["frame"]),
            box=it["box"],
            verb_id=int(it["verb_category_id"]),
            noun_id=int(it["noun_category_id"]),
            ttc=float(it.get("time_to_contact", 0.0)),
            split=it.get("split","train")
        ))
    return items

def choose_min_ttc(items: List[StaItem]) -> StaItem:
    return min(items, key=lambda x: x.ttc)

def class_id_for_detector(item: StaItem) -> int:
    return 0 if DETECTOR_CLASS_POLICY == "single" else item.noun_id

def download_one_video(uid: str):
    cmd = [
        "ego4d",
        "--output_directory", f"{EGO4D_ROOT}/{VERSION}/Full_vids",
        "--datasets", "full_scale",
        "--version", VERSION,
        "--video_uids", uid,
        "-y",
    ]
    print("    > ", " ".join(cmd))
    subprocess.run(cmd, text=True, capture_output=True, check=True, timeout=DOWNLOAD_TIMEOUT)

def extract_frames_eqn(video_path: str, frames: List[int], out_dir: str, chunk_size=800):
    os.makedirs(out_dir, exist_ok=True)
    frames = sorted(set(int(x) for x in frames))
    if not frames:
        return 0
    start_number = len([f for f in os.listdir(out_dir) if f.lower().endswith(".jpg")])
    total_before = len([f for f in os.listdir(out_dir) if f.lower().endswith(".jpg")])

    for i in range(0, len(frames), chunk_size):
        chunk = frames[i:i+chunk_size]
        expr = "+".join([f"eq(n\\,{n})" for n in chunk])
        vf = f"select='{expr}',setpts=N/FRAME_RATE/TB"
        cmd = [
            "ffmpeg","-y","-i", video_path,
            "-vf", vf,
            "-vsync","0",
            "-start_number", str(start_number),
            os.path.join(out_dir, "%07d.jpg"),
        ]
        print(f"    > ffmpeg chunk {i//chunk_size+1} ({len(chunk)} frames)")
        subprocess.run(cmd, text=True, capture_output=True, check=True, timeout=FFMPEG_TIMEOUT)
        start_number += len(chunk)

    total_after = len([f for f in os.listdir(out_dir) if f.lower().endswith(".jpg")])
    return total_after - total_before

# ---------- Main ----------
os.makedirs(FRAME_LISTS_DIR, exist_ok=True)
os.makedirs(YOLO_LABELS_DIR, exist_ok=True)
os.makedirs(LITESTA_DIR, exist_ok=True)
os.makedirs(VIDEO_DIR, exist_ok=True)
os.makedirs(FRAMES_ROOT, exist_ok=True)

# Preflight (only if using optional steps)
if EXTRACT_FRAMES and not which_or_msg("ffmpeg"):
    raise SystemExit("Install ffmpeg first.")
if EXTRACT_FRAMES and not which_or_msg("ego4d"):
    raise SystemExit("Install ego4d CLI first.")

# Load STA items
if USE_EXTRACTED_JSON:
    print("Loading items from extracted_sta_data.json ...")
    sta_items = load_sta_from_extracted()
else:
    print("Loading items from full STA JSONs ...")
    sta_items = load_sta_from_full()

print(f"Loaded {len(sta_items)} STA objects")

# Group by image (video_uid, frame)
per_img = collections.defaultdict(list)
for it in sta_items:
    per_img[(it.video_uid, it.frame)].append(it)

# Choose one object (min TTC) per image
chosen_by_img = {k: choose_min_ttc(v) for k,v in per_img.items()}

# Write per-video frame lists + sta_uids.txt
frames_by_vid = collections.defaultdict(set)
for (vid, fidx) in chosen_by_img.keys():
    frames_by_vid[vid].add(fidx)

for vid, frames in frames_by_vid.items():
    with open(os.path.join(FRAME_LISTS_DIR, f"{vid}_frames.txt"), "w") as g:
        for k in sorted(frames):
            g.write(f"{k}\n")

with open(UID_LIST_FILE, "w") as f:
    f.write("\n".join(sorted(frames_by_vid.keys())))

print(f"Per-video frame lists → {FRAME_LISTS_DIR}  | videos: {len(frames_by_vid)}")
print(f"UID list              → {UID_LIST_FILE}")

# Optional: extract frames now (demo-limited)
if EXTRACT_FRAMES:
    vids = sorted(frames_by_vid.keys())
    if DEMO_MODE and len(vids) > NUM_DEMO_VIDS:
        import random
        vids = random.sample(vids, NUM_DEMO_VIDS)
        print(f"DEMO: limiting to {len(vids)} videos")

    for i, vid in enumerate(vids, 1):
        print(f"\n[{i}/{len(vids)}] {vid}")
        vpath = os.path.join(VIDEO_DIR, f"{vid}.mp4")
        if not os.path.exists(vpath):
            print("  downloading video ...")
            try:
                download_one_video(vid)
            except subprocess.CalledProcessError as e:
                print("  download failed:", e.stderr[-500:])
                continue
            except subprocess.TimeoutExpired:
                print("  download timed out.")
                continue

        out_dir = os.path.join(FRAMES_ROOT, vid)
        flist = os.path.join(FRAME_LISTS_DIR, f"{vid}_frames.txt")
        with open(flist,"r") as fh:
            needed = [int(x.strip()) for x in fh if x.strip()]
        print(f"  extracting {len(needed)} frames ...")
        try:
            n = extract_frames_eqn(vpath, needed, out_dir)
            print(f"  extracted {n} frames → {out_dir}")
        except subprocess.CalledProcessError as e:
            print("  ffmpeg failed:", e.stderr[-500:])
            continue
        except subprocess.TimeoutExpired:
            print("  ffmpeg timed out")
            continue

        if DELETE_VIDEO_AFTER and os.path.exists(vpath):
            try:
                os.remove(vpath)
                print("  deleted video to save space")
            except Exception as e:
                print("  could not delete video:", e)

# Optional: YOLO labels (requires frames to exist)
if GENERATE_YOLO_LABELS:
    try:
        from PIL import Image
    except Exception as e:
        raise SystemExit("Pillow not installed. Run: pip install pillow")

    yolo_written = 0
    for (vid, fidx), chosen in chosen_by_img.items():
        img_path = os.path.join(FRAMES_ROOT, vid, f"{fidx:07d}.jpg")
        if not os.path.exists(img_path):
            continue
        W, H = Image.open(img_path).size
        x1,y1,x2,y2 = map(float, chosen.box)
        w = max(1.0, x2-x1); h = max(1.0, y2-y1)
        cx = x1 + w/2.0; cy = y1 + h/2.0
        cls_id = 0 if DETECTOR_CLASS_POLICY=="single" else chosen.noun_id
        line = f"{cls_id} {cx/W:.6f} {cy/H:.6f} {w/W:.6f} {h/H:.6f}\n"
        out_dir = os.path.join(YOLO_LABELS_DIR, vid)
        os.makedirs(out_dir, exist_ok=True)
        with open(os.path.join(out_dir, f"{fidx:07d}.txt"), "w") as g:
            g.write(line)
        yolo_written += 1
    print(f"YOLO labels written: {yolo_written} → {YOLO_LABELS_DIR}")

# Optional: head manifests
if GENERATE_HEAD_MANIFESTS:
    os.makedirs(LITESTA_DIR, exist_ok=True)
    head_train, head_val = [], []
    for (vid, fidx), chosen in chosen_by_img.items():
        entry = {
            "image": os.path.join(FRAMES_ROOT, vid, f"{fidx:07d}.jpg"),
            "gt_box": chosen.box,
            "verb_id": chosen.verb_id,
            "noun_id": chosen.noun_id,
            "ttc": chosen.ttc,
        }
        if chosen.split == "val":
            entry["candidates"] = []  # fill later after detector inference
            head_val.append(entry)
        else:
            head_train.append(entry)
    json.dump(head_train, open(HEAD_TRAIN_JSON,"w"))
    json.dump(head_val, open(HEAD_VAL_JSON,"w"))
    print(f"head_train.json → {HEAD_TRAIN_JSON}  ({len(head_train)})")
    print(f"head_val.json   → {HEAD_VAL_JSON}    ({len(head_val)})")

print("\nDone.")

Loading items from full STA JSONs ...
Loaded 152075 STA objects
Per-video frame lists → /content/drive/MyDrive/ego4d_data/v2/tmp_frame_lists  | videos: 1311
UID list              → /content/drive/MyDrive/ego4d_data/sta_uids.txt

Done.

In [ ]:
# Replace '.' with the path to the directory you want to list
!ls /content/drive/MyDrive/ego4d_data/v2/annotations_540ss

av_train_height-540.json       fho_sta_val_height-540.json
av_val_height-540.json	       vq_train_height-540.json
fho_sta_train_height-540.json  vq_val_height-540.json

# Old artifacts

In [ ]:
# ===========================
# Ego4D STA (no extraction) — build frame lists, YOLO labels (optional), head manifests (optional)
# Works with 540-scaled STA JSONs you produced:
#   - fho_sta_train_height-540.json
#   - fho_sta_val_height-540.json
# ===========================
import os, json, collections
from dataclasses import dataclass
from typing import List, Dict, Tuple, Optional

# -------- Paths & toggles --------
EGO4D_ROOT = "/content/drive/MyDrive/ego4d_data"
VERSION    = "v2"

# Input annotations (choose one of the two blocks)
USE_HEIGHT_540 = True   # <-- set True to use *_height-540.json you generated

ANN_DIR_FULL   = f"{EGO4D_ROOT}/{VERSION}/annotations"
ANN_540_DIR    = f"{EGO4D_ROOT}/{VERSION}/annotations_540ss"  # set to the folder where your *_height-540.json live

# Expected filenames
FHO_TRAIN_NAME_540 = "fho_sta_train_height-540.json"
FHO_VAL_NAME_540   = "fho_sta_val_height-540.json"
FHO_TRAIN_NAME_FULL= "fho_sta_train.json"
FHO_VAL_NAME_FULL  = "fho_sta_val.json"

# Outputs
FRAME_LISTS_DIR   = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists"    # per-video frame indices
UID_LIST_FILE     = f"{EGO4D_ROOT}/sta_uids.txt"                 # master list of UIDs
FRAMES_ROOT       = f"{EGO4D_ROOT}/{VERSION}/frames"             # not used here, but referenced in manifests
YOLO_LABELS_DIR   = f"{EGO4D_ROOT}/yolo_labels_540"              # YOLO .txt will be written here if enabled
LITESTA_DIR       = "/content/drive/MyDrive/Ego4d-LiteSTA"
HEAD_TRAIN_JSON   = f"{LITESTA_DIR}/head_train.json"
HEAD_VAL_JSON     = f"{LITESTA_DIR}/head_val.json"

# Optional artifacts
GENERATE_YOLO_LABELS    = False     # normalized TXT labels; needs frame width/height info in JSON
DETECTOR_CLASS_POLICY   = "noun"    # "noun" or "single" (single -> class 0)
GENERATE_HEAD_MANIFESTS = True      # produces head_train.json and head_val.json

# -------- Data model --------
@dataclass
class StaItem:
    video_uid: str
    frame: int
    box: List[float]              # [x1,y1,x2,y2] in pixels (540 space if USE_HEIGHT_540=True)
    verb_id: int
    noun_id: int
    ttc: float
    split: str                    # "train" | "val"
    width: Optional[int] = None   # image width if available
    height: Optional[int] = None  # image height if available

# -------- Parsers (robust to minor format differences) --------
def _iter_sta_records(obj) -> List[dict]:
    """Return an iterator over annotation records regardless of top-level shape."""
    if isinstance(obj, dict) and "annotations" in obj:
        return obj["annotations"]
    if isinstance(obj, list):
        return obj
    # some formats: {"data":[...]}
    if isinstance(obj, dict) and "data" in obj and isinstance(obj["data"], list):
        return obj["data"]
    return []

def _extract_dims(rec: dict) -> Tuple[Optional[int], Optional[int]]:
    # Try common keys for per-record dims (height-540 transforms may store them)
    for k_w, k_h in [("width","height"), ("frame_width","frame_height"), ("img_w","img_h")]:
        if k_w in rec and k_h in rec:
            try: return int(rec[k_w]), int(rec[k_h])
            except: pass
    return None, None

def _extract_items_one_file(path: str, split: str, height_540: bool) -> List[StaItem]:
    if not os.path.exists(path):
        raise FileNotFoundError(f"Annotation file not found: {path}")
    data = json.load(open(path, "r"))
    items: List[StaItem] = []

    for rec in _iter_sta_records(data):
        # core fields
        vid  = rec.get("video_uid") or rec.get("video_id") or rec.get("uid") or ""
        if not vid:
            # sometimes nested
            vid = rec.get("clip_video_uid") or rec.get("video", "")
        # frame index
        fidx = rec.get("frame")
        if fidx is None:
            # sometimes "video_frame" or "frame_index"
            fidx = rec.get("video_frame", rec.get("frame_index", None))
        if fidx is None:
            continue
        try:
            fidx = int(fidx)
        except:
            continue

        # per-record dims if provided (particularly in your height-540 conversion)
        w, h = _extract_dims(rec)

        # objects
        objs = rec.get("objects", [])
        for obj in objs:
            box = obj.get("box") or obj.get("bbox") or obj.get("gt_box")
            if not box or len(box) != 4:
                continue
            try:
                x1, y1, x2, y2 = map(float, box)
            except:
                continue

            verb_id = obj.get("verb_category_id", obj.get("verb_id", 0))
            noun_id = obj.get("noun_category_id", obj.get("noun_id", 0))
            ttc     = obj.get("time_to_contact", obj.get("ttc", 0.0))

            try: verb_id = int(verb_id)
            except: verb_id = 0
            try: noun_id = int(noun_id)
            except: noun_id = 0
            try: ttc = float(ttc)
            except: ttc = 0.0

            items.append(
                StaItem(
                    video_uid=vid, frame=fidx, box=[x1,y1,x2,y2],
                    verb_id=verb_id, noun_id=noun_id, ttc=ttc, split=split,
                    width=w, height=h
                )
            )
    return items

def load_sta_items(use_540: bool) -> List[StaItem]:
    if use_540:
        train_path = os.path.join(ANN_540_DIR, FHO_TRAIN_NAME_540)
        val_path   = os.path.join(ANN_540_DIR, FHO_VAL_NAME_540)
    else:
        train_path = os.path.join(ANN_DIR_FULL, FHO_TRAIN_NAME_FULL)
        val_path   = os.path.join(ANN_DIR_FULL, FHO_VAL_NAME_FULL)

    train = _extract_items_one_file(train_path, "train", use_540)
    val   = _extract_items_one_file(val_path,   "val",   use_540)
    return train + val

# -------- Selection + writers --------
def choose_min_ttc(items: List[StaItem]) -> StaItem:
    return min(items, key=lambda x: x.ttc)

def class_id_for_detector(item: StaItem) -> int:
    return 0 if DETECTOR_CLASS_POLICY == "single" else item.noun_id

os.makedirs(FRAME_LISTS_DIR, exist_ok=True)
os.makedirs(YOLO_LABELS_DIR, exist_ok=True)
os.makedirs(LITESTA_DIR, exist_ok=True)

# 1) Load items
print(f"Reading {'540-scaled' if USE_HEIGHT_540 else 'full-resolution'} STA JSONs ...")
items = load_sta_items(USE_HEIGHT_540)
print(f"Loaded STA objects: {len(items)}")

# 2) One object per (video_uid, frame) by min-TTC
per_img = collections.defaultdict(list)
for it in items:
    per_img[(it.video_uid, it.frame)].append(it)
chosen_by_img: Dict[Tuple[str,int], StaItem] = {k: choose_min_ttc(v) for k, v in per_img.items()}

# 3) Write per-video frame lists + uid list
frames_by_vid = collections.defaultdict(set)
for (vid, fidx) in chosen_by_img.keys():
    frames_by_vid[vid].add(fidx)

for vid, frames in frames_by_vid.items():
    outp = os.path.join(FRAME_LISTS_DIR, f"{vid}_frames.txt")
    with open(outp, "w") as g:
        for k in sorted(frames):
            g.write(f"{k}\n")

with open(UID_LIST_FILE, "w") as f:
    f.write("\n".join(sorted(frames_by_vid.keys())))

print(f"Per-video frame lists → {FRAME_LISTS_DIR}  | videos: {len(frames_by_vid)}")
print(f"UID list              → {UID_LIST_FILE}")

# 4) Optional YOLO labels (normalized). No images required: we only need width/height.
if GENERATE_YOLO_LABELS:
    written = 0
    missing_wh = 0
    for (vid, fidx), it in chosen_by_img.items():
        # Must have width & height in the record to normalize
        W, H = it.width, it.height
        if not (W and H) or W <= 0 or H <= 0:
            missing_wh += 1
            continue

        x1, y1, x2, y2 = map(float, it.box)
        w = max(1.0, x2 - x1)
        h = max(1.0, y2 - y1)
        cx = x1 + w/2.0
        cy = y1 + h/2.0

        cls_id = class_id_for_detector(it)
        line = f"{cls_id} {cx/W:.6f} {cy/H:.6f} {w/W:.6f} {h/H:.6f}\n"

        out_dir = os.path.join(YOLO_LABELS_DIR, vid)
        os.makedirs(out_dir, exist_ok=True)
        with open(os.path.join(out_dir, f"{fidx:07d}.txt"), "w") as g:
            g.write(line)
        written += 1

    print(f"YOLO labels written: {written} → {YOLO_LABELS_DIR}  (skipped {missing_wh} samples missing width/height)")

# 5) Optional head manifests (resolution-agnostic)
if GENERATE_HEAD_MANIFESTS:
    head_train, head_val = [], []
    for (vid, fidx), it in chosen_by_img.items():
        entry = {
            # The image path is where YOU will put images later (540 or full).
            # Keeping it under FRAMES_ROOT keeps downstream code stable.
            "image": os.path.join(FRAMES_ROOT, vid, f"{fidx:07d}.jpg"),
            "gt_box": it.box,          # already in 540 pixels if USE_HEIGHT_540=True
            "verb_id": it.verb_id,
            "noun_id": it.noun_id,
            "ttc": it.ttc,
        }
        if it.split == "val":
            entry["candidates"] = []   # to be filled after detector inference
            head_val.append(entry)
        else:
            head_train.append(entry)

    os.makedirs(LITESTA_DIR, exist_ok=True)
    json.dump(head_train, open(HEAD_TRAIN_JSON, "w"))
    json.dump(head_val,   open(HEAD_VAL_JSON,   "w"))
    print(f"head_train.json → {HEAD_TRAIN_JSON}  ({len(head_train)})")
    print(f"head_val.json   → {HEAD_VAL_JSON}    ({len(head_val)})")

print("\nDone (no video downloads, no frame extraction).")

Reading 540-scaled STA JSONs ...
Loaded STA objects: 152075
Per-video frame lists → /content/drive/MyDrive/ego4d_data/v2/tmp_frame_lists  | videos: 1311
UID list              → /content/drive/MyDrive/ego4d_data/sta_uids.txt
head_train.json → /content/drive/MyDrive/Ego4d-LiteSTA/head_train.json  (98276)
head_val.json   → /content/drive/MyDrive/Ego4d-LiteSTA/head_val.json    (47395)

Done (no video downloads, no frame extraction).

# New artifacts

In [ ]:
# ==========================================
# Ego4D STA — ONE-CELL BUILDER (videos + clips)
# Inputs (pick 540 or full):
#   - 540:  v2/annotations_540ss/fho_sta_train_height-540.json
#            v2/annotations_540ss/fho_sta_val_height-540.json
#   - full: v2/annotations/fho_sta_train.json
#            v2/annotations/fho_sta_val.json
#
# Outputs (all under ego4d_data):
#   /ego4d_data/sta_uids.txt                 (video_uids)
#   /ego4d_data/sta_clip_uids.txt            (clip_uids)
#   /ego4d_data/v2/tmp_frame_lists/videos/<video_uid>_frames.txt      (video frame space)
#   /ego4d_data/v2/tmp_frame_lists/clips/<clip_uid>_clip_frames.txt   (clip frame space, 30 FPS)
#   /ego4d_data/v2/yolo_labels_540/videos/<video_uid>/<frame>.txt     (optional)
#   /ego4d_data/v2/manifests/head_{train,val}_video.json              (optional)
#   /ego4d_data/v2/manifests/head_{train,val}_clip.json               (optional)
# ==========================================
import os, json, collections
from dataclasses import dataclass
from typing import List, Dict, Tuple, Optional

# ---------------- USER TOGGLES ----------------
EGO4D_ROOT = "/content/drive/MyDrive/ego4d_data"
VERSION    = "v2"

# Use 540-scaled JSONs you produced (True) OR original full-res JSONs (False)
USE_HEIGHT_540 = True

# Build lists (recommended True): video lists, clip lists, and UID files
BUILD_VIDEO_LISTS = True
BUILD_CLIP_LISTS  = True

# Optional artifacts
GENERATE_YOLO_LABELS    = False   # normalized YOLO txt (requires width/height per record)
DETECTOR_CLASS_POLICY   = "noun"  # "noun" or "single" (single -> class 0)
GENERATE_HEAD_MANIFESTS = True    # head manifests for videos + clips
SELECT_MIN_TTC_FOR_HEAD = True    # for head manifests: pick one object per (id,frame) by min-TTC

# ---------------- PATHS ----------------
ANN_DIR_FULL = f"{EGO4D_ROOT}/{VERSION}/annotations"
ANN_540_DIR  = f"{EGO4D_ROOT}/{VERSION}/annotations_540ss"

# Expected file names
FHO_TRAIN_NAME_540  = "fho_sta_train_height-540.json"
FHO_VAL_NAME_540    = "fho_sta_val_height-540.json"
FHO_TRAIN_NAME_FULL = "fho_sta_train.json"
FHO_VAL_NAME_FULL   = "fho_sta_val.json"

# Where we write lists/labels/manifests
TMP_BASE         = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists"
VIDEO_LIST_DIR   = os.path.join(TMP_BASE, "videos")
CLIP_LIST_DIR    = os.path.join(TMP_BASE, "clips")

UID_VID_FILE     = os.path.join(EGO4D_ROOT, "sta_uids.txt")
UID_CLIP_FILE    = os.path.join(EGO4D_ROOT, "sta_clip_uids.txt")

YOLO_BASE_DIR    = f"{EGO4D_ROOT}/{VERSION}/yolo_labels_540"   # ok for both 540/full (labels are normalized)
YOLO_VID_DIR     = os.path.join(YOLO_BASE_DIR, "videos")
YOLO_CLIP_DIR    = os.path.join(YOLO_BASE_DIR, "clips")        # rarely used; included for completeness

MANIFEST_DIR     = f"{EGO4D_ROOT}/{VERSION}/manifests"
HEAD_TRAIN_VIDEO = os.path.join(MANIFEST_DIR, "head_train_video.json")
HEAD_VAL_VIDEO   = os.path.join(MANIFEST_DIR, "head_val_video.json")
HEAD_TRAIN_CLIP  = os.path.join(MANIFEST_DIR, "head_train_clip.json")
HEAD_VAL_CLIP    = os.path.join(MANIFEST_DIR, "head_val_clip.json")

# Where your extracted images will eventually live (not created here)
FRAMES_VIDEO_ROOT = f"{EGO4D_ROOT}/{VERSION}/frames_videos"
FRAMES_CLIP_ROOT  = f"{EGO4D_ROOT}/{VERSION}/frames_clips"

for d in [VIDEO_LIST_DIR, CLIP_LIST_DIR, YOLO_VID_DIR, YOLO_CLIP_DIR, MANIFEST_DIR]:
    os.makedirs(d, exist_ok=True)

# ---------------- DATA MODEL ----------------
@dataclass
class StaRec:
    video_uid: Optional[str]
    clip_uid: Optional[str]
    video_frame: Optional[int]   # "frame" (global video frame index)
    clip_frame: Optional[int]    # "clip_frame" (0-based within canonical clip @ 30FPS)
    box: Optional[List[float]]   # [x1,y1,x2,y2] (in current JSON pixel space)
    verb_id: Optional[int]
    noun_id: Optional[int]
    ttc: Optional[float]
    split: str                   # "train" | "val"
    width: Optional[int] = None
    height: Optional[int] = None

def _iter_list(obj):
    if isinstance(obj, dict):
        if "annotations" in obj and isinstance(obj["annotations"], list):
            return obj["annotations"]
        if "data" in obj and isinstance(obj["data"], list):
            return obj["data"]
    if isinstance(obj, list):
        return obj
    return []

def _get_dims(rec: dict) -> Tuple[Optional[int], Optional[int]]:
    # Try several common keys
    for (kw, kh) in [("width","height"), ("frame_width","frame_height"), ("img_w","img_h")]:
        if kw in rec and kh in rec:
            try:
                return int(rec[kw]), int(rec[kh])
            except:
                pass
    return None, None

def _as_int(x):
    try: return int(x)
    except: return None

def _as_float(x):
    try: return float(x)
    except: return None

def _load_one_file(path: str, split: str) -> List[StaRec]:
    if not os.path.exists(path):
        raise FileNotFoundError(f"Missing annotation file: {path}")
    raw = json.load(open(path, "r"))
    out : List[StaRec] = []
    for rec in _iter_list(raw):
        vuid = rec.get("video_uid")
        cuid = rec.get("clip_uid")
        vfr  = _as_int(rec.get("frame"))
        cfr  = _as_int(rec.get("clip_frame"))
        w, h = _get_dims(rec)

        objs = rec.get("objects", [])
        for obj in objs:
            box = obj.get("box") or obj.get("bbox") or obj.get("gt_box")
            if not (isinstance(box, (list, tuple)) and len(box) == 4):
                continue
            try:
                x1,y1,x2,y2 = map(float, box)
            except:
                continue

            verb = _as_int(obj.get("verb_category_id", obj.get("verb_id", 0)))
            noun = _as_int(obj.get("noun_category_id", obj.get("noun_id", 0)))
            ttc  = _as_float(obj.get("time_to_contact", obj.get("ttc", 0.0)))

            out.append(StaRec(
                video_uid=vuid, clip_uid=cuid,
                video_frame=vfr, clip_frame=cfr,
                box=[x1,y1,x2,y2],
                verb_id=verb, noun_id=noun,
                ttc=ttc, split=split, width=w, height=h
            ))
    return out

def load_all_records(use_540: bool) -> List[StaRec]:
    if use_540:
        train = _load_one_file(os.path.join(ANN_540_DIR, FHO_TRAIN_NAME_540), "train")
        val   = _load_one_file(os.path.join(ANN_540_DIR, FHO_VAL_NAME_540),   "val")
    else:
        train = _load_one_file(os.path.join(ANN_DIR_FULL, FHO_TRAIN_NAME_FULL), "train")
        val   = _load_one_file(os.path.join(ANN_DIR_FULL, FHO_VAL_NAME_FULL),   "val")
    return train + val

def _choose_min_ttc(objs: List[StaRec]) -> StaRec:
    return min(objs, key=lambda r: (1e9 if r.ttc is None else r.ttc))

def _class_id_for_detector(noun_id: Optional[int]) -> int:
    if DETECTOR_CLASS_POLICY == "single":
        return 0
    return 0 if noun_id is None else int(noun_id)

# ---------------- MAIN ----------------
print(f"Reading {'540-scaled' if USE_HEIGHT_540 else 'full-resolution'} STA JSONs ...")
recs = load_all_records(USE_HEIGHT_540)
print(f"Loaded {len(recs)} object records.")

# --------- Build FRAME LISTS + UID FILES ---------
if BUILD_VIDEO_LISTS:
    by_video = collections.defaultdict(set)   # video_uid -> set(video_frame)
    for r in recs:
        if r.video_uid is not None and r.video_frame is not None:
            by_video[str(r.video_uid)].add(int(r.video_frame))

    for vuid, frames in by_video.items():
        outp = os.path.join(VIDEO_LIST_DIR, f"{vuid}_frames.txt")
        with open(outp, "w") as f:
            for k in sorted(frames):
                f.write(f"{k}\n")

    with open(UID_VID_FILE, "w") as f:
        f.write("\n".join(sorted(by_video.keys())))

    print(f"[VIDEO] {len(by_video)} videos → lists at {VIDEO_LIST_DIR}")
    print(f"[VIDEO] UID file → {UID_VID_FILE}")

if BUILD_CLIP_LISTS:
    by_clip = collections.defaultdict(set)    # clip_uid -> set(clip_frame)
    for r in recs:
        if r.clip_uid is not None and r.clip_frame is not None:
            by_clip[str(r.clip_uid)].add(int(r.clip_frame))

    for cuid, frames in by_clip.items():
        outp = os.path.join(CLIP_LIST_DIR, f"{cuid}_clip_frames.txt")
        with open(outp, "w") as f:
            for k in sorted(frames):
                f.write(f"{k}\n")

    with open(UID_CLIP_FILE, "w") as f:
        f.write("\n".join(sorted(by_clip.keys())))

    print(f"[CLIP]  {len(by_clip)} clips → lists at {CLIP_LIST_DIR}")
    print(f"[CLIP]  UID file → {UID_CLIP_FILE}")

# --------- Optional: YOLO LABELS (normalized) ----------
# Only needs width/height from JSON record; if missing, sample is skipped.
if GENERATE_YOLO_LABELS:
    written_vid, skipped_vid = 0, 0
    written_clip, skipped_clip = 0, 0

    # For videos (per (video_uid, video_frame) we can emit one label line per object)
    per_img = collections.defaultdict(list)  # key: ("video", vuid, vframe)
    for r in recs:
        if r.video_uid is not None and r.video_frame is not None:
            per_img[("video", r.video_uid, r.video_frame)].append(r)

    for (tag, vuid, vframe), rs in per_img.items():
        # Need dims per record; if not present on any, skip
        W = next((x.width for x in rs if x.width), None)
        H = next((x.height for x in rs if x.height), None)
        if not (W and H and W > 0 and H > 0):
            skipped_vid += 1
            continue

        out_dir = os.path.join(YOLO_VID_DIR, str(vuid))
        os.makedirs(out_dir, exist_ok=True)
        out_path = os.path.join(out_dir, f"{int(vframe):07d}.txt")
        with open(out_path, "w") as g:
            for r in rs:
                x1, y1, x2, y2 = r.box
                w = max(1.0, x2 - x1); h = max(1.0, y2 - y1)
                cx = x1 + w/2.0; cy = y1 + h/2.0
                cls_id = _class_id_for_detector(r.noun_id)
                g.write(f"{cls_id} {cx/W:.6f} {cy/H:.6f} {w/W:.6f} {h/H:.6f}\n")
        written_vid += 1

    # For clips (rarely used for detection; included for completeness)
    per_clip_img = collections.defaultdict(list)  # key: ("clip", cuid, cframe)
    for r in recs:
        if r.clip_uid is not None and r.clip_frame is not None:
            per_clip_img[("clip", r.clip_uid, r.clip_frame)].append(r)

    for (tag, cuid, cframe), rs in per_clip_img.items():
        W = next((x.width for x in rs if x.width), None)
        H = next((x.height for x in rs if x.height), None)
        if not (W and H and W > 0 and H > 0):
            skipped_clip += 1
            continue

        out_dir = os.path.join(YOLO_CLIP_DIR, str(cuid))
        os.makedirs(out_dir, exist_ok=True)
        out_path = os.path.join(out_dir, f"{int(cframe):07d}.txt")
        with open(out_path, "w") as g:
            for r in rs:
                x1, y1, x2, y2 = r.box
                w = max(1.0, x2 - x1); h = max(1.0, y2 - y1)
                cx = x1 + w/2.0; cy = y1 + h/2.0
                cls_id = _class_id_for_detector(r.noun_id)
                g.write(f"{cls_id} {cx/W:.6f} {cy/H:.6f} {w/W:.6f} {h/H:.6f}\n")
        written_clip += 1

    print(f"[YOLO] videos: written {written_vid}, skipped {skipped_vid} (missing width/height)")
    print(f"[YOLO] clips : written {written_clip}, skipped {skipped_clip} (missing width/height)")

# --------- Optional: HEAD MANIFESTS (videos + clips) ----------
# For each (id, frame) we pick ONE object with min-TTC (if SELECT_MIN_TTC_FOR_HEAD=True),
# otherwise we keep all objects for that image as separate entries.
if GENERATE_HEAD_MANIFESTS:
    head_train_video, head_val_video = [], []
    head_train_clip,  head_val_clip  = [], []

    # group by (video_uid, video_frame) and (clip_uid, clip_frame)
    g_video = collections.defaultdict(list)
    g_clip  = collections.defaultdict(list)
    for r in recs:
        if r.video_uid and r.video_frame is not None:
            g_video[(r.video_uid, r.video_frame, r.split)].append(r)
        if r.clip_uid and r.clip_frame is not None:
            g_clip[(r.clip_uid, r.clip_frame, r.split)].append(r)

    def _emit_entries(rs: List[StaRec], space: str):
        # Return list of entries for head; either min-TTC single or all
        out = []
        entries = [(_choose_min_ttc(rs),)] if SELECT_MIN_TTC_FOR_HEAD else [(x,) for x in rs]
        for (r,) in entries:
            if space == "video":
                img_path = os.path.join(FRAMES_VIDEO_ROOT, str(r.video_uid), f"{int(r.video_frame):07d}.jpg")
            else:
                img_path = os.path.join(FRAMES_CLIP_ROOT, str(r.clip_uid), f"{int(r.clip_frame):07d}.jpg")
            out.append({
                "image": img_path,
                "gt_box": r.box,
                "verb_id": r.verb_id if r.verb_id is not None else 0,
                "noun_id": r.noun_id if r.noun_id is not None else 0,
                "ttc":    r.ttc if r.ttc is not None else 0.0,
            })
        return out

    # videos
    for (vuid, vframe, split), rs in g_video.items():
        items = _emit_entries(rs, space="video")
        if (split or "").lower() == "val":
            head_val_video.extend(items)
        else:
            head_train_video.extend(items)

    # clips
    for (cuid, cframe, split), rs in g_clip.items():
        items = _emit_entries(rs, space="clip")
        if (split or "").lower() == "val":
            head_val_clip.extend(items)
        else:
            head_train_clip.extend(items)

    # dump
    os.makedirs(MANIFEST_DIR, exist_ok=True)
    json.dump(head_train_video, open(HEAD_TRAIN_VIDEO,"w"))
    json.dump(head_val_video,   open(HEAD_VAL_VIDEO,  "w"))
    json.dump(head_train_clip,  open(HEAD_TRAIN_CLIP, "w"))
    json.dump(head_val_clip,    open(HEAD_VAL_CLIP,   "w"))

    print(f"[HEAD] video: train={len(head_train_video)} → {HEAD_TRAIN_VIDEO}")
    print(f"[HEAD] video:   val={len(head_val_video)}   → {HEAD_VAL_VIDEO}")
    print(f"[HEAD] clip : train={len(head_train_clip)}  → {HEAD_TRAIN_CLIP}")
    print(f"[HEAD] clip :   val={len(head_val_clip)}    → {HEAD_VAL_CLIP}")

print("\nDone.")

Reading 540-scaled STA JSONs ...
Loaded 152075 object records.
[VIDEO] 1311 videos → lists at /content/drive/MyDrive/ego4d_data/v2/tmp_frame_lists/videos
[VIDEO] UID file → /content/drive/MyDrive/ego4d_data/sta_uids.txt
[CLIP]  2324 clips → lists at /content/drive/MyDrive/ego4d_data/v2/tmp_frame_lists/clips
[CLIP]  UID file → /content/drive/MyDrive/ego4d_data/sta_clip_uids.txt
[HEAD] video: train=98276 → /content/drive/MyDrive/ego4d_data/v2/manifests/head_train_video.json
[HEAD] video:   val=47395   → /content/drive/MyDrive/ego4d_data/v2/manifests/head_val_video.json
[HEAD] clip : train=98276  → /content/drive/MyDrive/ego4d_data/v2/manifests/head_train_clip.json
[HEAD] clip :   val=47395    → /content/drive/MyDrive/ego4d_data/v2/manifests/head_val_clip.json

Done.

In [ ]:
import os

def summarize_directory(path):
    summary = []
    for root, dirs, files in os.walk(path):
        total_size = sum(os.path.getsize(os.path.join(root, f)) for f in files)
        summary.append({
            "folder": root,
            "num_subfolders": len(dirs),
            "num_files": len(files),
            "total_size_MB": round(total_size / (1024 * 1024), 2)
        })
    return summary

# Example usage
path = "/content/drive/MyDrive/ego4d_data/v2/tmp_frame_lists"
summary = summarize_directory(path)

import pandas as pd
df = pd.DataFrame(summary)
df

,folder,num_subfolders,num_files,total_size_MB
0,/content/drive/MyDrive/ego4d_data/v2/tmp_frame...,2,0,0.00
1,/content/drive/MyDrive/ego4d_data/v2/tmp_frame...,0,1311,0.79
2,/content/drive/MyDrive/ego4d_data/v2/tmp_frame...,0,2324,0.68

In [ ]:
import json, os, collections

EGO4D_ROOT = "/content/drive/MyDrive/ego4d_data"
ANN_DIR = f"{EGO4D_ROOT}/v2/annotations_540ss"
paths = [os.path.join(ANN_DIR, "fho_sta_train_height-540.json"),
         os.path.join(ANN_DIR, "fho_sta_val_height-540.json")]

by_video = collections.defaultdict(set)
for p in paths:
    data = json.load(open(p))
    anns = data["annotations"] if isinstance(data, dict) else data
    for r in anns:
        v = r.get("video_uid"); c = r.get("clip_uid")
        if v and c: by_video[v].add(c)

num_videos = len(by_video)
num_clips  = sum(len(s) for s in by_video.values())
avg_clips_per_video = num_clips / num_videos if num_videos else 0
print(f"videos={num_videos}, unique_clips={num_clips}, avg_clips_per_video={avg_clips_per_video:.2f}")

# (Optional) show a few videos with their clip counts
for i,(v,cs) in enumerate(by_video.items()):
    if i==5: break
    print(v, len(cs))

videos=1311, unique_clips=2324, avg_clips_per_video=1.77
26202090-684d-4be8-b3cc-de04da827e91 4
d8c894ab-7b08-4983-9e80-fdb5d6ee0202 4
cde41c4f-50d1-4910-9f2a-4c7b6987df92 9
5b97f47f-f015-46f3-8879-3fcc2a61a728 8
3b609b23-f91d-43da-9918-ce928181f53f 2

#json samples

In [ ]:
import json
import os

file_path_1 = "/content/drive/MyDrive/ego4d_data/v2/annotations_540ss/fho_sta_train_height-540.json"
file_path_2 = "/content/drive/MyDrive/ego4d_data/v2/annotations_540ss/fho_sta_val_height-540.json"

def display_first_entry(file_path):
    print(f"\n--- First entry from: {file_path} ---")
    if os.path.exists(file_path):
        try:
            with open(file_path, 'r') as f:
                data = json.load(f)

            if isinstance(data, list) and len(data) > 0:
                print(json.dumps(data[0], indent=2))
            elif isinstance(data, dict):
                print("Data is a dictionary. Looking for a list within it...")
                first_list_entry = None
                for key, value in data.items():
                    if isinstance(value, list) and len(value) > 0:
                        print(f"Found a list under key '{key}'. First entry:")
                        print(json.dumps(value[0], indent=2))
                        first_list_entry = value[0]
                        break
                if first_list_entry is None:
                     print("No list with at least one entry found in the dictionary.")
                     print("First few key-value pairs:")
                     print(json.dumps(dict(list(data.items())[:5]), indent=2))
            else:
                print("Data is neither a list nor a dictionary, or is empty.")
        except json.JSONDecodeError:
            print("Error: Could not decode JSON from the file.")
        except Exception as e:
            print(f"An error occurred while reading the file: {e}")

    else:
        print(f"File not found: {file_path}")

display_first_entry(file_path_1)
display_first_entry(file_path_2)

--- First entry from: /content/drive/MyDrive/ego4d_data/v2/annotations_540ss/fho_sta_train_height-540.json ---
Data is a dictionary. Looking for a list within it...
Found a list under key 'annotations'. First entry:
{
  "uid": "26202090-684d-4be8-b3cc-de04da827e91_0000984",
  "main_uid": "3b867f4f-958b-4735-aecd-5984998658a7",
  "video_uid": "26202090-684d-4be8-b3cc-de04da827e91",
  "frame": 984,
  "clip_id": 121,
  "clip_uid": "4f68183f-610a-44de-b102-e7f300b49dcd",
  "clip_frame": 984,
  "action_start_sec": 30.654361933333334,
  "action_end_sec": 38.654361933333334,
  "action_start_frame": 919,
  "action_end_frame": 1159,
  "action_clip_start_sec": 30.654361933333334,
  "action_clip_end_sec": 38.654361933333334,
  "action_clip_start_frame": 919,
  "action_clip_end_frame": 1159,
  "interval_start_frame": 0,
  "interval_end_frame": 8999,
  "interval_start_sec": 0.0,
  "interval_end_sec": 300.0,
  "clip_parent_start_sec": 0.0,
  "clip_parent_end_sec": 308.0,
  "clip_parent_start_frame": 0,
  "clip_parent_end_frame": 9239,
  "objects": [
    {
      "box": [
        117.66,
        21.65,
        290.845,
        220.09
      ],
      "verb_category_id": 34,
      "noun_category_id": 1,
      "time_to_contact": 1.7666666666666666
    }
  ]
}

--- First entry from: /content/drive/MyDrive/ego4d_data/v2/annotations_540ss/fho_sta_val_height-540.json ---
Data is a dictionary. Looking for a list within it...
Found a list under key 'annotations'. First entry:
{
  "uid": "d8c894ab-7b08-4983-9e80-fdb5d6ee0202_0149227",
  "main_uid": "f06f4635-9f5e-4cf5-9482-d6be03c6f786",
  "video_uid": "d8c894ab-7b08-4983-9e80-fdb5d6ee0202",
  "frame": 149227,
  "clip_id": 930,
  "clip_uid": "a8f95c5f-7d7b-419b-af29-60d97d8fe379",
  "clip_frame": 241,
  "action_start_sec": 4971.887695266666,
  "action_end_sec": 4979.887695266666,
  "action_start_frame": 149156,
  "action_end_frame": 149396,
  "action_clip_start_sec": 5.677695266665978,
  "action_clip_end_sec": 13.677695266665978,
  "action_clip_start_frame": 170,
  "action_clip_end_frame": 410,
  "interval_start_frame": 149226,
  "interval_end_frame": 151901,
  "interval_start_sec": 4974.21,
  "interval_end_sec": 5063.38,
  "clip_parent_start_sec": 4966.21,
  "clip_parent_end_sec": 5063.391028645833,
  "clip_parent_start_frame": 148986,
  "clip_parent_end_frame": 151901,
  "objects": [
    {
      "box": [
        295.9,
        1.295,
        718.06,
        376.83500000000004
      ],
      "verb_category_id": 34,
      "noun_category_id": 20,
      "time_to_contact": 1.8
    }
  ]
}

# estimate and tmp files

## Estimate video sizes and list tmp_frames_list

### Subtask:
For each video UID, if the actual size is not available, estimate it based on the frame count and a typical frame size (or average size from available data).

**Reasoning**:
For each video UID, if the actual size is not available, estimate it based on the frame count and a typical frame size (or average size from available data).

In [ ]:
# Estimate video sizes
# We'll use a simple estimation based on an average frame size if actual size isn't available.
# A more accurate estimation would require knowing the video's bitrate or average frame size in bytes.
# For demonstration, let's assume an average frame size (e.g., 50 KB per frame for 540p video).
# This is a rough estimate and may not be accurate for all videos.

ESTIMATED_BYTES_PER_FRAME = 50 * 1024 # 50 KB per frame (example for 540p)

video_sizes = {}
total_estimated_size = 0

for video_uid, frame_count in video_frame_counts.items():
    # In a real scenario, you would try to get the actual video size from metadata or file system
    # For this task, we are estimating if not available in the original JSON.
    # The provided JSON doesn't seem to have video size information per entry,
    # so we will rely solely on estimation for this step based on frame count.

    estimated_size = frame_count * ESTIMATED_BYTES_PER_FRAME
    video_sizes[video_uid] = {
        "frame_count": frame_count,
        "estimated_size_bytes": estimated_size
    }
    total_estimated_size += estimated_size

def format_bytes(byte_count):
    """Formats bytes into a human-readable string."""
    if byte_count is None:
        return "N/A"
    for unit in ['B', 'KB', 'MB', 'GB', 'TB']:
        if byte_count < 1024.0:
            return f"{byte_count:.2f} {unit}"
        byte_count /= 1024.0
    return f"{byte_count:.2f} PB"

print(f"\nEstimated sizes for {len(video_sizes)} videos.")
print(f"Total estimated size: {format_bytes(total_estimated_size)}")

# Print estimated sizes for the first few videos
print("\nEstimated sizes for first 5 videos:")
for i, (uid, info) in enumerate(video_sizes.items()):
    if i >= 5:
        break
    print(f"  {uid}: {info['frame_count']} frames, Estimated Size: {format_bytes(info['estimated_size_bytes'])}")

Estimated sizes for 989 videos.
Total estimated size: 4.69 GB

Estimated sizes for first 5 videos:
  002d2729-df71-438d-8396-5895b349e8fd: 601 frames, Estimated Size: 29.35 MB
  0031d268-818c-4ec4-a804-935be610a61a: 156 frames, Estimated Size: 7.62 MB
  0091e812-f56f-4bd9-ad65-019fc97c1ffe: 1 frames, Estimated Size: 50.00 KB
  0123d797-c17d-42db-8268-53150a0641ad: 30 frames, Estimated Size: 1.46 MB
  01db7c39-a512-4bac-b284-dff8c7360e80: 48 frames, Estimated Size: 2.34 MB

In [24]:
import os
import pandas as pd

# Change to the directory containing the frame lists
frame_lists_dir = "/content/drive/MyDrive/ego4d_data/v2/tmp_frame_lists/clips"
%cd "$frame_lists_dir"

# Get a list of available video UIDs (from the filenames)
available_uids = [f.replace("_clip_frames.txt", "") for f in os.listdir(".") if f.endswith("_clip_frames.txt")]
available_uids.sort() # Sort the UIDs for consistent indexing

print(f"Changed directory to: {os.getcwd()}")
print(f"Found {len(available_uids)} frame list files.")

# Function to find the number of frames for a given video UID
def get_frame_count(video_uid):
    file_path = f"{video_uid}_clip_frames.txt"
    if os.path.exists(file_path):
        try:
            with open(file_path, 'r') as f:
                frame_count = sum(1 for line in f if line.strip())
            return frame_count
        except Exception as e:
            print(f"Error reading file {file_path}: {e}")
            return None
    else:
        return None

# --- Set the range of video UIDs to process by index ---
start_index = 0  # <<< EDIT ME: Start index (0-based)
end_index = 2400    # <<< EDIT ME: End index (exclusive)

# Ensure the indices are within the bounds of the available UIDs list
start_index = max(0, start_index)
end_index = min(len(available_uids), end_index)

video_data = []

if start_index >= end_index:
    print("Warning: Start index is greater than or equal to end index. No UIDs to process.")
else:
    # Process the specified range of UIDs
    uids_to_process = available_uids[start_index:end_index]
    total_selected_videos = len(uids_to_process)
    total_frames_in_selection = 0

    print(f"\nProcessing UIDs from index {start_index} to {end_index-1}:")
    for i, video_uid in enumerate(uids_to_process):
        frame_count = get_frame_count(video_uid)

        if frame_count is not None:
            total_frames_in_selection += frame_count
            # Estimate video size (using a placeholder value for bytes per frame)
            ESTIMATED_BYTES_PER_FRAME = 50 * 1024 # 50 KB per frame (example)
            estimated_size_bytes = frame_count * ESTIMATED_BYTES_PER_FRAME
            video_data.append({
                'video_uid': video_uid,
                'frame_count': frame_count,
                'estimated_size_bytes': estimated_size_bytes
            })
        else:
            print(f"Index {start_index + i}: Frame list file not found for video UID '{video_uid}'.")

    # Create DataFrame
    df_video_summary = pd.DataFrame(video_data)

    print(f"\n--- Summary ---")
    print(f"Total videos selected: {total_selected_videos}")
    print(f"Total frames in selected videos: {total_frames_in_selection}")
    print("\nVideo Summary DataFrame (first 5 rows):")
    display(df_video_summary.head())

/content/drive/MyDrive/ego4d_data/v2/tmp_frame_lists/clips
Changed directory to: /content/drive/MyDrive/ego4d_data/v2/tmp_frame_lists/clips
Found 2324 frame list files.

Processing UIDs from index 0 to 2323:

KeyboardInterrupt:

# ============================
# Ego4D selective frame extraction + duplicate-safe downloading + stats
# ============================

In [ ]:
# ==============================================
# Ego4D — FINAL single cell (with SPECIFIC_UIDS)
# Use existing sta_uids.txt + *_frames.txt (no JSON reading)
# Variant switch:  "540" -> video_540ss,  "orig" -> full_scale
# Parallel download + parallel extraction + optional batch download
# Modes: 'from_lists' | 'first_n' | 'all'
# ==============================================
import os, subprocess, time, math, json, shutil
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import timedelta
from tqdm.auto import tqdm

# ---------------------- USER CONFIG ----------------------
EGO4D_ROOT   = "/content/drive/MyDrive/ego4d_data"
VERSION      = "v2"

# Choose video set:
#  - "540"  -> downscaled short-side=540 (dataset: video_540ss)
#  - "orig" -> full-scale canonical (dataset: full_scale)
ANN_VARIANT  = "540"              # <<< "540" or "orig"

# Extraction mode:
EXTRACTION_MODE = "first_n"    # <<< 'from_lists' | 'first_n' | 'all'
NUM_FRAMES_TO_EXTRACT = 500       # used only if EXTRACTION_MODE == 'first_n'

# Selection controls:
NUM_VIDEOS_TO_PROCESS = 3      # e.g., 50  (None = all)
SPECIFIC_UIDS = [                # <<< Optional: put UIDs here to force processing these only
    # "002d2729-df71-438d-8396-5895b349e8fd",
    # "0031d268-818c-4ec4-a804-935be610a61a",
]

# Download + extraction controls
DOWNLOAD_MISSING           = True
DELETE_VIDEO_AFTER         = False          # delete .mp4 after each successful extraction
USE_PARALLEL_DOWNLOADS     = True          # parallel ego4d downloads (I/O-bound)
USE_PARALLEL_EXTRACTION    = True          # parallel ffmpeg across videos (CPU/IO-bound)
BATCH_DOWNLOAD             = True         # use ego4d --video_uid_file in chunks instead of per-uid
BATCH_CHUNK_SIZE           = 100           # chunk size for batch download

N_DOWNLOAD_WORKERS         = 4             # 2-6 is reasonable on Colab
N_EXTRACT_WORKERS          = 2             # 2 is safe; 3 may be ok; >3 often slower
FFMPEG_TIMEOUT_SECS        = 1800
DOWNLOAD_TIMEOUT_SECS      = 3600
CHUNK_SIZE_FRAMES_SELECT   = 800           # frame indices per ffmpeg call (from_lists)
PRINT_PER_ITEM_INFO        = True         # set True for verbose per-item logs

# ---------------------- PATHS ----------------------
DATASET      = "video_540ss" if ANN_VARIANT == "540" else "full_scale"
VIDEO_DIR    = f"{EGO4D_ROOT}/{VERSION}/{DATASET}"
FRAME_LISTS_DIR = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists"   # expects <uid>_frames.txt already present
UID_LIST_FILE  = f"{EGO4D_ROOT}/sta_uids.txt"                 # expects list of video_uids already present
FRAMES_DRIVE_ROOT = f"{EGO4D_ROOT}/{VERSION}/extracted_frames"
FRAMES_TMP_ROOT   = "/content/tmp_frames"                     # fast local scratch
PROCESSED_LOG     = f"{EGO4D_ROOT}/{VERSION}/processed_uids_{ANN_VARIANT}.txt"

# ---------------------- PREP ----------------------
os.makedirs(VIDEO_DIR, exist_ok=True)
os.makedirs(FRAME_LISTS_DIR, exist_ok=True)
os.makedirs(FRAMES_DRIVE_ROOT, exist_ok=True)
os.makedirs(FRAMES_TMP_ROOT, exist_ok=True)

def which(cmd: str) -> bool:
    import shutil as _sh
    return _sh.which(cmd) is not None

def format_size(n):
    if n is None: return "N/A"
    for u in ["B","KB","MB","GB","TB"]:
        if n < 1024: return f"{n:.2f} {u}"
        n /= 1024
    return f"{n:.2f} PB"

def list_existing_jpgs(folder):
    return [f for f in os.listdir(folder) if f.lower().endswith(".jpg")] if os.path.isdir(folder) else []

def build_eqn_select(frames):
    return "+".join([f"eq(n\\,{int(n)})" for n in frames])

def ffprobe_video_info(video_path):
    info = {"nb_frames": None, "duration": None, "r_frame_rate": None,
            "width": None, "height": None, "size_bytes": None}
    if not os.path.exists(video_path):
        return info
    try:
        info["size_bytes"] = os.path.getsize(video_path)
    except Exception:
        pass
    cmd = ["ffprobe","-v","error","-select_streams","v:0",
           "-show_entries","stream=nb_frames,r_frame_rate,width,height:format=duration",
           "-of","json", video_path]
    try:
        res = subprocess.run(cmd, text=True, capture_output=True, check=True)
        data = json.loads(res.stdout or "{}")
        if "streams" in data and data["streams"]:
            s = data["streams"][0]
            if s.get("nb_frames") is not None:
                try: info["nb_frames"] = int(s["nb_frames"])
                except: pass
            info["r_frame_rate"] = s.get("r_frame_rate")
            info["width"]  = int(s["width"])  if s.get("width")  else None
            info["height"] = int(s["height"]) if s.get("height") else None
        if "format" in data and data["format"].get("duration") is not None:
            try: info["duration"] = float(data["format"]["duration"])
            except: pass
        if info["nb_frames"] in (None, 0):
            # fallback nb_frames ≈ fps * duration
            fps = None
            if info["r_frame_rate"]:
                try:
                    a,b = info["r_frame_rate"].split("/")
                    a = float(a); b = float(b) if float(b) != 0 else 1.0
                    fps = a/b
                except: pass
            if fps and info["duration"]:
                info["nb_frames"] = int(fps * info["duration"])
    except:
        pass
    return info

# ---------------------- FFMPEG RUNNERS ----------------------
def run_ffmpeg_select(video_path, frames, out_dir, start_number=None, chunk=800, timeout=1800):
    os.makedirs(out_dir, exist_ok=True)
    frames = sorted(set(int(x) for x in frames))
    if not frames: return 0, 0.0
    before = len(list_existing_jpgs(out_dir))
    if start_number is None: start_number = before
    t0 = time.time()
    for i in range(0, len(frames), chunk):
        piece = frames[i:i+chunk]
        vf = f"select='{build_eqn_select(piece)}',setpts=N/FRAME_RATE/TB"
        cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
               "-i", video_path, "-vf", vf, "-vsync","0",
               "-start_number", str(start_number),
               os.path.join(out_dir, "%07d.jpg")]
        subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
        start_number += len(piece)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

def run_ffmpeg_first_n(video_path, n, out_dir, timeout=1800):
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
           "-i", video_path, "-vframes", str(int(n)),
           os.path.join(out_dir, "%07d.jpg")]
    t0 = time.time()
    subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

def run_ffmpeg_all(video_path, out_dir, timeout=1800):
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
           "-i", video_path, "-vsync","0",
           os.path.join(out_dir, "%07d.jpg")]
    t0 = time.time()
    subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

# ---------------------- DOWNLOAD HELPERS ----------------------
def download_one(uid, timeout=3600, aws_profile=None):
    vpath = os.path.join(VIDEO_DIR, f"{uid}.mp4")
    if os.path.exists(vpath):
        return uid, True, 0.0, "present"
    if not which("ego4d"):
        return uid, False, 0.0, "ego4d CLI not found"

    cmd = ["ego4d","--output_directory", EGO4D_ROOT, "--datasets", DATASET,
           "--version", VERSION, "--video_uids", uid, "-y"]
    if aws_profile:
        cmd += ["--aws_profile_name", aws_profile]
    t0 = time.time()
    try:
        subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
        ok = os.path.exists(vpath); t1 = time.time()
        return uid, ok, (t1-t0), ("downloaded" if ok else "missing_after_dl")
    except subprocess.CalledProcessError as e:
        return uid, False, time.time()-t0, f"ego4d failed"
    except subprocess.TimeoutExpired:
        return uid, False, time.time()-t0, "timeout"

def batch_download_uids(uids, chunk_size=100, timeout=3600, aws_profile=None):
    if not which("ego4d"):
        print("  !!! ego4d CLI not found; cannot batch download.")
        return 0, len(uids)
    ok_total = 0
    for i in range(0, len(uids), chunk_size):
        chunk = uids[i:i+chunk_size]
        tmpfile = f"/content/ego4d_uids_{i//chunk_size}.txt"
        with open(tmpfile,"w") as f:
            f.write("\n".join(chunk))
        cmd = ["ego4d","--output_directory", EGO4D_ROOT, "--datasets", DATASET,
               "--version", VERSION, "--video_uid_file", tmpfile, "-y"]
        if aws_profile:
            cmd += ["--aws_profile_name", aws_profile]
        try:
            subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
        except subprocess.CalledProcessError:
            pass
        except subprocess.TimeoutExpired:
            pass
        ok_total += sum(os.path.exists(os.path.join(VIDEO_DIR, f"{u}.mp4")) for u in chunk)
        try: os.remove(tmpfile)
        except: pass
    return ok_total, len(uids)

# ---------------------- LOAD/CHOOSE UIDS ----------------------
def load_all_uids_from_file(path):
    if not os.path.exists(path):
        raise SystemExit(f"UID list not found: {path}")
    with open(path,"r") as f:
        return [ln.strip() for ln in f if ln.strip()]

# Merge logic:
# - If SPECIFIC_UIDS is non-empty: use that list (order preserved, dupes removed).
# - Else use sta_uids.txt.
# - Then, if EXTRACTION_MODE=='from_lists', drop any uid missing <uid>_frames.txt.
# - Finally, if NUM_VIDEOS_TO_PROCESS is set, keep only first N.
def choose_uids():
    if SPECIFIC_UIDS:
        seen = set()
        base = []
        for u in SPECIFIC_UIDS:
            if u not in seen:
                base.append(u); seen.add(u)
    else:
        base = load_all_uids_from_file(UID_LIST_FILE)

    if EXTRACTION_MODE == "from_lists":
        filtered = []
        for u in base:
            if os.path.exists(os.path.join(FRAME_LISTS_DIR, f"{u}_frames.txt")):
                filtered.append(u)
        if len(filtered) != len(base):
            print(f"NOTE: {len(base)-len(filtered)} uid(s) missing *_frames.txt → skipped.")
        base = filtered

    if NUM_VIDEOS_TO_PROCESS:
        base = base[:NUM_VIDEOS_TO_PROCESS]
    return base

uids_all = choose_uids()

print(f"Variant: {ANN_VARIANT} → dataset='{DATASET}', video dir='{VIDEO_DIR}'")
print(f"Selected {len(uids_all)} video(s) for mode='{EXTRACTION_MODE}'")
if SPECIFIC_UIDS:
    print(f"Using SPECIFIC_UIDS (length={len(SPECIFIC_UIDS)}).")

# ---------------------- PREFLIGHT ----------------------
if not which("ffmpeg"):
    raise SystemExit("Install ffmpeg first (e.g., `!apt-get -y install ffmpeg`).")
if DOWNLOAD_MISSING and not which("ego4d"):
    print("WARNING: ego4d CLI not found; downloads will be skipped.")

# ---------------------- DOWNLOAD PHASE ----------------------
outer_t0 = time.time()
downloaded_ct = 0

if DOWNLOAD_MISSING and uids_all:
    to_get = [u for u in uids_all if not os.path.exists(os.path.join(VIDEO_DIR, f"{u}.mp4"))]
    print(f"Need to download: {len(to_get)} video(s).")

    if BATCH_DOWNLOAD and to_get:
        ok_ct, total_ct = batch_download_uids(to_get, chunk_size=BATCH_CHUNK_SIZE, timeout=DOWNLOAD_TIMEOUT_SECS)
        downloaded_ct += ok_ct
        print(f"Batch downloaded {ok_ct}/{total_ct} (now present in {VIDEO_DIR}).")

    elif USE_PARALLEL_DOWNLOADS and to_get:
        print(f"Parallel downloading with {N_DOWNLOAD_WORKERS} workers ...")
        with ThreadPoolExecutor(max_workers=max(1, int(N_DOWNLOAD_WORKERS))) as ex:
            futures = [ex.submit(download_one, u, DOWNLOAD_TIMEOUT_SECS, None) for u in to_get]
            for fut in tqdm(as_completed(futures), total=len(futures)):
                uid, ok, secs, note = fut.result()
                downloaded_ct += int(ok)
                if PRINT_PER_ITEM_INFO:
                    print(f"  {uid} → {note} in {secs:.1f}s")
        print(f"Downloaded (parallel): {downloaded_ct}/{len(to_get)} new videos.")

    elif to_get:
        print("Serial downloading ...")
        for u in tqdm(to_get):
            uid, ok, secs, note = download_one(u, DOWNLOAD_TIMEOUT_SECS, None)
            downloaded_ct += int(ok)
            if PRINT_PER_ITEM_INFO:
                print(f"  {uid} → {note} in {secs:.1f}s")
        print(f"Downloaded (serial): {downloaded_ct}/{len(to_get)} new videos.")
else:
    print("Skipping downloads.")

# ---------------------- EXTRACTION PHASE ----------------------
def load_frames_for(uid):
    path = os.path.join(FRAME_LISTS_DIR, f"{uid}_frames.txt")
    if not os.path.exists(path): return []
    with open(path) as f:
        return [int(x.strip()) for x in f if x.strip()]

def extract_one(uid):
    vpath = os.path.join(VIDEO_DIR, f"{uid}.mp4")
    if not os.path.exists(vpath):
        return uid, 0, 0.0, 0, "video_missing"

    # probe (optional info)
    info = ffprobe_video_info(vpath)
    total_frames_video = info["nb_frames"] if info["nb_frames"] else 0
    w, h, vsize = info["width"], info["height"], info["size_bytes"]

    out_tmp   = os.path.join(FRAMES_TMP_ROOT, uid)    # fast local
    out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)  # Drive
    os.makedirs(out_tmp, exist_ok=True)

    try:
        if EXTRACTION_MODE == "all":
            new_count, secs = run_ffmpeg_all(vpath, out_tmp, timeout=FFMPEG_TIMEOUT_SECS)
            requested_ct = total_frames_video if total_frames_video else 0
        elif EXTRACTION_MODE == "first_n":
            new_count, secs = run_ffmpeg_first_n(vpath, NUM_FRAMES_TO_EXTRACT, out_tmp, timeout=FFMPEG_TIMEOUT_SECS)
            requested_ct = NUM_FRAMES_TO_EXTRACT
        elif EXTRACTION_MODE == "from_lists":
            frames = load_frames_for(uid)
            if not frames:
                return uid, 0, 0.0, total_frames_video, "no_frame_list"
            new_count, secs = run_ffmpeg_select(vpath, frames, out_tmp,
                                                chunk=CHUNK_SIZE_FRAMES_SELECT,
                                                timeout=FFMPEG_TIMEOUT_SECS)
            requested_ct = len(frames)
        else:
            return uid, 0, 0.0, total_frames_video, "bad_mode"

        # Move to Drive (fewer small writes)
        if os.path.exists(out_final):
            for f in os.listdir(out_tmp):
                src = os.path.join(out_tmp, f)
                dst = os.path.join(out_final, f)
                if not os.path.exists(dst):
                    shutil.move(src, dst)
            shutil.rmtree(out_tmp, ignore_errors=True)
        else:
            shutil.move(out_tmp, out_final)

        # Optionally delete source video
        if DELETE_VIDEO_AFTER:
            try: os.remove(vpath)
            except: pass

        imgs_now = len(list_existing_jpgs(out_final))
        if PRINT_PER_ITEM_INFO:
            print(f"  {uid}: {w}x{h}, {format_size(vsize)}, total≈{total_frames_video} | requested={requested_ct} new={new_count} now={imgs_now}")
        return uid, new_count, secs, total_frames_video, "ok"
    except subprocess.CalledProcessError:
        return uid, 0, 0.0, total_frames_video, "ffmpeg_failed"
    except Exception as e:
        return uid, 0, 0.0, total_frames_video, f"error:{str(e)[:80]}"

rows = []
total_requested, total_extracted = 0, 0
if USE_PARALLEL_EXTRACTION and uids_all:
    print(f"Parallel extraction with {N_EXTRACT_WORKERS} workers ...")
    with ThreadPoolExecutor(max_workers=max(1, int(N_EXTRACT_WORKERS))) as ex:
        futures = [ex.submit(extract_one, u) for u in uids_all]
        for fut in tqdm(as_completed(futures), total=len(futures)):
            uid, new_ct, secs, tf_all, note = fut.result()
            # infer requested count
            if EXTRACTION_MODE == "first_n":
                req_ct = NUM_FRAMES_TO_EXTRACT
            elif EXTRACTION_MODE == "all":
                req_ct = tf_all if tf_all else 0
            else:
                pth = os.path.join(FRAME_LISTS_DIR, f"{uid}_frames.txt")
                req_ct = sum(1 for _ in open(pth)) if os.path.exists(pth) else 0

            out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)
            imgs_now = len(list_existing_jpgs(out_final)) if os.path.exists(out_final) else 0

            rows.append((uid, req_ct, new_ct, imgs_now, tf_all, 0.0, secs, note))
            total_requested += req_ct
            total_extracted += new_ct
else:
    print("Serial extraction ...")
    for uid in tqdm(uids_all):
        uid, new_ct, secs, tf_all, note = extract_one(uid)
        if EXTRACTION_MODE == "first_n":
            req_ct = NUM_FRAMES_TO_EXTRACT
        elif EXTRACTION_MODE == "all":
            req_ct = tf_all if tf_all else 0
        else:
            pth = os.path.join(FRAME_LISTS_DIR, f"{uid}_frames.txt")
            req_ct = sum(1 for _ in open(pth)) if os.path.exists(pth) else 0
        out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)
        imgs_now = len(list_existing_jpgs(out_final)) if os.path.exists(out_final) else 0
        rows.append((uid, req_ct, new_ct, imgs_now, tf_all, 0.0, secs, note))
        total_requested += req_ct
        total_extracted += new_ct

# ---------------------- MARK DONE & SUMMARY ----------------------
with open(PROCESSED_LOG,"a") as f:
    for uid, *_ in rows:
        f.write(uid + "\n")

outer_t1 = time.time()
print("\n========== SUMMARY ==========")
print(f"Variant: {ANN_VARIANT} (dataset={DATASET})")
print(f"Mode: {EXTRACTION_MODE}")
print(f"Videos processed: {len(rows)} / {len(uids_all)} selected")
print(f"Frames requested (sum): {total_requested}")
print(f"Frames extracted (new this run): {total_extracted}")
print(f"Total wall time: {timedelta(seconds=int(outer_t1-outer_t0))}")

if rows:
    print("\n[uid | req | new | imgs_now | total_frames | download_s | extract_s | note]")
    for uid, req, new, imgs, tf, dls, exs, note in rows[:40]:
        tf_disp = f"{tf}" if tf not in (None, 0) else "unknown"
        print(f"{uid} | {req:4d} | {new:4d} | {imgs:7d} | {tf_disp:12} | {dls:10.1f} | {exs:9.1f} | {note}")

print(f"\nFrames on Drive: {FRAMES_DRIVE_ROOT}")
print(f"Processed log updated: {PROCESSED_LOG}")
print("=============================================")

Variant: 540 → dataset='video_540ss', video dir='/content/drive/MyDrive/ego4d_data/v2/video_540ss'
Selected 3 video(s) for mode='first_n'
Need to download: 0 video(s).
Parallel extraction with 2 workers ...

  0%|          | 0/3 [00:00<?, ?it/s]

  000cd456-ff8d-499b-b0c1-4acead128a8b: 720x540, 117.08 MB, total≈28744 | requested=500 new=500 now=500
  002c3b5c-ed86-4af3-99a1-4b497b7c8a86: 720x540, 450.92 MB, total≈82740 | requested=500 new=500 now=500
  002d2729-df71-438d-8396-5895b349e8fd: 720x540, 554.02 MB, total≈107143 | requested=500 new=500 now=500

========== SUMMARY ==========
Variant: 540 (dataset=video_540ss)
Mode: first_n
Videos processed: 3 / 3 selected
Frames requested (sum): 1500
Frames extracted (new this run): 1500
Total wall time: 0:00:30

[uid | req | new | imgs_now | total_frames | download_s | extract_s | note]
000cd456-ff8d-499b-b0c1-4acead128a8b |  500 |  500 |     500 | 28744        |        0.0 |      10.6 | ok
002c3b5c-ed86-4af3-99a1-4b497b7c8a86 |  500 |  500 |     500 | 82740        |        0.0 |      10.9 | ok
002d2729-df71-438d-8396-5895b349e8fd |  500 |  500 |     500 | 107143       |        0.0 |       5.3 | ok

Frames on Drive: /content/drive/MyDrive/ego4d_data/v2/extracted_frames
Processed log updated: /content/drive/MyDrive/ego4d_data/v2/processed_uids_540.txt
=============================================

#Final working frame extraction code

In [ ]:
# ============================
# Ego4D: download-if-missing + ffprobe totals + multi-mode extraction (incl. 'all')
# + per-video timing + no-dup log + optional delete .mp4 after extraction
# Modes: 'single' | 'first_n' | 'range' | 'list' | 'from_lists' | 'all'
# ============================
import os, subprocess, json, time, math, shutil
from datetime import timedelta
from tqdm.auto import tqdm

# ---------- Small utils ----------
def which_or_msg(cmd):
    p = shutil.which(cmd)
    if not p:
        print(f"ERROR: '{cmd}' not found on PATH.")
        return False
    return True

def get_folder_info(folder_path):
    total_size = 0
    image_count = 0
    if os.path.exists(folder_path):
        for dirpath, _, filenames in os.walk(folder_path):
            for f in filenames:
                fp = os.path.join(dirpath, f)
                if not os.path.islink(fp):
                    try:
                        total_size += os.path.getsize(fp)
                    except FileNotFoundError:
                        pass
                    if f.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
                        image_count += 1
    return total_size, image_count

def format_size(n):
    if n is None: return "N/A"
    for u in ["B","KB","MB","GB","TB"]:
        if n < 1024: return f"{n:.2f} {u}"
        n /= 1024
    return f"{n:.2f} PB"

def read_uid_list(path):
    if not os.path.exists(path): return []
    with open(path, "r") as f:
        return [line.strip() for line in f if line.strip()]

def list_existing_jpgs(folder):
    return [f for f in os.listdir(folder) if f.lower().endswith(".jpg")] if os.path.isdir(folder) else []

def build_eqn_select(frames):
    # ffmpeg expression: eq(n\,f1)+eq(n\,f2)+...
    return "+".join([f"eq(n\\,{int(n)})" for n in frames])

# ---------- FFPROBE ----------
def ffprobe_video_info(video_path):
    """
    Returns dict:
      {
        'nb_frames': int or None,
        'duration': float or None,
        'r_frame_rate': 'num/den' or None,
        'width': int or None,
        'height': int or None,
        'size_bytes': int or None
      }
    Tries nb_frames first; if missing, estimates from r_frame_rate * duration.
    """
    info = {
        "nb_frames": None, "duration": None, "r_frame_rate": None,
        "width": None, "height": None, "size_bytes": None
    }
    if not os.path.exists(video_path):
        return info
    try:
        info["size_bytes"] = os.path.getsize(video_path)
    except Exception:
        pass

    cmd = [
        "ffprobe", "-v", "error",
        "-select_streams", "v:0",
        "-show_entries", "stream=nb_frames,r_frame_rate,width,height:format=duration",
        "-of", "json", video_path
    ]
    try:
        res = subprocess.run(cmd, text=True, capture_output=True, check=True)
        data = json.loads(res.stdout or "{}")
        if "streams" in data and data["streams"]:
            s = data["streams"][0]
            if "nb_frames" in s and s["nb_frames"] is not None:
                try: info["nb_frames"] = int(s["nb_frames"])
                except: pass
            if "r_frame_rate" in s: info["r_frame_rate"] = s["r_frame_rate"]
            if "width" in s: info["width"] = int(s["width"])
            if "height" in s: info["height"] = int(s["height"])
        if "format" in data and "duration" in data["format"]:
            try: info["duration"] = float(data["format"]["duration"])
            except: pass

        # Fallback for nb_frames
        if info["nb_frames"] in (None, 0):
            fps = None
            if info["r_frame_rate"]:
                try:
                    a, b = info["r_frame_rate"].split("/")
                    a = float(a); b = float(b) if float(b) != 0 else 1.0
                    fps = a / b
                except:
                    pass
            if fps and info["duration"]:
                info["nb_frames"] = int(fps * info["duration"])
        return info
    except:
        return info

# ---------- FFmpeg runners ----------
def run_ffmpeg_select(video_path, frames, out_dir, start_number=None, chunk_size=800, timeout_secs=1800):
    """Extract frames in chunks using eq(n\,...) + setpts; returns (#new files, seconds)."""
    os.makedirs(out_dir, exist_ok=True)
    frames = sorted(set(int(x) for x in frames))
    if not frames: return 0, 0.0
    before = len(list_existing_jpgs(out_dir))
    if start_number is None:
        start_number = before

    t0 = time.time()
    total_chunks = math.ceil(len(frames) / chunk_size)
    with tqdm(total=total_chunks, desc=f"extract(eq) {os.path.basename(video_path)}", leave=False) as pbar:
        for i in range(0, len(frames), chunk_size):
            chunk = frames[i:i+chunk_size]
            expr = build_eqn_select(chunk)
            vf = f"select='{expr}',setpts=N/FRAME_RATE/TB"
            cmd = [
                "ffmpeg", "-y",
                "-i", video_path,
                "-vf", vf,
                "-vsync", "0",
                "-start_number", str(start_number),
                os.path.join(out_dir, "%07d.jpg"),
            ]
            c0 = time.time()
            subprocess.run(cmd, text=True, capture_output=True, check=True, timeout=timeout_secs)
            c1 = time.time()
            pbar.set_postfix_str(f"chunk {i//chunk_size+1}/{total_chunks} ({len(chunk)} fr) {c1-c0:.1f}s")
            start_number += len(chunk)
            pbar.update(1)
    t1 = time.time()
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (t1 - t0)

def run_ffmpeg_first_n(video_path, n, out_dir, timeout_secs=1800):
    """Extract first N frames via -vframes; returns (#new files, seconds)."""
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = [
        "ffmpeg", "-y",
        "-i", video_path,
        "-vframes", str(int(n)),
        os.path.join(out_dir, "%07d.jpg"),
    ]
    t0 = time.time()
    subprocess.run(cmd, text=True, capture_output=True, check=True, timeout=timeout_secs)
    t1 = time.time()
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (t1 - t0)

def run_ffmpeg_all_frames(video_path, out_dir, timeout_secs=1800):
    """Extract ALL frames with -vsync 0; returns (#new files, seconds)."""
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = [
        "ffmpeg", "-y",
        "-i", video_path,
        "-vsync", "0",
        os.path.join(out_dir, "%07d.jpg"),
    ]
    t0 = time.time()
    subprocess.run(cmd, text=True, capture_output=True, check=True, timeout=timeout_secs)
    t1 = time.time()
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (t1 - t0)

# ---------- Ego4D download (assumes your AWS/Ego4D setup already works) ----------
def download_one_video_if_needed(uid, root, version, video_dir, timeout_secs=3600, aws_profile=None):
    """
    Download via ego4d CLI if missing.
    Returns (ok:bool, seconds:float, note:str)
    """
    vpath = os.path.join(video_dir, f"{uid}.mp4")
    if os.path.exists(vpath):
        return True, 0.0, "present"

    if not which_or_msg("ego4d"):
        return False, 0.0, "ego4d CLI not found"

    cmd = [
        "ego4d",
        "--output_directory", root,
        "--datasets", "full_scale",
        "--version", version,
        "--video_uids", uid,
        "-y",
    ]
    if aws_profile:
        cmd.extend(["--aws_profile_name", aws_profile])

    t0 = time.time()
    try:
        subprocess.run(cmd, text=True, capture_output=True, check=True, timeout=timeout_secs)
        ok = os.path.exists(vpath)
        t1 = time.time()
        if ok:
            return True, t1 - t0, f"downloaded in {t1 - t0:.1f}s"
        else:
            return False, t1 - t0, "download OK, file missing"
    except subprocess.CalledProcessError as e:
        return False, time.time()-t0, f"ego4d failed: {e.stderr[-500:]}"
    except subprocess.TimeoutExpired:
        return False, time.time()-t0, "ego4d timed out"

# ---------- Paths & core config ----------
EGO4D_ROOT = "/content/drive/MyDrive/ego4d_data"
VERSION = "v2"

VIDEO_DIR        = f"{EGO4D_ROOT}/{VERSION}/full_scale"            # where CLI places full_scale videos
FRAME_LISTS_DIR  = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists"       # <uid>_frames.txt for 'from_lists'
UID_LIST_FILE    = f"{EGO4D_ROOT}/sta_uids.txt"                    # one video_uid per line
OUTPUT_BASE_DIR  = f"{EGO4D_ROOT}/{VERSION}/extracted_frames"      # frames/<uid>/*.jpg
PROCESSED_LOG    = f"{EGO4D_ROOT}/{VERSION}/processed_uids.txt"    # avoid reprocessing

os.makedirs(VIDEO_DIR, exist_ok=True)
os.makedirs(OUTPUT_BASE_DIR, exist_ok=True)

# ---------- Selection controls ----------
NUM_VIDEOS_TO_PROCESS = 1        # None for all available
EXTRACTION_MODE = 'first_n'          # 'single' | 'first_n' | 'range' | 'list' | 'from_lists' | 'all'
DELETE_VIDEO_AFTER = True        # Delete(True)/ Keep(False) video after extraction

# Mode params
FRAME_NUMBER_TO_EXTRACT = 0
NUM_FRAMES_TO_EXTRACT   = 50
START_FRAME             = 100
END_FRAME               = 300
FRAME_LIST_TO_EXTRACT   = [450, 465, 480, 495]

# Behavior
DOWNLOAD_MISSING        = True
AWS_PROFILE             = None     # e.g., "default" or "ego4d"; None -> ego4d default
FFMPEG_TIMEOUT_SECS     = 1800
DOWNLOAD_TIMEOUT_SECS   = 3600
CHUNK_SIZE              = 800

# ---------- Build candidate list ----------
uids_all = read_uid_list(UID_LIST_FILE)
lists_available = [f for f in os.listdir(FRAME_LISTS_DIR) if f.endswith("_frames.txt")] if os.path.exists(FRAME_LISTS_DIR) else []
uids_with_lists = {f.replace("_frames.txt","") for f in lists_available}

if EXTRACTION_MODE == "from_lists":
    candidate_uids = [u for u in uids_all if u in uids_with_lists]
else:
    candidate_uids = uids_all

done = set(open(PROCESSED_LOG).read().split()) if os.path.exists(PROCESSED_LOG) else set()
pool = [u for u in candidate_uids if u not in done]
picked = pool[:NUM_VIDEOS_TO_PROCESS] if NUM_VIDEOS_TO_PROCESS else pool

print(f"Videos available in sta_uids.txt: {len(uids_all)}")
if EXTRACTION_MODE == "from_lists":
    print(f"Per-video frame lists found: {len(uids_with_lists)} in {FRAME_LISTS_DIR}")
print(f"Selected {len(picked)} video(s) for mode='{EXTRACTION_MODE}'")

# ---------- Preflight ----------
if not which_or_msg("ffmpeg"):
    raise SystemExit("Install ffmpeg first.")
if DOWNLOAD_MISSING and not which_or_msg("ego4d"):
    print("WARNING: ego4d CLI not found; you won't be able to auto-download missing videos.")

# ---------- Main loop ----------
total_requested = 0
total_extracted = 0
rows = []                 # for pretty table at end
processed_success = []
issues = []

outer_t0 = time.time()

def append_done(path, uids):
    if not uids: return
    with open(path, "a") as f:
        for u in uids: f.write(u+"\n")

for idx, uid in enumerate(picked, 1):
    print(f"\n[{idx}/{len(picked)}] {uid}")
    vpath = os.path.join(VIDEO_DIR, f"{uid}.mp4")
    out_dir = os.path.join(OUTPUT_BASE_DIR, uid)
    os.makedirs(out_dir, exist_ok=True)

    # 1) Download if missing (time it)
    dl_secs = 0.0
    dl_note = "present"
    if DOWNLOAD_MISSING and not os.path.exists(vpath):
        ok, dl_secs, dl_note = download_one_video_if_needed(uid, EGO4D_ROOT, VERSION, VIDEO_DIR,
                                                            timeout_secs=DOWNLOAD_TIMEOUT_SECS,
                                                            aws_profile=AWS_PROFILE)
        if not ok:
            print("  Skipping due to download issue.")
            issues.append((uid, "download_failed"))
            continue

    if not os.path.exists(vpath):
        print(f"  WARNING: video not found at {vpath}. Skipping.")
        issues.append((uid, "video_missing"))
        continue

    # 2) ffprobe: total frames, dimensions, size
    vinfo = ffprobe_video_info(vpath)
    total_frames_video = vinfo["nb_frames"] if vinfo["nb_frames"] is not None else 0
    w, h = vinfo["width"], vinfo["height"]
    vsize = vinfo["size_bytes"]
    print(f"  Video info: {w}x{h}, {format_size(vsize)}, total_frames≈{total_frames_video if total_frames_video else 'unknown'}")

    # 3) Decide requested frames this run
    if EXTRACTION_MODE == "single":
        req_frames = [int(FRAME_NUMBER_TO_EXTRACT)]
    elif EXTRACTION_MODE == "first_n":
        req_frames = list(range(1, int(NUM_FRAMES_TO_EXTRACT)+1))  # for reporting only
    elif EXTRACTION_MODE == "range":
        if END_FRAME < START_FRAME:
            print("  ERROR: END_FRAME < START_FRAME; skipping.")
            issues.append((uid, "bad_range"))
            continue
        req_frames = list(range(int(START_FRAME), int(END_FRAME)+1))
    elif EXTRACTION_MODE == "list":
        req_frames = [int(x) for x in FRAME_LIST_TO_EXTRACT]
    elif EXTRACTION_MODE == "from_lists":
        fpath = os.path.join(FRAME_LISTS_DIR, f"{uid}_frames.txt")
        if not os.path.exists(fpath):
            print("  No frame list found; skipping.")
            issues.append((uid, "no_frame_list"))
            continue
        with open(fpath, "r") as f:
            req_frames = [int(x.strip()) for x in f if x.strip()]
    elif EXTRACTION_MODE == "all":
        req_frames = None  # not used; we dump all frames
    else:
        print(f"  ERROR: Unknown EXTRACTION_MODE '{EXTRACTION_MODE}'.")
        issues.append((uid, "unknown_mode"))
        continue

    # 4) Extract (time it)
    if EXTRACTION_MODE == "first_n":
        new_count, ex_secs = run_ffmpeg_first_n(vpath, int(NUM_FRAMES_TO_EXTRACT), out_dir,
                                                timeout_secs=FFMPEG_TIMEOUT_SECS)
        requested_ct = len(req_frames)
    elif EXTRACTION_MODE == "all":
        new_count, ex_secs = run_ffmpeg_all_frames(vpath, out_dir, timeout_secs=FFMPEG_TIMEOUT_SECS)
        requested_ct = total_frames_video if total_frames_video else 0
    else:
        new_count, ex_secs = run_ffmpeg_select(vpath, req_frames, out_dir,
                                               chunk_size=CHUNK_SIZE, timeout_secs=FFMPEG_TIMEOUT_SECS)
        requested_ct = len(req_frames)

    imgs_now = len(list_existing_jpgs(out_dir))
    total_requested += requested_ct
    total_extracted += new_count

    # 5) Print per-video summary + running count vs total frames
    print(f"  Requested: {requested_ct} | New extracted: {new_count} | Total JPGs now: {imgs_now}")
    if total_frames_video:
        print(f"  {imgs_now}/{total_frames_video} total frames for this video extracted")
    else:
        print(f"  {imgs_now}/(unknown total) frames extracted")
    print(f"  Timing: download {dl_secs:.1f}s | extract {ex_secs:.1f}s")

    # 6) Delete the source .mp4 to save space (controlled by flag)
    if DELETE_VIDEO_AFTER:
        try:
            os.remove(vpath)
            print("  Source video deleted to free space.")
        except Exception as e:
            print(f"  Could not delete video: {e}")
    else:
        print("  Keeping source video (DELETE_VIDEO_AFTER=False).")

    # 7) accumulate row: include total frames & cumulative time since start
    cumulative = time.time() - outer_t0
    rows.append((uid, requested_ct, new_count, imgs_now, total_frames_video, dl_secs, ex_secs, f"{cumulative:.1f}s"))
    processed_success.append(uid)

# ---------- Mark done ----------
def append_done(path, uids):
    if not uids: return
    with open(path, "a") as f:
        for u in uids: f.write(u+"\n")
append_done(PROCESSED_LOG, processed_success)

# ---------- Summary ----------
outer_t1 = time.time()
print("\n========== SUMMARY ==========")
print(f"Mode: {EXTRACTION_MODE}")
print(f"Videos processed: {len(rows)} / {len(picked)} selected")
print(f"Frames requested (sum): {total_requested}")
print(f"Frames extracted (new this run): {total_extracted}")
print(f"Total wall time: {timedelta(seconds=int(outer_t1-outer_t0))}")

# Table header
if rows:
    print("\n[uid | req | new | imgs_now | total_frames | download_s | extract_s | cumulative]")
    for uid, req, new, imgs, tf, dls, exs, cum in rows[:20]:
        tf_disp = f"{tf}" if tf not in (None, 0) else "unknown"
        print(f"{uid} | {req:4d} | {new:4d} | {imgs:7d} | {tf_disp:12} | {dls:10.1f} | {exs:9.1f} | {cum}")

# Folder sizes
size_bytes, img_count = get_folder_info(OUTPUT_BASE_DIR)
print(f"\nOutput frames root: {OUTPUT_BASE_DIR}")
print(f"  Total size: {format_size(size_bytes)}")
print(f"  Total images: {img_count}")

if EXTRACTION_MODE == "from_lists":
    fl_size, _ = get_folder_info(FRAME_LISTS_DIR)
    print(f"\nFrame lists dir: {FRAME_LISTS_DIR}")
    print(f"  Size:  {format_size(fl_size)}")

if issues:
    print("\nVideos with issues:")
    for uid, err in issues[:20]:
        print(f"  - {uid} → {err}")

print(f"\nProcessed log updated: {PROCESSED_LOG}")
print("================================")

<>:117: SyntaxWarning: invalid escape sequence '\,'
<>:117: SyntaxWarning: invalid escape sequence '\,'
/tmp/ipython-input-1660950350.py:117: SyntaxWarning: invalid escape sequence '\,'
  """Extract frames in chunks using eq(n\,...) + setpts; returns (#new files, seconds)."""

Videos available in sta_uids.txt: 1311
Selected 1 video(s) for mode='first_n'

[1/1] 0377792b-7b1e-4d67-86fd-f50c9257ea85
  Video info: 1440x1080, 253.20 MB, total_frames≈36633
  Requested: 50 | New extracted: 0 | Total JPGs now: 14112
  14112/36633 total frames for this video extracted
  Timing: download 0.0s | extract 16.0s
  Source video deleted to free space.

========== SUMMARY ==========
Mode: first_n
Videos processed: 1 / 1 selected
Frames requested (sum): 50
Frames extracted (new this run): 0
Total wall time: 0:01:15

[uid | req | new | imgs_now | total_frames | download_s | extract_s | cumulative]
0377792b-7b1e-4d67-86fd-f50c9257ea85 |   50 |    0 |   14112 | 36633        |        0.0 |      16.0 | 75.2s

Output frames root: /content/drive/MyDrive/ego4d_data/v2/extracted_frames
  Total size: 622.26 MB
  Total images: 15714

Processed log updated: /content/drive/MyDrive/ego4d_data/v2/processed_uids.txt
================================

In [ ]:
# Replace '/path/to/your/directory' with the actual directory path you want to check
folder_path = "/content/drive/MyDrive/ego4d_data/v2/extracted_frames/0377792b-7b1e-4d67-86fd-f50c9257ea85"  # <<< EDIT ME

folder_size, image_count = get_folder_info(folder_path)
print(f"Number of image files in the folder '{folder_path}': {image_count}")

Number of image files in the folder '/content/drive/MyDrive/ego4d_data/v2/extracted_frames/0377792b-7b1e-4d67-86fd-f50c9257ea85': 14112

# 540

In [ ]:
# ============================
# Ego4D: use existing sta_uids.txt + *_frames.txt
# - ANN_VARIANT="540"  -> download from video_540ss and extract frames
# - ANN_VARIANT="orig" -> download from full_scale and extract frames
# Modes: 'single' | 'first_n' | 'range' | 'list' | 'from_lists' | 'all'
# ============================
import os, subprocess, json, time, math, shutil
from datetime import timedelta
from tqdm.auto import tqdm

# ---------------- Config ----------------
EGO4D_ROOT = "/content/drive/MyDrive/ego4d_data"
VERSION = "v2"

# Choose which video set to use:
#  - "540"  -> downscaled short-side=540 videos (dataset: video_540ss)
#  - "orig" -> full-scale canonical videos (dataset: full_scale)
ANN_VARIANT = "540"   # <<< set "540" or "orig"

# Extraction controls
NUM_VIDEOS_TO_PROCESS = 2                # None for all in sta_uids.txt
EXTRACTION_MODE = 'first_n'           # 'single'|'first_n'|'range'|'list'|'from_lists'|'all'
DELETE_VIDEO_AFTER = False                # remove .mp4 after extraction

# Mode params (used by the selected mode)
FRAME_NUMBER_TO_EXTRACT = 0
NUM_FRAMES_TO_EXTRACT   = 200
START_FRAME             = 100
END_FRAME               = 300
FRAME_LIST_TO_EXTRACT   = [450, 465, 480, 495]

# Download / runtime
DOWNLOAD_MISSING      = True
AWS_PROFILE           = None   # e.g. "default"|"ego4d"|None
FFMPEG_TIMEOUT_SECS   = 1800
DOWNLOAD_TIMEOUT_SECS = 3600
CHUNK_SIZE            = 800

# ---------------- Paths ----------------
if ANN_VARIANT == "540":
    DATASET_NAME  = "video_540ss"
    VIDEO_DIR     = f"{EGO4D_ROOT}/{VERSION}/video_540ss"
    PROCESSED_LOG = f"{EGO4D_ROOT}/{VERSION}/processed_uids_540.txt"
elif ANN_VARIANT == "orig":
    DATASET_NAME  = "full_scale"
    VIDEO_DIR     = f"{EGO4D_ROOT}/{VERSION}/full_scale"
    PROCESSED_LOG = f"{EGO4D_ROOT}/{VERSION}/processed_uids_full.txt"
else:
    raise ValueError("ANN_VARIANT must be '540' or 'orig'")

FRAME_LISTS_DIR  = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists"   # expects <uid>_frames.txt already present
UID_LIST_FILE    = f"{EGO4D_ROOT}/sta_uids.txt"                # expects list of video_uids already present
OUTPUT_BASE_DIR  = f"{EGO4D_ROOT}/{VERSION}/extracted_frames"  # frames/<uid>/*.jpg

os.makedirs(VIDEO_DIR, exist_ok=True)
os.makedirs(FRAME_LISTS_DIR, exist_ok=True)
os.makedirs(OUTPUT_BASE_DIR, exist_ok=True)

# ------------- Utils -------------
def which_or_msg(cmd):
    p = shutil.which(cmd)
    if not p:
        print(f"ERROR: '{cmd}' not found on PATH.")
        return False
    return True

def get_folder_info(folder_path):
    total_size, image_count = 0, 0
    if os.path.exists(folder_path):
        for dirpath, _, filenames in os.walk(folder_path):
            for f in filenames:
                fp = os.path.join(dirpath, f)
                if not os.path.islink(fp):
                    try:
                        total_size += os.path.getsize(fp)
                    except FileNotFoundError:
                        pass
                    if f.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
                        image_count += 1
    return total_size, image_count

def format_size(n):
    if n is None: return "N/A"
    for u in ["B","KB","MB","GB","TB"]:
        if n < 1024: return f"{n:.2f} {u}"
        n /= 1024
    return f"{n:.2f} PB"

def list_existing_jpgs(folder):
    return [f for f in os.listdir(folder) if f.lower().endswith(".jpg")] if os.path.isdir(folder) else []

def build_eqn_select(frames):
    return "+".join([f"eq(n\\,{int(n)})" for n in frames])

def ffprobe_video_info(video_path):
    info = {"nb_frames": None, "duration": None, "r_frame_rate": None,
            "width": None, "height": None, "size_bytes": None}
    if not os.path.exists(video_path):
        return info
    try:
        info["size_bytes"] = os.path.getsize(video_path)
    except Exception:
        pass
    cmd = [
        "ffprobe","-v","error","-select_streams","v:0",
        "-show_entries","stream=nb_frames,r_frame_rate,width,height:format=duration",
        "-of","json", video_path
    ]
    try:
        res = subprocess.run(cmd, text=True, capture_output=True, check=True)
        data = json.loads(res.stdout or "{}")
        if "streams" in data and data["streams"]:
            s = data["streams"][0]
            if s.get("nb_frames") is not None:
                try: info["nb_frames"] = int(s["nb_frames"])
                except: pass
            info["r_frame_rate"] = s.get("r_frame_rate")
            info["width"]  = int(s["width"])  if s.get("width")  else None
            info["height"] = int(s["height"]) if s.get("height") else None
        if "format" in data and data["format"].get("duration") is not None:
            try: info["duration"] = float(data["format"]["duration"])
            except: pass
        if info["nb_frames"] in (None, 0):
            fps = None
            if info["r_frame_rate"]:
                try:
                    a,b = info["r_frame_rate"].split("/")
                    a = float(a); b = float(b) if float(b) != 0 else 1.0
                    fps = a/b
                except:
                    pass
            if fps and info["duration"]:
                info["nb_frames"] = int(fps * info["duration"])
    except:
        pass
    return info

# ------------- FFmpeg runners -------------
def run_ffmpeg_select(video_path, frames, out_dir, start_number=None, chunk_size=800, timeout_secs=1800):
    os.makedirs(out_dir, exist_ok=True)
    frames = sorted(set(int(x) for x in frames))
    if not frames: return 0, 0.0
    before = len(list_existing_jpgs(out_dir))
    if start_number is None:
        start_number = before
    t0 = time.time()
    total_chunks = math.ceil(len(frames) / chunk_size)
    with tqdm(total=total_chunks, desc=f"extract(eq) {os.path.basename(video_path)}", leave=False) as pbar:
        for i in range(0, len(frames), chunk_size):
            chunk = frames[i:i+chunk_size]
            expr = build_eqn_select(chunk)
            vf = f"select='{expr}',setpts=N/FRAME_RATE/TB"
            cmd = ["ffmpeg","-y","-i",video_path,"-vf",vf,"-vsync","0","-start_number",str(start_number),
                   os.path.join(out_dir, "%07d.jpg")]
            c0 = time.time()
            subprocess.run(cmd, text=True, capture_output=True, check=True, timeout=timeout_secs)
            c1 = time.time()
            pbar.set_postfix_str(f"chunk {i//chunk_size+1}/{total_chunks} ({len(chunk)} fr) {c1-c0:.1f}s")
            start_number += len(chunk); pbar.update(1)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

def run_ffmpeg_first_n(video_path, n, out_dir, timeout_secs=1800):
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = ["ffmpeg","-y","-i",video_path,"-vframes",str(int(n)), os.path.join(out_dir, "%07d.jpg")]
    t0 = time.time()
    subprocess.run(cmd, text=True, capture_output=True, check=True, timeout=timeout_secs)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

def run_ffmpeg_all_frames(video_path, out_dir, timeout_secs=1800):
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = ["ffmpeg","-y","-i",video_path,"-vsync","0", os.path.join(out_dir, "%07d.jpg")]
    t0 = time.time()
    subprocess.run(cmd, text=True, capture_output=True, check=True, timeout=timeout_secs)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

# ------------- Download -------------
def download_one_video_if_needed(uid, root, version, dataset_name, video_dir, timeout_secs=3600, aws_profile=None):
    vpath = os.path.join(video_dir, f"{uid}.mp4")
    if os.path.exists(vpath):
        return True, 0.0, "present"
    if not which_or_msg("ego4d"):
        return False, 0.0, "ego4d CLI not found"
    cmd = ["ego4d","--output_directory", root,"--datasets", dataset_name,
           "--version", version,"--video_uids", uid,"-y"]
    if aws_profile:
        cmd.extend(["--aws_profile_name", aws_profile])
    t0 = time.time()
    try:
        subprocess.run(cmd, text=True, capture_output=True, check=True, timeout=timeout_secs)
        ok = os.path.exists(vpath); t1 = time.time()
        return (True, t1-t0, f"downloaded in {t1-t0:.1f}s") if ok else (False, t1-t0, "download OK, file missing")
    except subprocess.CalledProcessError as e:
        return False, time.time()-t0, f"ego4d failed: {e.stderr[-500:]}"
    except subprocess.TimeoutExpired:
        return False, time.time()-t0, "ego4d timed out"

# ------------- Candidate list (no JSON reading; use existing files) -------------
if not os.path.exists(UID_LIST_FILE):
    raise SystemExit(f"UID list not found: {UID_LIST_FILE} (generate it beforehand)")

with open(UID_LIST_FILE,"r") as f:
    uids_all = [x.strip() for x in f if x.strip()]

if EXTRACTION_MODE == "from_lists":
    lists_available = [f for f in os.listdir(FRAME_LISTS_DIR) if f.endswith("_frames.txt")] if os.path.exists(FRAME_LISTS_DIR) else []
    uids_with_lists = {f.replace("_frames.txt","") for f in lists_available}
    candidate_uids = [u for u in uids_all if u in uids_with_lists]
else:
    candidate_uids = uids_all

done = set(open(PROCESSED_LOG).read().split()) if os.path.exists(PROCESSED_LOG) else set()
pool = [u for u in candidate_uids if u not in done]
picked = pool[:NUM_VIDEOS_TO_PROCESS] if NUM_VIDEOS_TO_PROCESS else pool

print(f"Variant: {ANN_VARIANT} -> dataset='{DATASET_NAME}', videos dir='{VIDEO_DIR}'")
print(f"Videos in sta_uids.txt: {len(uids_all)}")
print(f"Selected {len(picked)} video(s) for mode='{EXTRACTION_MODE}'")

# ------------- Preflight -------------
if not which_or_msg("ffmpeg"):
    raise SystemExit("Install ffmpeg first.")
if DOWNLOAD_MISSING and not which_or_msg("ego4d"):
    print("WARNING: ego4d CLI not found; auto-download disabled.")

# ------------- Main loop -------------
def append_done(path, uids):
    if not uids: return
    with open(path,"a") as f:
        for u in uids: f.write(u+"\n")

total_requested, total_extracted = 0, 0
rows, processed_success, issues = [], [], []
outer_t0 = time.time()

for idx, uid in enumerate(picked, 1):
    print(f"\n[{idx}/{len(picked)}] {uid}")
    vpath = os.path.join(VIDEO_DIR, f"{uid}.mp4")
    out_dir = os.path.join(OUTPUT_BASE_DIR, uid)
    os.makedirs(out_dir, exist_ok=True)

    # download if needed (from the chosen dataset)
    dl_secs, dl_note = 0.0, "present"
    if DOWNLOAD_MISSING and not os.path.exists(vpath):
        ok, dl_secs, dl_note = download_one_video_if_needed(uid, EGO4D_ROOT, VERSION, DATASET_NAME, VIDEO_DIR,
                                                            timeout_secs=DOWNLOAD_TIMEOUT_SECS, aws_profile=AWS_PROFILE)
        if not ok:
            print("  Skipping due to download issue.")
            issues.append((uid, "download_failed")); continue
    if not os.path.exists(vpath):
        print(f"  WARNING: video not found at {vpath}. Skipping.")
        issues.append((uid, "video_missing")); continue

    # probe info
    vinfo = ffprobe_video_info(vpath)
    total_frames_video = vinfo["nb_frames"] if vinfo["nb_frames"] is not None else 0
    w, h, vsize = vinfo["width"], vinfo["height"], vinfo["size_bytes"]
    print(f"  Video info: {w}x{h}, {format_size(vsize)}, total_frames≈{total_frames_video if total_frames_video else 'unknown'}")

    # decide requested frames
    if EXTRACTION_MODE == "single":
        req_frames = [int(FRAME_NUMBER_TO_EXTRACT)]
    elif EXTRACTION_MODE == "first_n":
        req_frames = list(range(1, int(NUM_FRAMES_TO_EXTRACT)+1))
    elif EXTRACTION_MODE == "range":
        if END_FRAME < START_FRAME:
            print("  ERROR: END_FRAME < START_FRAME; skipping.")
            issues.append((uid,"bad_range")); continue
        req_frames = list(range(int(START_FRAME), int(END_FRAME)+1))
    elif EXTRACTION_MODE == "list":
        req_frames = [int(x) for x in FRAME_LIST_TO_EXTRACT]
    elif EXTRACTION_MODE == "from_lists":
        fpath = os.path.join(FRAME_LISTS_DIR, f"{uid}_frames.txt")
        if not os.path.exists(fpath):
            print("  No frame list found; skipping.")
            issues.append((uid, "no_frame_list")); continue
        with open(fpath,"r") as f:
            req_frames = [int(x.strip()) for x in f if x.strip()]
    elif EXTRACTION_MODE == "all":
        req_frames = None
    else:
        print(f"  ERROR: Unknown EXTRACTION_MODE '{EXTRACTION_MODE}'.")
        issues.append((uid, "unknown_mode")); continue

    # extract
    if EXTRACTION_MODE == "first_n":
        new_count, ex_secs = run_ffmpeg_first_n(vpath, int(NUM_FRAMES_TO_EXTRACT), out_dir,
                                                timeout_secs=FFMPEG_TIMEOUT_SECS)
        requested_ct = len(req_frames)
    elif EXTRACTION_MODE == "all":
        new_count, ex_secs = run_ffmpeg_all_frames(vpath, out_dir, timeout_secs=FFMPEG_TIMEOUT_SECS)
        requested_ct = total_frames_video if total_frames_video else 0
    else:
        new_count, ex_secs = run_ffmpeg_select(vpath, req_frames, out_dir,
                                               chunk_size=CHUNK_SIZE, timeout_secs=FFMPEG_TIMEOUT_SECS)
        requested_ct = len(req_frames)

    imgs_now = len(list_existing_jpgs(out_dir))
    total_requested += requested_ct
    total_extracted += new_count

    print(f"  Requested: {requested_ct} | New extracted: {new_count} | Total JPGs now: {imgs_now}")
    if total_frames_video:
        print(f"  {imgs_now}/{total_frames_video} total frames for this video extracted")
    else:
        print(f"  {imgs_now}/(unknown total) frames extracted")
    print(f"  Timing: download {dl_secs:.1f}s | extract {ex_secs:.1f}s")

    # optional delete source mp4
    if DELETE_VIDEO_AFTER:
        try:
            os.remove(vpath)
            print("  Source video deleted to free space.")
        except Exception as e:
            print(f"  Could not delete video: {e}")
    else:
        print("  Keeping source video (DELETE_VIDEO_AFTER=False).")

    cumulative = time.time() - outer_t0
    rows.append((uid, requested_ct, new_count, imgs_now, total_frames_video, dl_secs, ex_secs, f"{cumulative:.1f}s"))
    processed_success.append(uid)

# mark done & summary
with open(PROCESSED_LOG,"a") as f:
    for u in processed_success:
        f.write(u+"\n")

outer_t1 = time.time()
print("\n========== SUMMARY ==========")
print(f"Variant: {ANN_VARIANT} (dataset={DATASET_NAME})")
print(f"Mode: {EXTRACTION_MODE}")
print(f"Videos processed: {len(rows)} / {len(picked)} selected")
print(f"Frames requested (sum): {total_requested}")
print(f"Frames extracted (new this run): {total_extracted}")
print(f"Total wall time: {timedelta(seconds=int(outer_t1-outer_t0))}")

if rows:
    print("\n[uid | req | new | imgs_now | total_frames | download_s | extract_s | cumulative]")
    for uid, req, new, imgs, tf, dls, exs, cum in rows[:20]:
        tf_disp = f"{tf}" if tf not in (None, 0) else "unknown"
        print(f"{uid} | {req:4d} | {new:4d} | {imgs:7d} | {tf_disp:12} | {dls:10.1f} | {exs:9.1f} | {cum}")

size_bytes, img_count = get_folder_info(OUTPUT_BASE_DIR)
print(f"\nOutput frames root: {OUTPUT_BASE_DIR}")
print(f"  Total size: {format_size(size_bytes)}")
print(f"  Total images: {img_count}")

print(f"\nProcessed log updated: {PROCESSED_LOG}")
print("================================")

Variant: 540 -> dataset='video_540ss', videos dir='/content/drive/MyDrive/ego4d_data/v2/video_540ss'
Videos in sta_uids.txt: 1311
Selected 2 video(s) for mode='first_n'

[1/2] 002d2729-df71-438d-8396-5895b349e8fd
  Video info: 720x540, 554.02 MB, total_frames≈107143
  Requested: 200 | New extracted: 200 | Total JPGs now: 200
  200/107143 total frames for this video extracted
  Timing: download 11.4s | extract 3.9s
  Keeping source video (DELETE_VIDEO_AFTER=False).

[2/2] 0031d268-818c-4ec4-a804-935be610a61a
  Video info: 720x540, 362.30 MB, total_frames≈59638
  Requested: 200 | New extracted: 200 | Total JPGs now: 200
  200/59638 total frames for this video extracted
  Timing: download 10.7s | extract 4.4s
  Keeping source video (DELETE_VIDEO_AFTER=False).

========== SUMMARY ==========
Variant: 540 (dataset=video_540ss)
Mode: first_n
Videos processed: 2 / 2 selected
Frames requested (sum): 400
Frames extracted (new this run): 400
Total wall time: 0:00:30

[uid | req | new | imgs_now | total_frames | download_s | extract_s | cumulative]
002d2729-df71-438d-8396-5895b349e8fd |  200 |  200 |     200 | 107143       |       11.4 |       3.9 | 15.4s
0031d268-818c-4ec4-a804-935be610a61a |  200 |  200 |     200 | 59638        |       10.7 |       4.4 | 30.8s

Output frames root: /content/drive/MyDrive/ego4d_data/v2/extracted_frames
  Total size: 8.92 MB
  Total images: 800

Processed log updated: /content/drive/MyDrive/ego4d_data/v2/processed_uids_540.txt
================================

## History Cleanup: remove awscliv2.zip (optional)
This rewrites repo history to drop the large awscliv2.zip blobs.
- Runs on /content for speed.
- Force-push affects all collaborators; ensure you are the only active pusher.
- After success, consider recloning locally to avoid dangling objects.

In [ ]:
%%bash -s "$WORKDIR"\nset -euo pipefail\nWORKDIR="$1"\nif [ -z "$WORKDIR" ]; then echo "Set WORKDIR earlier in the notebook." >&2; exit 1; fi\norigin=$(git -C "$WORKDIR" config --get remote.origin.url)\nbranch=$(git -C "$WORKDIR" rev-parse --abbrev-ref HEAD)\nmirror=/content/egolite_cleanup.git\npython3 -m pip -q install git-filter-repo\nrm -rf "$mirror"\ngit clone --mirror "$origin" "$mirror"\ncd "$mirror"\ngit filter-repo --invert-paths --path awscliv2.zip --force\ngit count-objects -vH\necho Origin: $origin\necho Branch: $branch\necho 'Review above size. If okay, remove # below to force-push:'
# git push --force --prune\n

# Build parent-video uid file

In [27]:
# ==========================================
# Build parent-video uid file for the clips you need, then print the download cmd
# ==========================================
import os, csv, json

EGO4D_ROOT = "/content/drive/MyDrive/ego4d_data"
VERSION    = "v2"

STA_CLIP_UIDS_FILE   = os.path.join(EGO4D_ROOT, "sta_clip_uids.txt")  # produced by your frame-list builder
CLIPS_MANIFEST       = os.path.join(EGO4D_ROOT, VERSION, "clips", "manifest.csv")
ANN_540_DIR          = os.path.join(EGO4D_ROOT, VERSION, "annotations_540ss")
TRAIN_JSON           = os.path.join(ANN_540_DIR, "fho_sta_train_height-540.json")
VAL_JSON             = os.path.join(ANN_540_DIR, "fho_sta_val_height-540.json")

OUT_PARENT_VIDS_FILE = os.path.join(EGO4D_ROOT, "clip_parent_video_uids.txt")

# 1) Load requested clip_uids
if not os.path.exists(STA_CLIP_UIDS_FILE):
    raise SystemExit(f"Missing {STA_CLIP_UIDS_FILE}. Build it with the frame-list generator first.")
clip_uids = [ln.strip() for ln in open(STA_CLIP_UIDS_FILE) if ln.strip()]
print(f"Clip UIDs to cover: {len(clip_uids)}")

# 2) Try to map via manifest.csv first
manifest_map = {}
if os.path.exists(CLIPS_MANIFEST):
    with open(CLIPS_MANIFEST, newline="") as f:
        R = csv.DictReader(f)
        for row in R:
            cu = row.get("exported_clip_uid") or row.get("file_uid")
            if not cu:
                continue
            pvu = row.get("parent_video_uid")
            if pvu:
                manifest_map[cu] = pvu
print(f"Manifest rows: {len(manifest_map)}")

# 3) Fallback to 540-STA JSONs for any clips not found in manifest
def _load_json_list(p):
    if not os.path.exists(p): return []
    data = json.load(open(p,'r'))
    if isinstance(data, dict) and "annotations" in data:
        return data["annotations"]
    if isinstance(data, list):
        return data
    if isinstance(data, dict) and "data" in data and isinstance(data["data"], list):
        return data["data"]
    return []

missing = set(clip_uids) - set(manifest_map.keys())
json_map = {}
if missing:
    train = _load_json_list(TRAIN_JSON)
    val   = _load_json_list(VAL_JSON)
    for r in train + val:
        cu = r.get("clip_uid")
        vu = r.get("video_uid")
        if cu and vu and cu in missing and cu not in json_map:
            json_map[cu] = vu
print(f"Mapped via STA JSONs: {len(json_map)}")

# 4) Merge maps
final_map = {}
for cu in clip_uids:
    vu = manifest_map.get(cu) or json_map.get(cu)
    if vu:
        final_map[cu] = vu

unmapped = [cu for cu in clip_uids if cu not in final_map]
print(f"Total mapped clip_uids → parent_video_uids: {len(final_map)}/{len(clip_uids)}")
if unmapped:
    print(f"WARNING: {len(unmapped)} clip(s) not found in manifest or JSONs. Example:", unmapped[:10])

# 5) Write unique parent video list
parent_videos = sorted(set(final_map.values()))
with open(OUT_PARENT_VIDS_FILE, "w") as f:
    f.write("\n".join(parent_videos))
print(f"\nWrote {len(parent_videos)} parent video_uids → {OUT_PARENT_VIDS_FILE}")

# 6) Show download command you should run next
print("\nRun this to download ONLY the clips you need:")
print(f"!ego4d --output_directory {EGO4D_ROOT} "
      f"--datasets clips --version {VERSION} "
      f"--video_uid_file {OUT_PARENT_VIDS_FILE} -y")

Clip UIDs to cover: 2324
Manifest rows: 15133
Mapped via STA JSONs: 0
Total mapped clip_uids → parent_video_uids: 2324/2324

Wrote 1311 parent video_uids → /content/drive/MyDrive/ego4d_data/clip_parent_video_uids.txt

Run this to download ONLY the clips you need:
!ego4d --output_directory /content/drive/MyDrive/ego4d_data --datasets clips --version v2 --video_uid_file /content/drive/MyDrive/ego4d_data/clip_parent_video_uids.txt -y

# The most perfect one

In [44]:
# ==============================================
# Ego4D — FINAL single cell (video_540 OR clip_540) — UPDATED
# Uses existing UID list + *_frames.txt (NO JSON reading for extraction)
# Adds correct clips download via parent video_uids file.
#
# SOURCE_KIND:
#   - "video_540" -> dataset: video_540ss   (frame files: <video_uid>_frames.txt)
#   - "clip_540"  -> dataset: clips_540ss   (frame files: <clip_uid>_clip_frames.txt, 30 FPS)
#
# Modes: 'from_lists' | 'first_n' | 'all'
# Parallel download + parallel extraction + optional batch download
# ==============================================
import os, subprocess, time, math, json, csv, shutil, random
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import timedelta
from tqdm.auto import tqdm

# ---------------------- USER CONFIG ----------------------
EGO4D_ROOT   = "/content/drive/MyDrive/ego4d_data"
VERSION      = "v2"

# Choose source:
#  - "video_540" -> downscaled canonical videos (dataset: video_540ss), video-frame indices
#  - "clip_540"  -> downscaled canonical clips  (dataset: clips_540ss), clip-frame indices @ 30 FPS
SOURCE_KIND  = "clip_540"      # <<< "video_540" or "clip_540"

# Extraction mode:
EXTRACTION_MODE = "from_lists"  # <<< 'from_lists' | 'first_n' | 'all'
NUM_FRAMES_TO_EXTRACT = 200     # used only if EXTRACTION_MODE == 'first_n'

# Selection controls:
NUM_ITEMS_TO_PROCESS = 4        # e.g., 50  (None = all)
SPECIFIC_IDS = [                # Optional: list of IDs (video_uids or clip_uids depending on SOURCE_KIND)
    # "002e11bc-deef-45f7-9af8-59421a606d69",
]

# Download + extraction controls
DOWNLOAD_MISSING           = True
DELETE_MEDIA_AFTER         = False         # delete .mp4 after each successful extraction
USE_PARALLEL_DOWNLOADS     = True
USE_PARALLEL_EXTRACTION    = True
BATCH_DOWNLOAD             = True          # use uid_file to reduce CLI overhead
BATCH_CHUNK_SIZE           = 300

N_DOWNLOAD_WORKERS         = 4
N_EXTRACT_WORKERS          = 2
FFMPEG_TIMEOUT_SECS        = 1800
DOWNLOAD_TIMEOUT_SECS      = 3600
CHUNK_SIZE_FRAMES_SELECT   = 800           # indices per ffmpeg call
PRINT_PER_ITEM_INFO        = True

# ---------------------- PATHS ----------------------
if SOURCE_KIND == "video_540":
    DATASET          = "video_540ss"
    MEDIA_DIR        = f"{EGO4D_ROOT}/{VERSION}/video_540ss"
    UID_LIST_FILE    = f"{EGO4D_ROOT}/sta_uids.txt"                       # video_uids
    FRAME_LISTS_DIR  = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists/videos"   # <video_uid>_frames.txt
    FRAME_FILE_TPL   = "{uid}_frames.txt"
    PROCESSED_LOG    = f"{EGO4D_ROOT}/{VERSION}/processed_uids_video540.txt"
    UID_FLAG_SINGLE  = "--video_uids"
    UID_FLAG_FILE    = "--video_uid_file"
elif SOURCE_KIND == "clip_540":
    DATASET          = "clips"
    MEDIA_DIR        = f"{EGO4D_ROOT}/{VERSION}/clips_540ss"
    UID_LIST_FILE    = f"{EGO4D_ROOT}/sta_clip_uids.txt"                  # clip_uids
    FRAME_LISTS_DIR  = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists/clips"    # <clip_uid>_clip_frames.txt
    FRAME_FILE_TPL   = "{uid}_clip_frames.txt"
    PROCESSED_LOG    = f"{EGO4D_ROOT}/{VERSION}/processed_uids_clip540.txt"
    # IMPORTANT: clips must be filtered by parent video_uids
    PARENT_VID_FILE  = f"{EGO4D_ROOT}/clip_parent_video_uids.txt"
    CLIPS_MANIFEST   = f"{EGO4D_ROOT}/{VERSION}/clips/manifest.csv"
    ANN_540_DIR      = f"{EGO4D_ROOT}/{VERSION}/annotations_540ss"
    TRAIN_JSON       = os.path.join(ANN_540_DIR, "fho_sta_train_height-540.json")
    VAL_JSON         = os.path.join(ANN_540_DIR, "fho_sta_val_height-540.json")
else:
    raise SystemExit("SOURCE_KIND must be 'video_540' or 'clip_540'")

FRAMES_DRIVE_ROOT = f"{EGO4D_ROOT}/{VERSION}/extracted_frames"  # frames/<id>/*.jpg
FRAMES_TMP_ROOT   = "/content/tmp_frames"                       # local scratch (fast)

# ---------------------- PREP ----------------------
os.makedirs(MEDIA_DIR, exist_ok=True)
os.makedirs(FRAME_LISTS_DIR, exist_ok=True)
os.makedirs(FRAMES_DRIVE_ROOT, exist_ok=True)
os.makedirs(FRAMES_TMP_ROOT, exist_ok=True)

def which(cmd: str) -> bool:
    import shutil as _sh
    return _sh.which(cmd) is not None

def format_size(n):
    if n is None: return "N/A"
    for u in ["B","KB","MB","GB","TB"]:
        if n < 1024: return f"{n:.2f} {u}"
        n /= 1024
    return f"{n:.2f} PB"

def list_existing_jpgs(folder):
    return [f for f in os.listdir(folder) if f.lower().endswith(".jpg")] if os.path.isdir(folder) else []

def build_eqn_select(frames):
    return "+".join([f"eq(n\\,{int(n)})" for n in frames])

def ffprobe_media_info(path):
    info = {"nb_frames": None, "duration": None, "r_frame_rate": None,
            "width": None, "height": None, "size_bytes": None}
    if not os.path.exists(path):
        return info
    try:
        info["size_bytes"] = os.path.getsize(path)
    except Exception:
        pass
    cmd = ["ffprobe","-v","error","-select_streams","v:0",
           "-show_entries","stream=nb_frames,r_frame_rate,width,height:format=duration",
           "-of","json", path]
    try:
        res = subprocess.run(cmd, text=True, capture_output=True, check=True)
        data = json.loads(res.stdout or "{}")
        if "streams" in data and data["streams"]:
            s = data["streams"][0]
            if s.get("nb_frames") is not None:
                try: info["nb_frames"] = int(s["nb_frames"])
                except: pass
            info["r_frame_rate"] = s.get("r_frame_rate")
            info["width"]  = int(s["width"])  if s.get("width")  else None
            info["height"] = int(s["height"]) if s.get("height") else None
        if "format" in data and data["format"].get("duration") is not None:
            try: info["duration"] = float(data["format"]["duration"])
            except: pass
        if info["nb_frames"] in (None, 0):
            fps = None
            if info["r_frame_rate"]:
                try:
                    a,b = info["r_frame_rate"].split("/")
                    a = float(a); b = float(b) if float(b) != 0 else 1.0
                    fps = a/b
                except: pass
            if fps and info["duration"]:
                info["nb_frames"] = int(fps * info["duration"])
    except:
        pass
    return info

# ---------------------- FFMPEG RUNNERS ----------------------
def run_ffmpeg_select(media_path, frames, out_dir, start_number=None, chunk=800, timeout=1800):
    os.makedirs(out_dir, exist_ok=True)
    frames = sorted(set(int(x) for x in frames))
    if not frames: return 0, 0.0
    before = len(list_existing_jpgs(out_dir))
    if start_number is None: start_number = before
    t0 = time.time()
    for i in range(0, len(frames), chunk):
        piece = frames[i:i+chunk]
        vf = f"select='{build_eqn_select(piece)}',setpts=N/FRAME_RATE/TB"
        cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
               "-i", media_path, "-vf", vf, "-vsync","0",
               "-start_number", str(start_number),
               os.path.join(out_dir, "%07d.jpg")]
        subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
        start_number += len(piece)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

def run_ffmpeg_first_n(media_path, n, out_dir, timeout=1800):
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
           "-i", media_path, "-vframes", str(int(n)),
           os.path.join(out_dir, "%07d.jpg")]
    t0 = time.time()
    subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

def run_ffmpeg_all(media_path, out_dir, timeout=1800):
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
           "-i", media_path, "-vsync","0",
           os.path.join(out_dir, "%07d.jpg")]
    t0 = time.time()
    subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

# ---------------------- DOWNLOAD HELPERS ----------------------
def _load_json_list(p):
    if not os.path.exists(p): return []
    data = json.load(open(p,'r'))
    if isinstance(data, dict) and "annotations" in data:
        return data["annotations"]
    if isinstance(data, list):
        return data
    if isinstance(data, dict) and "data" in data and isinstance(data["data"], list):
        return data["data"]
    return []

def _build_parent_video_file_for_clips(clip_ids_subset=None):
    """
    Build / reuse the parent-video list file for clips:
      - Prefer manifest.csv mapping (exported_clip_uid -> parent_video_uid)
      - Fallback to STA-540 JSONs (clip_uid -> video_uid)
    If clip_ids_subset is provided, only map those clips; else map all from sta_clip_uids.txt.
    Returns the filepath to a uid file listing parent video_uids.
    """
    sta_clip_uids_file = os.path.join(EGO4D_ROOT, "sta_clip_uids.txt")
    if clip_ids_subset is None:
        if not os.path.exists(sta_clip_uids_file):
            raise SystemExit(f"Missing {sta_clip_uids_file}. Build frame lists first.")
        clip_uids = [ln.strip() for ln in open(sta_clip_uids_file) if ln.strip()]
    else:
        clip_uids = list(dict.fromkeys([c for c in clip_ids_subset if c]))

    manifest_map = {}
    if os.path.exists(CLIPS_MANIFEST):
        with open(CLIPS_MANIFEST, newline="") as f:
            R = csv.DictReader(f)
            for row in R:
                cu = row.get("exported_clip_uid") or row.get("file_uid")
                pvu = row.get("parent_video_uid")
                if cu and pvu:
                    manifest_map[cu] = pvu

    missing = set(clip_uids) - set(manifest_map.keys())
    json_map = {}
    if missing:
        train = _load_json_list(TRAIN_JSON)
        val   = _load_json_list(VAL_JSON)
        for r in train + val:
            cu = r.get("clip_uid"); vu = r.get("video_uid")
            if cu and vu and cu in missing and cu not in json_map:
                json_map[cu] = vu

    final_map = {}
    for cu in clip_uids:
        vu = manifest_map.get(cu) or json_map.get(cu)
        if vu: final_map[cu] = vu

    parent_videos = sorted(set(final_map.values()))
    if clip_ids_subset is None:
        out_file = PARENT_VID_FILE
    else:
        # temp file for a specific subset
        rnd = random.randint(10**6, 10**9-1)
        out_file = f"/content/clip_parent_vuids_subset_{rnd}.txt"
    with open(out_file, "w") as f:
        f.write("\n".join(parent_videos))
    return out_file, len(clip_uids), len(parent_videos)

def download_one(uid, timeout=3600, aws_profile=None):
    path = os.path.join(MEDIA_DIR, f"{uid}.mp4")
    if os.path.exists(path):
        return uid, True, 0.0, "present"
    if not which("ego4d"):
        return uid, False, 0.0, "ego4d CLI not found"

    # For video_540 we can directly filter by video uid
    cmd = ["ego4d","--output_directory", EGO4D_ROOT, "--datasets", DATASET,
           "--version", VERSION]
    if SOURCE_KIND == "video_540":
        cmd += [ "--video_uids", uid ]
    else:
        # For clips we CANNOT pass clip uid; this path won't be used in batch mode.
        # We keep it for completeness, but we recommend BATCH_DOWNLOAD for clips.
        return uid, False, 0.0, "use_batch_parent_videos_for_clips"
    cmd += ["-y"]
    if aws_profile:
        cmd += ["--aws_profile_name", aws_profile]

    t0 = time.time()
    try:
        subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
        ok = os.path.exists(path); t1 = time.time()
        return uid, ok, (t1-t0), ("downloaded" if ok else "missing_after_dl")
    except subprocess.CalledProcessError:
        return uid, False, time.time()-t0, "ego4d failed"
    except subprocess.TimeoutExpired:
        return uid, False, time.time()-t0, "timeout"

def batch_download_ids(ids, chunk_size=100, timeout=3600, aws_profile=None):
    if not which("ego4d"):
        print("  !!! ego4d CLI not found; cannot batch download.")
        return 0, len(ids)

    if SOURCE_KIND == "video_540":
        # Batch by video_uids normally
        ok_total = 0
        for i in range(0, len(ids), chunk_size):
            chunk = ids[i:i+chunk_size]
            tmpfile = f"/content/ego4d_vids_{i//chunk_size}.txt"
            with open(tmpfile,"w") as f:
                f.write("\n".join(chunk))
            cmd = ["ego4d","--output_directory", EGO4D_ROOT, "--datasets", DATASET,
                   "--version", VERSION, "--video_uid_file", tmpfile, "-y"]
            if aws_profile:
                cmd += ["--aws_profile_name", aws_profile]
            try:
                subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
            except subprocess.CalledProcessError:
                pass
            except subprocess.TimeoutExpired:
                pass
            ok_total += sum(os.path.exists(os.path.join(MEDIA_DIR, f"{u}.mp4")) for u in chunk)
            try: os.remove(tmpfile)
            except: pass
        return ok_total, len(ids)

    else:
        # SOURCE_KIND == "clip_540"
        # We must map our selected clip IDs to their parent video_uids and pass a *video_uid_file* to dataset=clips
        parent_file, total_clips, total_parents = _build_parent_video_file_for_clips(ids if ids else None)
        print(f"[clips] Prepared parent video list from {total_clips} clip id(s) → {total_parents} parent video(s): {parent_file}")
        cmd = ["ego4d","--output_directory", EGO4D_ROOT, "--datasets", "clips",
               "--version", VERSION, "--video_uid_file", parent_file, "-y"]
        if aws_profile:
            cmd += ["--aws_profile_name", aws_profile]
        try:
            subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
        except subprocess.CalledProcessError:
            pass
        except subprocess.TimeoutExpired:
            pass
        # We can't easily count ok_total here because multiple clips per parent video are downloaded.
        # We'll check presence downstream per id.
        ok_total = sum(os.path.exists(os.path.join(MEDIA_DIR, f"{u}.mp4")) for u in ids) if ids else 0
        return ok_total, (len(ids) if ids else 0)

# ---------------------- LOAD/CHOOSE IDS ----------------------
def load_all_ids_from_file(path):
    if not os.path.exists(path):
        raise SystemExit(f"UID list not found: {path}")
    with open(path,"r") as f:
        return [ln.strip() for ln in f if ln.strip()]

def choose_ids():
    if SPECIFIC_IDS:
        seen, base = set(), []
        for u in SPECIFIC_IDS:
            if u not in seen:
                base.append(u); seen.add(u)
    else:
        base = load_all_ids_from_file(UID_LIST_FILE)

    if EXTRACTION_MODE == "from_lists":
        filtered = []
        for u in base:
            fpath = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=u))
            if os.path.exists(fpath):
                filtered.append(u)
        if len(filtered) != len(base):
            print(f"NOTE: {len(base)-len(filtered)} id(s) missing frame file → skipped.")
        base = filtered

    if NUM_ITEMS_TO_PROCESS:
        base = base[:NUM_ITEMS_TO_PROCESS]
    return base

ids_all = choose_ids()

print(f"Source: {SOURCE_KIND} → dataset='{DATASET}', media dir='{MEDIA_DIR}'")
print(f"Selected {len(ids_all)} item(s) for mode='{EXTRACTION_MODE}'")
if SPECIFIC_IDS:
    print(f"Using SPECIFIC_IDS (length={len(SPECIFIC_IDS)}).")

# ---------------------- PREFLIGHT ----------------------
if not which("ffmpeg"):
    raise SystemExit("Install ffmpeg first (e.g., `!apt-get -y install ffmpeg`).")
if DOWNLOAD_MISSING and not which("ego4d"):
    print("WARNING: ego4d CLI not found; downloads will be skipped.")

# ---------------------- DOWNLOAD PHASE ----------------------
outer_t0 = time.time()
downloaded_ct = 0

if DOWNLOAD_MISSING and ids_all:
    to_get = [u for u in ids_all if not os.path.exists(os.path.join(MEDIA_DIR, f"{u}.mp4"))]
    print(f"Need to download: {len(to_get)} file(s).")

    if BATCH_DOWNLOAD and to_get:
        ok_ct, total_ct = batch_download_ids(to_get, chunk_size=BATCH_CHUNK_SIZE, timeout=DOWNLOAD_TIMEOUT_SECS)
        downloaded_ct += ok_ct
        if SOURCE_KIND == "clip_540":
            print(f"[clips] Batch download initiated via parent video_uids (see console for ego4d logs).")
        print(f"Batch 'ok' presence (post-check) {ok_ct}/{total_ct}.")

    elif USE_PARALLEL_DOWNLOADS and to_get:
        print(f"Parallel downloading with {N_DOWNLOAD_WORKERS} workers ...")
        with ThreadPoolExecutor(max_workers=max(1, int(N_DOWNLOAD_WORKERS))) as ex:
            futures = [ex.submit(download_one, u, DOWNLOAD_TIMEOUT_SECS, None) for u in to_get]
            for fut in tqdm(as_completed(futures), total=len(futures)):
                uid, ok, secs, note = fut.result()
                downloaded_ct += int(ok)
                if PRINT_PER_ITEM_INFO:
                    print(f"  {uid} → {note} in {secs:.1f}s")
        print(f"Downloaded (parallel): {downloaded_ct}/{len(to_get)} new files.")
else:
    print("Skipping downloads.")

# ---------------------- FRAME LIST LOADER ----------------------
def load_frames_for(uid):
    p = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
    if not os.path.exists(p): return []
    with open(p) as f:
        return [int(x.strip()) for x in f if x.strip()]

# ---------------------- EXTRACTION ----------------------
def move_tmp_to_drive(out_tmp, out_final):
    if os.path.exists(out_final):
        for f in os.listdir(out_tmp):
            src = os.path.join(out_tmp, f)
            dst = os.path.join(out_final, f)
            if not os.path.exists(dst):
                shutil.move(src, dst)
        shutil.rmtree(out_tmp, ignore_errors=True)
    else:
        shutil.move(out_tmp, out_final)

def extract_one(uid):
    media_path = os.path.join(MEDIA_DIR, f"{uid}.mp4")
    if not os.path.exists(media_path):
        return uid, 0, 0.0, 0, "media_missing"

    info = ffprobe_media_info(media_path)
    total_frames_media = info["nb_frames"] if info["nb_frames"] else 0
    w, h, msize = info["width"], info["height"], info["size_bytes"]

    out_tmp   = os.path.join(FRAMES_TMP_ROOT, uid)    # local scratch
    out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)  # Drive
    os.makedirs(out_tmp, exist_ok=True)

    try:
        if EXTRACTION_MODE == "all":
            new_count, secs = run_ffmpeg_all(media_path, out_tmp, timeout=FFMPEG_TIMEOUT_SECS)
            requested_ct = total_frames_media if total_frames_media else 0
        elif EXTRACTION_MODE == "first_n":
            new_count, secs = run_ffmpeg_first_n(media_path, NUM_FRAMES_TO_EXTRACT, out_tmp,
                                                 timeout=FFMPEG_TIMEOUT_SECS)
            requested_ct = NUM_FRAMES_TO_EXTRACT
        elif EXTRACTION_MODE == "from_lists":
            frames = load_frames_for(uid)
            if not frames:
                return uid, 0, 0.0, total_frames_media, "no_frame_list"
            new_count, secs = run_ffmpeg_select(media_path, frames, out_tmp,
                                                chunk=CHUNK_SIZE_FRAMES_SELECT,
                                                timeout=FFMPEG_TIMEOUT_SECS)
            requested_ct = len(frames)
        else:
            return uid, 0, 0.0, total_frames_media, "bad_mode"

        move_tmp_to_drive(out_tmp, out_final)

        if DELETE_MEDIA_AFTER:
            try: os.remove(media_path)
            except: pass

        imgs_now = len(list_existing_jpgs(out_final))
        if PRINT_PER_ITEM_INFO:
            print(f"  {uid}: {w}x{h}, {format_size(msize)}, total≈{total_frames_media} | requested={requested_ct} new={new_count} now={imgs_now}")
        return uid, new_count, secs, total_frames_media, "ok"

    except subprocess.CalledProcessError:
        return uid, 0, 0.0, total_frames_media, "ffmpeg_failed"
    except Exception as e:
        return uid, 0, 0.0, total_frames_media, f"error:{str(e)[:80]}"

# ---------------------- RUN EXTRACTION ----------------------
rows = []
total_requested, total_extracted = 0, 0
if USE_PARALLEL_EXTRACTION and ids_all:
    print(f"Parallel extraction with {N_EXTRACT_WORKERS} workers ...")
    with ThreadPoolExecutor(max_workers=max(1, int(N_EXTRACT_WORKERS))) as ex:
        futures = [ex.submit(extract_one, u) for u in ids_all]
        for fut in tqdm(as_completed(futures), total=len(futures)):
            uid, new_ct, secs, tf_all, note = fut.result()
            if EXTRACTION_MODE == "first_n":
                req_ct = NUM_FRAMES_TO_EXTRACT
            elif EXTRACTION_MODE == "all":
                req_ct = tf_all if tf_all else 0
            else:
                fpath = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
                req_ct = sum(1 for _ in open(fpath)) if os.path.exists(fpath) else 0

            out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)
            imgs_now = len(list_existing_jpgs(out_final)) if os.path.exists(out_final) else 0

            rows.append((uid, req_ct, new_ct, imgs_now, tf_all, 0.0, secs, note))
            total_requested += req_ct
            total_extracted += new_ct
else:
    print("Serial extraction ...")
    for uid in tqdm(ids_all):
        uid, new_ct, secs, tf_all, note = extract_one(uid)
        if EXTRACTION_MODE == "first_n":
            req_ct = NUM_FRAMES_TO_EXTRACT
        elif EXTRACTION_MODE == "all":
            req_ct = tf_all if tf_all else 0
        else:
            fpath = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
            req_ct = sum(1 for _ in open(fpath)) if os.path.exists(fpath) else 0
        out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)
        imgs_now = len(list_existing_jpgs(out_final)) if os.path.exists(out_final) else 0
        rows.append((uid, req_ct, new_ct, imgs_now, tf_all, 0.0, secs, note))
        total_requested += req_ct
        total_extracted += new_ct

# ---------------------- MARK DONE & SUMMARY ----------------------
with open(PROCESSED_LOG,"a") as f:
    for uid, *_ in rows:
        f.write(uid + "\n")

outer_t1 = time.time()
print("\n========== SUMMARY ==========")
print(f"Source: {SOURCE_KIND} (dataset={DATASET})")
print(f"Mode: {EXTRACTION_MODE}")
print(f"Items processed: {len(rows)} / {len(ids_all)} selected")
print(f"Frames requested (sum): {total_requested}")
print(f"Frames extracted (new this run): {total_extracted}")
print(f"Total wall time: {timedelta(seconds=int(outer_t1-outer_t0))}")

if rows:
    print("\n[uid | req | new | imgs_now | total_frames | download_s | extract_s | note]")
    for uid, req, new, imgs, tf, dls, exs, note in rows[:40]:
        tf_disp = f"{tf}" if tf not in (None, 0) else "unknown"
        print(f"{uid} | {req:4d} | {new:4d} | {imgs:7d} | {tf_disp:12} | {dls:10.1f} | {exs:9.1f} | {note}")

print(f"\nFrames on Drive: {FRAMES_DRIVE_ROOT}")
print(f"Processed log updated: {PROCESSED_LOG}")
print("=============================================")

Source: clip_540 → dataset='clips', media dir='/content/drive/MyDrive/ego4d_data/v2/clips_540ss'
Selected 4 item(s) for mode='from_lists'
Need to download: 4 file(s).
[clips] Prepared parent video list from 4 clip id(s) → 4 parent video(s): /content/clip_parent_vuids_subset_852495065.txt
[clips] Batch download initiated via parent video_uids (see console for ego4d logs).
Batch 'ok' presence (post-check) 0/4.
Parallel extraction with 2 workers ...

  0%|          | 0/4 [00:00<?, ?it/s]

========== SUMMARY ==========
Source: clip_540 (dataset=clips)
Mode: from_lists
Items processed: 4 / 4 selected
Frames requested (sum): 300
Frames extracted (new this run): 0
Total wall time: 0:00:03

[uid | req | new | imgs_now | total_frames | download_s | extract_s | note]
004e8f11-9d56-4208-aeaf-77b03ced000c |   35 |    0 |       0 | unknown      |        0.0 |       0.0 | media_missing
002e11bc-deef-45f7-9af8-59421a606d69 |  124 |    0 |       0 | unknown      |        0.0 |       0.0 | media_missing
005efbab-c314-48d8-8dd9-bfc1263ec5df |  100 |    0 |       0 | unknown      |        0.0 |       0.0 | media_missing
00600a90-0934-4d5f-aa9d-1cdea46ab740 |   41 |    0 |       0 | unknown      |        0.0 |       0.0 | media_missing

Frames on Drive: /content/drive/MyDrive/ego4d_data/v2/extracted_frames
Processed log updated: /content/drive/MyDrive/ego4d_data/v2/processed_uids_clip540.txt
=============================================

In [54]:
# ==============================================
# Ego4D — FINAL single cell (video_540 OR clip_540) — FIXED for "clips"
# Uses existing UID list + *_frames.txt (NO JSON reading for extraction)
# Corrects dataset name & media dir for clips, so files are found.
# ==============================================
import os, subprocess, time, json, csv, shutil, random
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import timedelta
from tqdm.auto import tqdm

# ---------------------- USER CONFIG ----------------------
EGO4D_ROOT   = "/content/drive/MyDrive/ego4d_data"
VERSION      = "v2"

# "video_540" -> dataset: video_540ss   (video-frame indices)
# "clip_540"  -> dataset: clips         (clip-frame indices @30 FPS)
SOURCE_KIND  = "clip_540"        # <<< "video_540" or "clip_540"

EXTRACTION_MODE = "from_lists"   # 'from_lists' | 'first_n' | 'all'
NUM_FRAMES_TO_EXTRACT = 200

NUM_ITEMS_TO_PROCESS = 4         # None = all
SPECIFIC_IDS = [
    # Example clip_uids when SOURCE_KIND="clip_540"
    # "002e11bc-deef-45f7-9af8-59421a606d69",
]

DOWNLOAD_MISSING        = True
DELETE_MEDIA_AFTER      = False
USE_PARALLEL_DOWNLOADS  = True
USE_PARALLEL_EXTRACTION = True
BATCH_DOWNLOAD          = True
BATCH_CHUNK_SIZE        = 300

N_DOWNLOAD_WORKERS      = 4
N_EXTRACT_WORKERS       = 2
FFMPEG_TIMEOUT_SECS     = 1800
DOWNLOAD_TIMEOUT_SECS   = 3600
CHUNK_SIZE_FRAMES_SELECT= 800
PRINT_PER_ITEM_INFO     = True

# ---------------------- PATHS ----------------------
if SOURCE_KIND == "video_540":
    DATASET          = "video_540ss"
    MEDIA_DIR        = f"{EGO4D_ROOT}/{VERSION}/video_540ss"
    UID_LIST_FILE    = f"{EGO4D_ROOT}/sta_uids.txt"
    FRAME_LISTS_DIR  = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists/videos"
    FRAME_FILE_TPL   = "{uid}_frames.txt"
    PROCESSED_LOG    = f"{EGO4D_ROOT}/{VERSION}/processed_uids_video540.txt"
    UID_FLAG_SINGLE  = "--video_uids"
    UID_FLAG_FILE    = "--video_uid_file"
elif SOURCE_KIND == "clip_540":
    # IMPORTANT: dataset is "clips", files live in .../v2/clips
    DATASET          = "clips"
    MEDIA_DIR        = f"{EGO4D_ROOT}/{VERSION}/clips"
    UID_LIST_FILE    = f"{EGO4D_ROOT}/sta_clip_uids.txt"         # clip_uids
    FRAME_LISTS_DIR  = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists/clips"
    FRAME_FILE_TPL   = "{uid}_clip_frames.txt"
    PROCESSED_LOG    = f"{EGO4D_ROOT}/{VERSION}/processed_uids_clip540.txt"
    # For downloading clips we must filter by parent video_uids:
    PARENT_VID_FILE  = f"{EGO4D_ROOT}/clip_parent_video_uids.txt"
    CLIPS_MANIFEST   = f"{EGO4D_ROOT}/{VERSION}/clips/manifest.csv"
    ANN_540_DIR      = f"{EGO4D_ROOT}/{VERSION}/annotations_540ss"
    TRAIN_JSON       = os.path.join(ANN_540_DIR, "fho_sta_train_height-540.json")
    VAL_JSON         = os.path.join(ANN_540_DIR, "fho_sta_val_height-540.json")
else:
    raise SystemExit("SOURCE_KIND must be 'video_540' or 'clip_540'")

FRAMES_DRIVE_ROOT = f"{EGO4D_ROOT}/{VERSION}/extracted_frames"
FRAMES_TMP_ROOT   = "/content/tmp_frames"

# ---------------------- PREP ----------------------
for p in (MEDIA_DIR, FRAME_LISTS_DIR, FRAMES_DRIVE_ROOT, FRAMES_TMP_ROOT):
    os.makedirs(p, exist_ok=True)

def which(cmd: str) -> bool:
    import shutil as _sh
    return _sh.which(cmd) is not None

def format_size(n):
    if n is None: return "N/A"
    for u in ["B","KB","MB","GB","TB"]:
        if n < 1024: return f"{n:.2f} {u}"
        n /= 1024
    return f"{n:.2f} PB"

def list_existing_jpgs(folder):
    return [f for f in os.listdir(folder) if f.lower().endswith(".jpg")] if os.path.isdir(folder) else []

def build_eqn_select(frames):
    return "+".join([f"eq(n\\,{int(n)})" for n in frames])

def ffprobe_media_info(path):
    info = {"nb_frames": None, "duration": None, "r_frame_rate": None,
            "width": None, "height": None, "size_bytes": None}
    if not os.path.exists(path):
        return info
    try: info["size_bytes"] = os.path.getsize(path)
    except: pass
    cmd = ["ffprobe","-v","error","-select_streams","v:0",
           "-show_entries","stream=nb_frames,r_frame_rate,width,height:format=duration",
           "-of","json", path]
    try:
        res = subprocess.run(cmd, text=True, capture_output=True, check=True)
        data = json.loads(res.stdout or "{}")
        if "streams" in data and data["streams"]:
            s = data["streams"][0]
            if s.get("nb_frames") is not None:
                try: info["nb_frames"] = int(s["nb_frames"])
                except: pass
            info["r_frame_rate"] = s.get("r_frame_rate")
            info["width"]  = int(s["width"])  if s.get("width")  else None
            info["height"] = int(s["height"]) if s.get("height") else None
        if "format" in data and data["format"].get("duration") is not None:
            try: info["duration"] = float(data["format"]["duration"])
            except: pass
        if info["nb_frames"] in (None, 0):
            fps = None
            if info["r_frame_rate"]:
                try:
                    a,b = info["r_frame_rate"].split("/")
                    a = float(a); b = float(b) if float(b) != 0 else 1.0
                    fps = a/b
                except: pass
            if fps and info["duration"]:
                info["nb_frames"] = int(fps * info["duration"])
    except: pass
    return info

# ---------------------- FFMPEG RUNNERS ----------------------
def run_ffmpeg_select(media_path, frames, out_dir, start_number=None, chunk=800, timeout=1800):
    os.makedirs(out_dir, exist_ok=True)
    frames = sorted(set(int(x) for x in frames))
    if not frames: return 0, 0.0
    before = len(list_existing_jpgs(out_dir))
    if start_number is None: start_number = before
    t0 = time.time()
    for i in range(0, len(frames), chunk):
        piece = frames[i:i+chunk]
        vf = f"select='{build_eqn_select(piece)}',setpts=N/FRAME_RATE/TB"
        cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
               "-i", media_path, "-vf", vf, "-vsync","0",
               "-start_number", str(start_number),
               os.path.join(out_dir, "%07d.jpg")]
        subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
        start_number += len(piece)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

def run_ffmpeg_first_n(media_path, n, out_dir, timeout=1800):
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
           "-i", media_path, "-vframes", str(int(n)),
           os.path.join(out_dir, "%07d.jpg")]
    t0 = time.time()
    subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

def run_ffmpeg_all(media_path, out_dir, timeout=1800):
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
           "-i", media_path, "-vsync","0",
           os.path.join(out_dir, "%07d.jpg")]
    t0 = time.time()
    subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

# ---------------------- CLIP PARENT VIDEO MAPPING ----------------------
def _load_json_list(p):
    if not os.path.exists(p): return []
    data = json.load(open(p,'r'))
    if isinstance(data, dict) and "annotations" in data: return data["annotations"]
    if isinstance(data, list): return data
    if isinstance(data, dict) and "data" in data and isinstance(data["data"], list): return data["data"]
    return []

def _build_parent_video_file_for_clips(clip_ids_subset=None):
    sta_clip_uids_file = os.path.join(EGO4D_ROOT, "sta_clip_uids.txt")
    if clip_ids_subset is None:
        if not os.path.exists(sta_clip_uids_file):
            raise SystemExit(f"Missing {sta_clip_uids_file}. Build frame lists first.")
        clip_uids = [ln.strip() for ln in open(sta_clip_uids_file) if ln.strip()]
    else:
        clip_uids = list(dict.fromkeys([c for c in clip_ids_subset if c]))

    manifest_map = {}
    if os.path.exists(CLIPS_MANIFEST):
        with open(CLIPS_MANIFEST, newline="") as f:
            for row in csv.DictReader(f):
                cu = row.get("exported_clip_uid") or row.get("file_uid")
                pvu = row.get("parent_video_uid")
                if cu and pvu:
                    manifest_map[cu] = pvu

    missing = set(clip_uids) - set(manifest_map.keys())
    json_map = {}
    if missing:
        train = _load_json_list(TRAIN_JSON)
        val   = _load_json_list(VAL_JSON)
        for r in train + val:
            cu = r.get("clip_uid"); vu = r.get("video_uid")
            if cu and vu and cu in missing and cu not in json_map:
                json_map[cu] = vu

    final_map = {}
    for cu in clip_uids:
        vu = manifest_map.get(cu) or json_map.get(cu)
        if vu: final_map[cu] = vu

    parent_videos = sorted(set(final_map.values()))
    out_file = (f"/content/clip_parent_vuids_subset_{random.randint(10**6,10**9-1)}.txt"
                if clip_ids_subset is not None else
                f"{EGO4D_ROOT}/clip_parent_video_uids.txt")
    with open(out_file, "w") as f:
        f.write("\n".join(parent_videos))
    return out_file, len(clip_uids), len(parent_videos)

# ---------------------- DOWNLOAD HELPERS ----------------------
def download_one(uid, timeout=3600, aws_profile=None):
    path = os.path.join(MEDIA_DIR, f"{uid}.mp4")
    if os.path.exists(path):
        return uid, True, 0.0, "present"
    if not which("ego4d"):
        return uid, False, 0.0, "ego4d CLI not found"

    if SOURCE_KIND == "video_540":
        cmd = ["ego4d","--output_directory", EGO4D_ROOT, "--datasets", DATASET,
               "--version", VERSION, "--video_uids", uid, "-y"]
    else:
        # For clips we should use batch (parent video file); skip single.
        return uid, False, 0.0, "use_batch_parent_videos_for_clips"

    t0 = time.time()
    try:
        subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
        ok = os.path.exists(path); t1 = time.time()
        return uid, ok, (t1-t0), ("downloaded" if ok else "missing_after_dl")
    except subprocess.CalledProcessError:
        return uid, False, time.time()-t0, "ego4d failed"
    except subprocess.TimeoutExpired:
        return uid, False, time.time()-t0, "timeout"

def batch_download_ids(ids, chunk_size=100, timeout=3600, aws_profile=None):
    if not which("ego4d"):
        print("  !!! ego4d CLI not found; cannot batch download.")
        return 0, len(ids)

    if SOURCE_KIND == "video_540":
        ok_total = 0
        for i in range(0, len(ids), chunk_size):
            chunk = ids[i:i+chunk_size]
            tmpfile = f"/content/ego4d_vids_{i//chunk_size}.txt"
            with open(tmpfile,"w") as f: f.write("\n".join(chunk))
            cmd = ["ego4d","--output_directory", EGO4D_ROOT, "--datasets", DATASET,
                   "--version", VERSION, "--video_uid_file", tmpfile, "-y"]
            if aws_profile: cmd += ["--aws_profile_name", aws_profile]
            try: subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
            except subprocess.CalledProcessError: pass
            except subprocess.TimeoutExpired: pass
            ok_total += sum(os.path.exists(os.path.join(MEDIA_DIR, f"{u}.mp4")) for u in chunk)
            try: os.remove(tmpfile)
            except: pass
        return ok_total, len(ids)

    else:
        parent_file, total_clips, total_parents = _build_parent_video_file_for_clips(ids if ids else None)
        print(f"[clips] Prepared parent video list from {total_clips} clip id(s) → {total_parents} parent video(s): {parent_file}")
        # IMPORTANT: dataset MUST be "clips" and we pass VIDEO uid file:
        cmd = ["ego4d","--output_directory", EGO4D_ROOT, "--datasets", "clips",
               "--version", VERSION, "--video_uid_file", parent_file, "-y"]
        print("[clips] Running:", " ".join(cmd))  # visibility
        if aws_profile: cmd += ["--aws_profile_name", aws_profile]
        try: subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
        except subprocess.CalledProcessError: pass
        except subprocess.TimeoutExpired: pass
        # Presence will be checked per-clip later.
        ok_total = sum(os.path.exists(os.path.join(MEDIA_DIR, f"{u}.mp4")) for u in ids) if ids else 0
        return ok_total, (len(ids) if ids else 0)

# ---------------------- LOAD/CHOOSE IDS ----------------------
def load_all_ids_from_file(path):
    if not os.path.exists(path): raise SystemExit(f"UID list not found: {path}")
    with open(path,"r") as f: return [ln.strip() for ln in f if ln.strip()]

def choose_ids():
    if SPECIFIC_IDS:
        seen, base = set(), []
        for u in SPECIFIC_IDS:
            if u not in seen:
                base.append(u); seen.add(u)
    else:
        base = load_all_ids_from_file(UID_LIST_FILE)

    if EXTRACTION_MODE == "from_lists":
        filtered = []
        for u in base:
            fpath = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=u))
            if os.path.exists(fpath): filtered.append(u)
        if len(filtered) != len(base):
            print(f"NOTE: {len(base)-len(filtered)} id(s) missing frame file → skipped.")
        base = filtered

    if NUM_ITEMS_TO_PROCESS: base = base[:NUM_ITEMS_TO_PROCESS]
    return base

ids_all = choose_ids()
print(f"Source: {SOURCE_KIND} → dataset='{DATASET}', media dir='{MEDIA_DIR}'")
print(f"Selected {len(ids_all)} item(s) for mode='{EXTRACTION_MODE}'")
if SPECIFIC_IDS: print(f"Using SPECIFIC_IDS (length={len(SPECIFIC_IDS)}).")

# ---------------------- PREFLIGHT ----------------------
if not which("ffmpeg"): raise SystemExit("Install ffmpeg first (e.g., `!apt-get -y install ffmpeg`).")
if DOWNLOAD_MISSING and not which("ego4d"):
    print("WARNING: ego4d CLI not found; downloads will be skipped.")

# ---------------------- DOWNLOAD PHASE ----------------------
outer_t0 = time.time()
downloaded_ct = 0

if DOWNLOAD_MISSING and ids_all:
    to_get = [u for u in ids_all if not os.path.exists(os.path.join(MEDIA_DIR, f"{u}.mp4"))]
    print(f"Need to download: {len(to_get)} file(s).")

    if BATCH_DOWNLOAD and to_get:
        ok_ct, total_ct = batch_download_ids(to_get, chunk_size=BATCH_CHUNK_SIZE, timeout=DOWNLOAD_TIMEOUT_SECS)
        downloaded_ct += ok_ct
        if SOURCE_KIND == "clip_540":
            print(f"[clips] Batch download invoked via parent video_uids. (See log above)")
        print(f"Batch 'ok' presence (post-check) {ok_ct}/{total_ct}.")
    elif USE_PARALLEL_DOWNLOADS and to_get and SOURCE_KIND == "video_540":
        print(f"Parallel downloading with {N_DOWNLOAD_WORKERS} workers ...")
        with ThreadPoolExecutor(max_workers=max(1, int(N_DOWNLOAD_WORKERS))) as ex:
            futures = [ex.submit(download_one, u, DOWNLOAD_TIMEOUT_SECS, None) for u in to_get]
            for fut in tqdm(as_completed(futures), total=len(futures)):
                uid, ok, secs, note = fut.result()
                downloaded_ct += int(ok)
                if PRINT_PER_ITEM_INFO:
                    print(f"  {uid} → {note} in {secs:.1f}s")
        print(f"Downloaded (parallel): {downloaded_ct}/{len(to_get)} new files.")
else:
    print("Skipping downloads.")

# ---------------------- FRAME LIST LOADER ----------------------
def load_frames_for(uid):
    p = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
    if not os.path.exists(p): return []
    with open(p) as f: return [int(x.strip()) for x in f if x.strip()]

# ---------------------- EXTRACTION ----------------------
def move_tmp_to_drive(out_tmp, out_final):
    if os.path.exists(out_final):
        for f in os.listdir(out_tmp):
            src = os.path.join(out_tmp, f)
            dst = os.path.join(out_final, f)
            if not os.path.exists(dst): shutil.move(src, dst)
        shutil.rmtree(out_tmp, ignore_errors=True)
    else:
        shutil.move(out_tmp, out_final)

def extract_one(uid):
    media_path = os.path.join(MEDIA_DIR, f"{uid}.mp4")   # NOW points to .../v2/clips for clips
    if not os.path.exists(media_path):
        return uid, 0, 0.0, 0, "media_missing"

    info = ffprobe_media_info(media_path)
    total_frames_media = info["nb_frames"] if info["nb_frames"] else 0
    w, h, msize = info["width"], info["height"], info["size_bytes"]

    out_tmp   = os.path.join(FRAMES_TMP_ROOT, uid)
    out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)
    os.makedirs(out_tmp, exist_ok=True)

    try:
        if EXTRACTION_MODE == "all":
            new_count, secs = run_ffmpeg_all(media_path, out_tmp, timeout=FFMPEG_TIMEOUT_SECS)
            requested_ct = total_frames_media if total_frames_media else 0
        elif EXTRACTION_MODE == "first_n":
            new_count, secs = run_ffmpeg_first_n(media_path, NUM_FRAMES_TO_EXTRACT, out_tmp, timeout=FFMPEG_TIMEOUT_SECS)
            requested_ct = NUM_FRAMES_TO_EXTRACT
        elif EXTRACTION_MODE == "from_lists":
            frames = load_frames_for(uid)
            if not frames:
                return uid, 0, 0.0, total_frames_media, "no_frame_list"
            new_count, secs = run_ffmpeg_select(media_path, frames, out_tmp,
                                                chunk=CHUNK_SIZE_FRAMES_SELECT,
                                                timeout=FFMPEG_TIMEOUT_SECS)
            requested_ct = len(frames)
        else:
            return uid, 0, 0.0, total_frames_media, "bad_mode"

        move_tmp_to_drive(out_tmp, out_final)

        if DELETE_MEDIA_AFTER:
            try: os.remove(media_path)
            except: pass

        imgs_now = len(list_existing_jpgs(out_final))
        if PRINT_PER_ITEM_INFO:
            print(f"  {uid}: {w}x{h}, {format_size(msize)}, total≈{total_frames_media} | requested={requested_ct} new={new_count} now={imgs_now}")
        return uid, new_count, secs, total_frames_media, "ok"

    except subprocess.CalledProcessError:
        return uid, 0, 0.0, total_frames_media, "ffmpeg_failed"
    except Exception as e:
        return uid, 0, 0.0, total_frames_media, f"error:{str(e)[:80]}"

# ---------------------- RUN EXTRACTION ----------------------
rows = []
total_requested, total_extracted = 0, 0
if USE_PARALLEL_EXTRACTION and ids_all:
    print(f"Parallel extraction with {N_EXTRACT_WORKERS} workers ...")
    with ThreadPoolExecutor(max_workers=max(1, int(N_EXTRACT_WORKERS))) as ex:
        futures = [ex.submit(extract_one, u) for u in ids_all]
        for fut in tqdm(as_completed(futures), total=len(futures)):
            uid, new_ct, secs, tf_all, note = fut.result()
            if EXTRACTION_MODE == "first_n":
                req_ct = NUM_FRAMES_TO_EXTRACT
            elif EXTRACTION_MODE == "all":
                req_ct = tf_all if tf_all else 0
            else:
                fpath = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
                req_ct = sum(1 for _ in open(fpath)) if os.path.exists(fpath) else 0

            out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)
            imgs_now = len(list_existing_jpgs(out_final)) if os.path.exists(out_final) else 0

            rows.append((uid, req_ct, new_ct, imgs_now, tf_all, 0.0, secs, note))
            total_requested += req_ct
            total_extracted += new_ct
else:
    print("Serial extraction ...")
    for uid in tqdm(ids_all):
        uid, new_ct, secs, tf_all, note = extract_one(uid)
        if EXTRACTION_MODE == "first_n":
            req_ct = NUM_FRAMES_TO_EXTRACT
        elif EXTRACTION_MODE == "all":
            req_ct = tf_all if tf_all else 0
        else:
            fpath = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
            req_ct = sum(1 for _ in open(fpath)) if os.path.exists(fpath) else 0
        out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)
        imgs_now = len(list_existing_jpgs(out_final)) if os.path.exists(out_final) else 0
        rows.append((uid, req_ct, new_ct, imgs_now, tf_all, 0.0, secs, note))
        total_requested += req_ct
        total_extracted += new_ct

# ---------------------- MARK DONE & SUMMARY ----------------------
with open(PROCESSED_LOG,"a") as f:
    for uid, *_ in rows:
        f.write(uid + "\n")

outer_t1 = time.time()
print("\n========== SUMMARY ==========")
print(f"Source: {SOURCE_KIND} (dataset={DATASET})")
print(f"Mode: {EXTRACTION_MODE}")
print(f"Items processed: {len(rows)} / {len(ids_all)} selected")
print(f"Frames requested (sum): {total_requested}")
print(f"Frames extracted (new this run): {total_extracted}")
print(f"Total wall time: {timedelta(seconds=int(outer_t1-outer_t0))}")

if rows:
    print("\n[uid | req | new | imgs_now | total_frames | download_s | extract_s | note]")
    for uid, req, new, imgs, tf, dls, exs, note in rows[:40]:
        tf_disp = f"{tf}" if tf not in (None, 0) else "unknown"
        print(f"{uid} | {req:4d} | {new:4d} | {imgs:7d} | {tf_disp:12} | {dls:10.1f} | {exs:9.1f} | {note}")

print(f"\nFrames on Drive: {FRAMES_DRIVE_ROOT}")
print(f"Processed log updated: {PROCESSED_LOG}")
print("=============================================")

Source: clip_540 → dataset='clips', media dir='/content/drive/MyDrive/ego4d_data/v2/clips'
Selected 3 item(s) for mode='from_lists'
Using SPECIFIC_IDS (length=3).
Need to download: 3 file(s).
[clips] Prepared parent video list from 3 clip id(s) → 3 parent video(s): /content/clip_parent_vuids_subset_940586289.txt
[clips] Running: ego4d --output_directory /content/drive/MyDrive/ego4d_data --datasets clips --version v2 --video_uid_file /content/clip_parent_vuids_subset_940586289.txt -y
[clips] Batch download invoked via parent video_uids. (See log above)
Batch 'ok' presence (post-check) 0/3.
Parallel extraction with 2 workers ...

  0%|          | 0/3 [00:00<?, ?it/s]

========== SUMMARY ==========
Source: clip_540 (dataset=clips)
Mode: from_lists
Items processed: 3 / 3 selected
Frames requested (sum): 176
Frames extracted (new this run): 0
Total wall time: 0:00:04

[uid | req | new | imgs_now | total_frames | download_s | extract_s | note]
004e8f11-9d56-4208-aeaf-77b03ced000c |   35 |    0 |       0 | unknown      |        0.0 |       0.0 | media_missing
00600a90-0934-4d5f-aa9d-1cdea46ab740 |   41 |    0 |       0 | unknown      |        0.0 |       0.0 | media_missing
005efbab-c314-48d8-8dd9-bfc1263ec5df |  100 |    0 |       0 | unknown      |        0.0 |       0.0 | media_missing

Frames on Drive: /content/drive/MyDrive/ego4d_data/v2/extracted_frames
Processed log updated: /content/drive/MyDrive/ego4d_data/v2/processed_uids_clip540.txt
=============================================

In [53]:
!ls -lh /content/drive/MyDrive/ego4d_data/v2/clips | head
# Check the exact clip files you need:
!ls -lh /content/drive/MyDrive/ego4d_data/v2/clips | grep -E '005efbab|004e8f11|00600a90|002e11bc' || true

total 5.2M
-rw------- 1 root root 5.2M Nov  7 02:05 manifest.csv
-rw------- 1 root root  134 Nov  7 00:10 manifest.ver

In [47]:
!ls -lh /content/drive/MyDrive/ego4d_data/v2/clips | head

total 5.2M
-rw------- 1 root root 5.2M Nov  7 01:55 manifest.csv
-rw------- 1 root root  134 Nov  7 00:10 manifest.ver

# Clip 540 included

In [22]:
# ==============================================
# Ego4D — FINAL single cell (video_540 OR clip_540)
# Uses existing UID list + *_frames.txt (NO JSON reading)
# SOURCE_KIND:
#   - "video_540" -> dataset: video_540ss   (frame files: <video_uid>_frames.txt)
#   - "clip_540"  -> dataset: clips_540ss   (frame files: <clip_uid>_clip_frames.txt, 30 FPS)
#
# Modes: 'from_lists' | 'first_n' | 'all'
# Parallel download + parallel extraction + optional batch download
# ==============================================
import os, subprocess, time, math, json, shutil
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import timedelta
from tqdm.auto import tqdm

# ---------------------- USER CONFIG ----------------------
EGO4D_ROOT   = "/content/drive/MyDrive/ego4d_data"
VERSION      = "v2"

# Choose source:
#  - "video_540" -> downscaled canonical videos (dataset: video_540ss), video-frame indices
#  - "clip_540"  -> downscaled canonical clips  (dataset: clips_540ss), clip-frame indices @ 30 FPS
SOURCE_KIND  = "clip_540"      # <<< "video_540" or "clip_540"

# Extraction mode:
EXTRACTION_MODE = "from_lists"  # <<< 'from_lists' | 'first_n' | 'all'
NUM_FRAMES_TO_EXTRACT = 200     # used only if EXTRACTION_MODE == 'first_n'

# Selection controls:
NUM_ITEMS_TO_PROCESS = 4       # e.g., 50  (None = all)
SPECIFIC_IDS = [               # <<< Optional: list of UIDs (video_uids or clip_uids depending on SOURCE_KIND)
    # "a8f95c5f-7d7b-419b-af29-60d97d8fe379",  # example for clip_540 (clip_uid)
    # "002d2729-df71-438d-8396-5895b349e8fd",  # example for video_540 (video_uid)
]

# Download + extraction controls
DOWNLOAD_MISSING           = True
DELETE_MEDIA_AFTER         = False         # delete .mp4 after each successful extraction
USE_PARALLEL_DOWNLOADS     = True
USE_PARALLEL_EXTRACTION    = True
BATCH_DOWNLOAD             = True          # use chunked *uid_file to reduce CLI overhead
BATCH_CHUNK_SIZE           = 100

N_DOWNLOAD_WORKERS         = 4
N_EXTRACT_WORKERS          = 2
FFMPEG_TIMEOUT_SECS        = 1800
DOWNLOAD_TIMEOUT_SECS      = 3600
CHUNK_SIZE_FRAMES_SELECT   = 800           # indices per ffmpeg call
PRINT_PER_ITEM_INFO        = True

# ---------------------- PATHS ----------------------
if SOURCE_KIND == "video_540":
    DATASET          = "video_540ss"
    MEDIA_DIR        = f"{EGO4D_ROOT}/{VERSION}/video_540ss"
    UID_LIST_FILE    = f"{EGO4D_ROOT}/sta_uids.txt"                       # video_uids
    FRAME_LISTS_DIR  = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists/videos"   # <video_uid>_frames.txt
    FRAME_FILE_TPL   = "{uid}_frames.txt"
    PROCESSED_LOG    = f"{EGO4D_ROOT}/{VERSION}/processed_uids_video540.txt"
    UID_FLAG_SINGLE  = "--video_uids"
    UID_FLAG_FILE    = "--video_uid_file"
elif SOURCE_KIND == "clip_540":
    DATASET          = "clips_540ss"
    MEDIA_DIR        = f"{EGO4D_ROOT}/{VERSION}/clips_540ss"
    UID_LIST_FILE    = f"{EGO4D_ROOT}/sta_clip_uids.txt"                  # clip_uids
    FRAME_LISTS_DIR  = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists/clips"    # <clip_uid>_clip_frames.txt
    FRAME_FILE_TPL   = "{uid}_clip_frames.txt"
    PROCESSED_LOG    = f"{EGO4D_ROOT}/{VERSION}/processed_uids_clip540.txt"
    UID_FLAG_SINGLE  = "--clip_uids"
    UID_FLAG_FILE    = "--clip_uid_file"
else:
    raise SystemExit("SOURCE_KIND must be 'video_540' or 'clip_540'")

FRAMES_DRIVE_ROOT = f"{EGO4D_ROOT}/{VERSION}/extracted_frames"  # frames/<id>/*.jpg
FRAMES_TMP_ROOT   = "/content/tmp_frames"                       # local scratch (fast)

# ---------------------- PREP ----------------------
os.makedirs(MEDIA_DIR, exist_ok=True)
os.makedirs(FRAME_LISTS_DIR, exist_ok=True)
os.makedirs(FRAMES_DRIVE_ROOT, exist_ok=True)
os.makedirs(FRAMES_TMP_ROOT, exist_ok=True)

def which(cmd: str) -> bool:
    import shutil as _sh
    return _sh.which(cmd) is not None

def format_size(n):
    if n is None: return "N/A"
    for u in ["B","KB","MB","GB","TB"]:
        if n < 1024: return f"{n:.2f} {u}"
        n /= 1024
    return f"{n:.2f} PB"

def list_existing_jpgs(folder):
    return [f for f in os.listdir(folder) if f.lower().endswith(".jpg")] if os.path.isdir(folder) else []

def build_eqn_select(frames):
    return "+".join([f"eq(n\\,{int(n)})" for n in frames])

def ffprobe_media_info(path):
    info = {"nb_frames": None, "duration": None, "r_frame_rate": None,
            "width": None, "height": None, "size_bytes": None}
    if not os.path.exists(path):
        return info
    try:
        info["size_bytes"] = os.path.getsize(path)
    except Exception:
        pass
    cmd = ["ffprobe","-v","error","-select_streams","v:0",
           "-show_entries","stream=nb_frames,r_frame_rate,width,height:format=duration",
           "-of","json", path]
    try:
        res = subprocess.run(cmd, text=True, capture_output=True, check=True)
        data = json.loads(res.stdout or "{}")
        if "streams" in data and data["streams"]:
            s = data["streams"][0]
            if s.get("nb_frames") is not None:
                try: info["nb_frames"] = int(s["nb_frames"])
                except: pass
            info["r_frame_rate"] = s.get("r_frame_rate")
            info["width"]  = int(s["width"])  if s.get("width")  else None
            info["height"] = int(s["height"]) if s.get("height") else None
        if "format" in data and data["format"].get("duration") is not None:
            try: info["duration"] = float(data["format"]["duration"])
            except: pass
        if info["nb_frames"] in (None, 0):
            fps = None
            if info["r_frame_rate"]:
                try:
                    a,b = info["r_frame_rate"].split("/")
                    a = float(a); b = float(b) if float(b) != 0 else 1.0
                    fps = a/b
                except: pass
            if fps and info["duration"]:
                info["nb_frames"] = int(fps * info["duration"])
    except:
        pass
    return info

# ---------------------- FFMPEG RUNNERS ----------------------
def run_ffmpeg_select(media_path, frames, out_dir, start_number=None, chunk=800, timeout=1800):
    os.makedirs(out_dir, exist_ok=True)
    frames = sorted(set(int(x) for x in frames))
    if not frames: return 0, 0.0
    before = len(list_existing_jpgs(out_dir))
    if start_number is None: start_number = before
    t0 = time.time()
    for i in range(0, len(frames), chunk):
        piece = frames[i:i+chunk]
        vf = f"select='{build_eqn_select(piece)}',setpts=N/FRAME_RATE/TB"
        cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
               "-i", media_path, "-vf", vf, "-vsync","0",
               "-start_number", str(start_number),
               os.path.join(out_dir, "%07d.jpg")]
        subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
        start_number += len(piece)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

def run_ffmpeg_first_n(media_path, n, out_dir, timeout=1800):
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
           "-i", media_path, "-vframes", str(int(n)),
           os.path.join(out_dir, "%07d.jpg")]
    t0 = time.time()
    subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

def run_ffmpeg_all(media_path, out_dir, timeout=1800):
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
           "-i", media_path, "-vsync","0",
           os.path.join(out_dir, "%07d.jpg")]
    t0 = time.time()
    subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

# ---------------------- DOWNLOAD HELPERS ----------------------
def download_one(uid, timeout=3600, aws_profile=None):
    path = os.path.join(MEDIA_DIR, f"{uid}.mp4")
    if os.path.exists(path):
        return uid, True, 0.0, "present"
    if not which("ego4d"):
        return uid, False, 0.0, "ego4d CLI not found"

    cmd = ["ego4d","--output_directory", EGO4D_ROOT, "--datasets", DATASET,
           "--version", VERSION, UID_FLAG_SINGLE, uid, "-y"]
    if aws_profile:
        cmd += ["--aws_profile_name", aws_profile]
    t0 = time.time()
    try:
        subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
        ok = os.path.exists(path); t1 = time.time()
        return uid, ok, (t1-t0), ("downloaded" if ok else "missing_after_dl")
    except subprocess.CalledProcessError:
        return uid, False, time.time()-t0, "ego4d failed"
    except subprocess.TimeoutExpired:
        return uid, False, time.time()-t0, "timeout"

def batch_download_ids(ids, chunk_size=100, timeout=3600, aws_profile=None):
    if not which("ego4d"):
        print("  !!! ego4d CLI not found; cannot batch download.")
        return 0, len(ids)
    ok_total = 0
    for i in range(0, len(ids), chunk_size):
        chunk = ids[i:i+chunk_size]
        tmpfile = f"/content/ego4d_ids_{i//chunk_size}.txt"
        with open(tmpfile,"w") as f:
            f.write("\n".join(chunk))
        cmd = ["ego4d","--output_directory", EGO4D_ROOT, "--datasets", DATASET,
               "--version", VERSION, UID_FLAG_FILE, tmpfile, "-y"]
        if aws_profile:
            cmd += ["--aws_profile_name", aws_profile]
        try:
            subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
        except subprocess.CalledProcessError:
            pass
        except subprocess.TimeoutExpired:
            pass
        ok_total += sum(os.path.exists(os.path.join(MEDIA_DIR, f"{u}.mp4")) for u in chunk)
        try: os.remove(tmpfile)
        except: pass
    return ok_total, len(ids)

# ---------------------- LOAD/CHOOSE IDS ----------------------
def load_all_ids_from_file(path):
    if not os.path.exists(path):
        raise SystemExit(f"UID list not found: {path}")
    with open(path,"r") as f:
        return [ln.strip() for ln in f if ln.strip()]

def choose_ids():
    if SPECIFIC_IDS:
        seen, base = set(), []
        for u in SPECIFIC_IDS:
            if u not in seen:
                base.append(u); seen.add(u)
    else:
        base = load_all_ids_from_file(UID_LIST_FILE)

    if EXTRACTION_MODE == "from_lists":
        filtered = []
        for u in base:
            fpath = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=u))
            if os.path.exists(fpath):
                filtered.append(u)
        if len(filtered) != len(base):
            print(f"NOTE: {len(base)-len(filtered)} id(s) missing frame file → skipped.")
        base = filtered

    if NUM_ITEMS_TO_PROCESS:
        base = base[:NUM_ITEMS_TO_PROCESS]
    return base

ids_all = choose_ids()

print(f"Source: {SOURCE_KIND} → dataset='{DATASET}', media dir='{MEDIA_DIR}'")
print(f"Selected {len(ids_all)} item(s) for mode='{EXTRACTION_MODE}'")
if SPECIFIC_IDS:
    print(f"Using SPECIFIC_IDS (length={len(SPECIFIC_IDS)}).")

# ---------------------- PREFLIGHT ----------------------
if not which("ffmpeg"):
    raise SystemExit("Install ffmpeg first (e.g., `!apt-get -y install ffmpeg`).")
if DOWNLOAD_MISSING and not which("ego4d"):
    print("WARNING: ego4d CLI not found; downloads will be skipped.")

# ---------------------- DOWNLOAD PHASE ----------------------
outer_t0 = time.time()
downloaded_ct = 0

if DOWNLOAD_MISSING and ids_all:
    to_get = [u for u in ids_all if not os.path.exists(os.path.join(MEDIA_DIR, f"{u}.mp4"))]
    print(f"Need to download: {len(to_get)} file(s).")

    if BATCH_DOWNLOAD and to_get:
        ok_ct, total_ct = batch_download_ids(to_get, chunk_size=BATCH_CHUNK_SIZE, timeout=DOWNLOAD_TIMEOUT_SECS)
        downloaded_ct += ok_ct
        print(f"Batch downloaded {ok_ct}/{total_ct} (now present in {MEDIA_DIR}).")

    elif USE_PARALLEL_DOWNLOADS and to_get:
        print(f"Parallel downloading with {N_DOWNLOAD_WORKERS} workers ...")
        with ThreadPoolExecutor(max_workers=max(1, int(N_DOWNLOAD_WORKERS))) as ex:
            futures = [ex.submit(download_one, u, DOWNLOAD_TIMEOUT_SECS, None) for u in to_get]
            for fut in tqdm(as_completed(futures), total=len(futures)):
                uid, ok, secs, note = fut.result()
                downloaded_ct += int(ok)
                if PRINT_PER_ITEM_INFO:
                    print(f"  {uid} → {note} in {secs:.1f}s")
        print(f"Downloaded (parallel): {downloaded_ct}/{len(to_get)} new files.")
else:
    print("Skipping downloads.")

# ---------------------- FRAME LIST LOADER ----------------------
def load_frames_for(uid):
    p = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
    if not os.path.exists(p): return []
    with open(p) as f:
        return [int(x.strip()) for x in f if x.strip()]

# ---------------------- EXTRACTION ----------------------
def move_tmp_to_drive(out_tmp, out_final):
    if os.path.exists(out_final):
        for f in os.listdir(out_tmp):
            src = os.path.join(out_tmp, f)
            dst = os.path.join(out_final, f)
            if not os.path.exists(dst):
                shutil.move(src, dst)
        shutil.rmtree(out_tmp, ignore_errors=True)
    else:
        shutil.move(out_tmp, out_final)

def extract_one(uid):
    media_path = os.path.join(MEDIA_DIR, f"{uid}.mp4")
    if not os.path.exists(media_path):
        return uid, 0, 0.0, 0, "media_missing"

    info = ffprobe_media_info(media_path)
    total_frames_media = info["nb_frames"] if info["nb_frames"] else 0
    w, h, msize = info["width"], info["height"], info["size_bytes"]

    out_tmp   = os.path.join(FRAMES_TMP_ROOT, uid)    # local scratch
    out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)  # Drive
    os.makedirs(out_tmp, exist_ok=True)

    try:
        if EXTRACTION_MODE == "all":
            new_count, secs = run_ffmpeg_all(media_path, out_tmp, timeout=FFMPEG_TIMEOUT_SECS)
            requested_ct = total_frames_media if total_frames_media else 0
        elif EXTRACTION_MODE == "first_n":
            new_count, secs = run_ffmpeg_first_n(media_path, NUM_FRAMES_TO_EXTRACT, out_tmp,
                                                 timeout=FFMPEG_TIMEOUT_SECS)
            requested_ct = NUM_FRAMES_TO_EXTRACT
        elif EXTRACTION_MODE == "from_lists":
            frames = load_frames_for(uid)
            if not frames:
                return uid, 0, 0.0, total_frames_media, "no_frame_list"
            new_count, secs = run_ffmpeg_select(media_path, frames, out_tmp,
                                                chunk=CHUNK_SIZE_FRAMES_SELECT,
                                                timeout=FFMPEG_TIMEOUT_SECS)
            requested_ct = len(frames)
        else:
            return uid, 0, 0.0, total_frames_media, "bad_mode"

        move_tmp_to_drive(out_tmp, out_final)

        if DELETE_MEDIA_AFTER:
            try: os.remove(media_path)
            except: pass

        imgs_now = len(list_existing_jpgs(out_final))
        if PRINT_PER_ITEM_INFO:
            print(f"  {uid}: {w}x{h}, {format_size(msize)}, total≈{total_frames_media} | requested={requested_ct} new={new_count} now={imgs_now}")
        return uid, new_count, secs, total_frames_media, "ok"

    except subprocess.CalledProcessError:
        return uid, 0, 0.0, total_frames_media, "ffmpeg_failed"
    except Exception as e:
        return uid, 0, 0.0, total_frames_media, f"error:{str(e)[:80]}"

# ---------------------- RUN EXTRACTION ----------------------
rows = []
total_requested, total_extracted = 0, 0
if USE_PARALLEL_EXTRACTION and ids_all:
    print(f"Parallel extraction with {N_EXTRACT_WORKERS} workers ...")
    with ThreadPoolExecutor(max_workers=max(1, int(N_EXTRACT_WORKERS))) as ex:
        futures = [ex.submit(extract_one, u) for u in ids_all]
        for fut in tqdm(as_completed(futures), total=len(futures)):
            uid, new_ct, secs, tf_all, note = fut.result()
            if EXTRACTION_MODE == "first_n":
                req_ct = NUM_FRAMES_TO_EXTRACT
            elif EXTRACTION_MODE == "all":
                req_ct = tf_all if tf_all else 0
            else:
                fpath = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
                req_ct = sum(1 for _ in open(fpath)) if os.path.exists(fpath) else 0

            out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)
            imgs_now = len(list_existing_jpgs(out_final)) if os.path.exists(out_final) else 0

            rows.append((uid, req_ct, new_ct, imgs_now, tf_all, 0.0, secs, note))
            total_requested += req_ct
            total_extracted += new_ct
else:
    print("Serial extraction ...")
    for uid in tqdm(ids_all):
        uid, new_ct, secs, tf_all, note = extract_one(uid)
        if EXTRACTION_MODE == "first_n":
            req_ct = NUM_FRAMES_TO_EXTRACT
        elif EXTRACTION_MODE == "all":
            req_ct = tf_all if tf_all else 0
        else:
            fpath = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
            req_ct = sum(1 for _ in open(fpath)) if os.path.exists(fpath) else 0
        out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)
        imgs_now = len(list_existing_jpgs(out_final)) if os.path.exists(out_final) else 0
        rows.append((uid, req_ct, new_ct, imgs_now, tf_all, 0.0, secs, note))
        total_requested += req_ct
        total_extracted += new_ct

# ---------------------- MARK DONE & SUMMARY ----------------------
with open(PROCESSED_LOG,"a") as f:
    for uid, *_ in rows:
        f.write(uid + "\n")

outer_t1 = time.time()
print("\n========== SUMMARY ==========")
print(f"Source: {SOURCE_KIND} (dataset={DATASET})")
print(f"Mode: {EXTRACTION_MODE}")
print(f"Items processed: {len(rows)} / {len(ids_all)} selected")
print(f"Frames requested (sum): {total_requested}")
print(f"Frames extracted (new this run): {total_extracted}")
print(f"Total wall time: {timedelta(seconds=int(outer_t1-outer_t0))}")

if rows:
    print("\n[uid | req | new | imgs_now | total_frames | download_s | extract_s | note]")
    for uid, req, new, imgs, tf, dls, exs, note in rows[:40]:
        tf_disp = f"{tf}" if tf not in (None, 0) else "unknown"
        print(f"{uid} | {req:4d} | {new:4d} | {imgs:7d} | {tf_disp:12} | {dls:10.1f} | {exs:9.1f} | {note}")

print(f"\nFrames on Drive: {FRAMES_DRIVE_ROOT}")
print(f"Processed log updated: {PROCESSED_LOG}")
print("=============================================")

Source: video_540 → dataset='video_540ss', media dir='/content/drive/MyDrive/ego4d_data/v2/video_540ss'
Selected 4 item(s) for mode='from_lists'
Need to download: 0 file(s).
Parallel extraction with 2 workers ...

  0%|          | 0/4 [00:00<?, ?it/s]

  000cd456-ff8d-499b-b0c1-4acead128a8b: 720x540, 117.08 MB, total≈28744 | requested=4 new=4 now=501
  002c3b5c-ed86-4af3-99a1-4b497b7c8a86: 720x540, 450.92 MB, total≈82740 | requested=124 new=124 now=501

KeyboardInterrupt:

In [60]:
!ego4d --output_directory /content \
      --datasets clip_256ss --version v2 \
      --video_uids 000cd456-ff8d-499b-b0c1-4acead128a8b -y

Warning: Non-standard Dataset Specfied (Allowed, will attempt download): ['clip_256ss']
ERROR:root:ERROR: video_uids specified for non-video datasets (and will be ignored)
Datasets to download: {'clip_256ss'}
Download Path: /content/v2
Ego4D Metadata: /content/ego4d.json
Checking requested datasets and versions...
Created download directory for version 'v2' of dataset: 'clip_256ss' at: /content/v2/clip_256ss
Only downloading a subset of the video files because the 'video_uids' flag has been set on the command line or in the config file. A total of 1 video files will be downloaded.

Retrieving object metadata from S3...
100% 14025/14025 [00:30<00:00, 463.35object/s]
Checking if latest file versions are already downloaded...
 98% 13745/14025 [02:05<00:04, 65.84file/s] WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-iiith.s3.ap-south-1.amazonaws.com. Connection pool size: 10
100% 14025/14025 [02:07<00:00, 110.38file/s]
No existing videos to filter.
Downloading 14025 files..
  1% 6.66G/454G [02:02<5:25:55, 24.5MiB/s]^C

# Main extraction

In [17]:
# ==============================================
# Ego4D — FRAME EXTRACTION ONLY (CLIPS)
# Uses existing clip_uids txt + <clip_uid>_clip_frames.txt (NO downloading)
# Fast, parallel ffmpeg extraction to LOCAL /content output
# ==============================================
import os, subprocess, time, json, shutil
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import timedelta
from tqdm.auto import tqdm

# ---------------------- USER CONFIG ----------------------
# Your Drive root where clips + frame lists already live
EGO4D_ROOT   = "/content/drive/MyDrive/ego4d_data"
VERSION      = "v2"

# We extract from dataset=clips (clip_uids, 30 FPS space)
SOURCE_KIND  = "clip_540"  # keep for structure; enforced to clips below

# Extraction mode:
EXTRACTION_MODE = "from_lists"   # 'from_lists' | 'first_n' | 'all'
NUM_FRAMES_TO_EXTRACT = 200      # used only if EXTRACTION_MODE == 'first_n'

# How many clip_uids to process (None = all)
NUM_ITEMS_TO_PROCESS = 10
# If you want to target a few clips only, list them here; otherwise leave empty to use UID_LIST_FILE
SPECIFIC_IDS = [
    # "002e11bc-deef-45f7-9af8-59421a606d69",
]

# Parallelism
USE_PARALLEL_EXTRACTION = True
N_EXTRACT_WORKERS       = 4          # try 2-4 on Colab free
FFMPEG_THREADS_PER_JOB  = 1          # keep 1 per worker to avoid oversubscription
FFMPEG_TIMEOUT_SECS     = 1800
CHUNK_SIZE_FRAMES_SELECT= 1000       # eq(n,...) indices per ffmpeg call; 800-1500 is good
PRINT_PER_ITEM_INFO     = True

# ---------------------- PATHS ----------------------
# Input media (already downloaded):
MEDIA_DIR        = f"{EGO4D_ROOT}/{VERSION}/clips_540/clips"                # clips/*.mp4

# Master list of clip_uids (one per line):
UID_LIST_FILE    = f"{EGO4D_ROOT}/sta_clip_uids.txt"             # clip_uids

# Per-clip frame index lists (generated earlier):
FRAME_LISTS_DIR  = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists/clips"   # <clip_uid>_clip_frames.txt
FRAME_FILE_TPL   = "{uid}_clip_frames.txt"

# LOCAL output dir (fast): each clip into /content/<OUTPUT_ROOT>/<clip_uid>/*.jpg
OUTPUT_ROOT      = "/content/extracted_frames"

# ---------------------- PREP ----------------------
os.makedirs(MEDIA_DIR, exist_ok=True)
os.makedirs(FRAME_LISTS_DIR, exist_ok=True)
os.makedirs(OUTPUT_ROOT, exist_ok=True)

def which(cmd: str) -> bool:
    import shutil as _sh
    return _sh.which(cmd) is not None

def format_size(n):
    if n is None: return "N/A"
    for u in ["B","KB","MB","GB","TB"]:
        if n < 1024: return f"{n:.2f} {u}"
        n /= 1024
    return f"{n:.2f} PB"

def list_existing_jpgs(folder):
    return [f for f in os.listdir(folder) if f.lower().endswith(".jpg")] if os.path.isdir(folder) else []

def build_eqn_select(frames):
    return "+".join([f"eq(n\\,{int(n)})" for n in frames])

def ffprobe_media_info(path):
    info = {"nb_frames": None, "duration": None, "r_frame_rate": None,
            "width": None, "height": None, "size_bytes": None}
    if not os.path.exists(path):
        return info
    try: info["size_bytes"] = os.path.getsize(path)
    except: pass
    cmd = ["ffprobe","-v","error","-select_streams","v:0",
           "-show_entries","stream=nb_frames,r_frame_rate,width,height:format=duration",
           "-of","json", path]
    try:
        res = subprocess.run(cmd, text=True, capture_output=True, check=True)
        data = json.loads(res.stdout or "{}")
        if "streams" in data and data["streams"]:
            s = data["streams"][0]
            if s.get("nb_frames") is not None:
                try: info["nb_frames"] = int(s["nb_frames"])
                except: pass
            info["r_frame_rate"] = s.get("r_frame_rate")
            info["width"]  = int(s.get("width") or 0)  or None
            info["height"] = int(s.get("height") or 0) or None
        if "format" in data and data["format"].get("duration") is not None:
            try: info["duration"] = float(data["format"]["duration"])
            except: pass
        if info["nb_frames"] in (None, 0):
            fps = None
            if info["r_frame_rate"]:
                try:
                    a,b = info["r_frame_rate"].split("/")
                    a = float(a); b = float(b) if float(b) != 0 else 1.0
                    fps = a/b
                except: pass
            if fps and info["duration"]:
                info["nb_frames"] = int(fps * info["duration"])
    except: pass
    return info

# ---------------------- FFMPEG RUNNERS ----------------------
def run_ffmpeg_select(media_path, frames, out_dir, start_number=None, chunk=1000, timeout=1800, threads_per_job=1):
    """
    Fast multi-frame extraction using select/eq(n,...) in chunks.
    Clips are constant-FPS at 30, so indices are in clip frame space.
    """
    os.makedirs(out_dir, exist_ok=True)
    frames = sorted(set(int(x) for x in frames))
    if not frames: return 0, 0.0
    before = len(list_existing_jpgs(out_dir))
    if start_number is None: start_number = before
    t0 = time.time()
    for i in range(0, len(frames), chunk):
        piece = frames[i:i+chunk]
        vf = f"select='{build_eqn_select(piece)}',setpts=N/FRAME_RATE/TB"
        cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
               "-threads", str(threads_per_job),
               "-i", media_path, "-vf", vf, "-vsync","0",
               "-start_number", str(start_number),
               os.path.join(out_dir, "%07d.jpg")]
        subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
        start_number += len(piece)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

def run_ffmpeg_first_n(media_path, n, out_dir, timeout=1800, threads_per_job=1):
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
           "-threads", str(threads_per_job),
           "-i", media_path, "-vframes", str(int(n)),
           os.path.join(out_dir, "%07d.jpg")]
    t0 = time.time()
    subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

def run_ffmpeg_all(media_path, out_dir, timeout=1800, threads_per_job=1):
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
           "-threads", str(threads_per_job),
           "-i", media_path, "-vsync","0",
           os.path.join(out_dir, "%07d.jpg")]
    t0 = time.time()
    subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

# ---------------------- LOAD/CHOOSE IDS ----------------------
def load_all_ids_from_file(path):
    if not os.path.exists(path): raise SystemExit(f"UID list not found: {path}")
    with open(path,"r") as f: return [ln.strip() for ln in f if ln.strip()]

def choose_ids():
    if SPECIFIC_IDS:
        seen, base = set(), []
        for u in SPECIFIC_IDS:
            if u not in seen:
                base.append(u); seen.add(u)
    else:
        base = load_all_ids_from_file(UID_LIST_FILE)

    if EXTRACTION_MODE == "from_lists":
        filtered = []
        for u in base:
            fpath = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=u))
            if os.path.exists(fpath): filtered.append(u)
        if len(filtered) != len(base):
            print(f"NOTE: {len(base)-len(filtered)} id(s) missing frame file → skipped.")
        base = filtered

    if NUM_ITEMS_TO_PROCESS: base = base[:NUM_ITEMS_TO_PROCESS]
    return base

ids_all = choose_ids()
print(f"Source: {SOURCE_KIND} → dataset='clips', media dir='{MEDIA_DIR}'")
print(f"Selected {len(ids_all)} item(s) for mode='{EXTRACTION_MODE}'")
if SPECIFIC_IDS: print(f"Using SPECIFIC_IDS (length={len(SPECIFIC_IDS)}).")

# ---------------------- PREFLIGHT ----------------------
if not which("ffmpeg"): raise SystemExit("Install ffmpeg first (e.g., `!apt-get -y install ffmpeg`).")

# ---------------------- FRAME LIST LOADER ----------------------
def load_frames_for(uid):
    p = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
    if not os.path.exists(p): return []
    with open(p) as f: return [int(x.strip()) for x in f if x.strip()]

# ---------------------- EXTRACTION ----------------------
def extract_one(uid):
    media_path = os.path.join(MEDIA_DIR, f"{uid}.mp4")   # clips/<clip_uid>.mp4
    if not os.path.exists(media_path):
        return uid, 0, 0.0, 0, "media_missing"

    info = ffprobe_media_info(media_path)
    total_frames_media = info["nb_frames"] if info["nb_frames"] else 0
    w, h, msize = info["width"], info["height"], info["size_bytes"]

    out_dir = os.path.join(OUTPUT_ROOT, uid)  # LOCAL
    os.makedirs(out_dir, exist_ok=True)

    try:
        if EXTRACTION_MODE == "all":
            new_count, secs = run_ffmpeg_all(
                media_path, out_dir,
                timeout=FFMPEG_TIMEOUT_SECS,
                threads_per_job=FFMPEG_THREADS_PER_JOB
            )
            requested_ct = total_frames_media if total_frames_media else 0

        elif EXTRACTION_MODE == "first_n":
            new_count, secs = run_ffmpeg_first_n(
                media_path, NUM_FRAMES_TO_EXTRACT, out_dir,
                timeout=FFMPEG_TIMEOUT_SECS,
                threads_per_job=FFMPEG_THREADS_PER_JOB
            )
            requested_ct = NUM_FRAMES_TO_EXTRACT

        elif EXTRACTION_MODE == "from_lists":
            frames = load_frames_for(uid)
            if not frames:
                return uid, 0, 0.0, total_frames_media, "no_frame_list"
            new_count, secs = run_ffmpeg_select(
                media_path, frames, out_dir,
                chunk=CHUNK_SIZE_FRAMES_SELECT,
                timeout=FFMPEG_TIMEOUT_SECS,
                threads_per_job=FFMPEG_THREADS_PER_JOB
            )
            requested_ct = len(frames)
        else:
            return uid, 0, 0.0, total_frames_media, "bad_mode"

        imgs_now = len(list_existing_jpgs(out_dir))
        if PRINT_PER_ITEM_INFO:
            print(f"  {uid}: {w}x{h}, {format_size(msize)}, total≈{total_frames_media} | requested={requested_ct} new={new_count} now={imgs_now}")
        return uid, new_count, secs, total_frames_media, "ok"

    except subprocess.CalledProcessError:
        return uid, 0, 0.0, total_frames_media, "ffmpeg_failed"
    except Exception as e:
        return uid, 0, 0.0, total_frames_media, f"error:{str(e)[:120]}"

# ---------------------- RUN EXTRACTION ----------------------
outer_t0 = time.time()
rows = []
total_requested, total_extracted = 0, 0

if USE_PARALLEL_EXTRACTION and ids_all:
    print(f"Parallel extraction with {N_EXTRACT_WORKERS} workers ...")
    with ThreadPoolExecutor(max_workers=max(1, int(N_EXTRACT_WORKERS))) as ex:
        futures = [ex.submit(extract_one, u) for u in ids_all]
        for fut in tqdm(as_completed(futures), total=len(futures)):
            uid, new_ct, secs, tf_all, note = fut.result()
            if EXTRACTION_MODE == "first_n":
                req_ct = NUM_FRAMES_TO_EXTRACT
            elif EXTRACTION_MODE == "all":
                req_ct = tf_all if tf_all else 0
            else:
                fpath = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
                req_ct = sum(1 for _ in open(fpath)) if os.path.exists(fpath) else 0

            out_final = os.path.join(OUTPUT_ROOT, uid)
            imgs_now = len(list_existing_jpgs(out_final)) if os.path.exists(out_final) else 0

            rows.append((uid, req_ct, new_ct, imgs_now, tf_all, 0.0, secs, note))
            total_requested += req_ct
            total_extracted += new_ct
else:
    print("Serial extraction ...")
    for uid in tqdm(ids_all):
        uid, new_ct, secs, tf_all, note = extract_one(uid)
        if EXTRACTION_MODE == "first_n":
            req_ct = NUM_FRAMES_TO_EXTRACT
        elif EXTRACTION_MODE == "all":
            req_ct = tf_all if tf_all else 0
        else:
            fpath = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
            req_ct = sum(1 for _ in open(fpath)) if os.path.exists(fpath) else 0
        out_final = os.path.join(OUTPUT_ROOT, uid)
        imgs_now = len(list_existing_jpgs(out_final)) if os.path.exists(out_final) else 0
        rows.append((uid, req_ct, new_ct, imgs_now, tf_all, 0.0, secs, note))
        total_requested += req_ct
        total_extracted += new_ct

# ---------------------- SUMMARY ----------------------
outer_t1 = time.time()
print("\n========== SUMMARY ==========")
print(f"Source: {SOURCE_KIND} (dataset=clips)")
print(f"Mode: {EXTRACTION_MODE}")
print(f"Items processed: {len(rows)} / {len(ids_all)} selected")
print(f"Frames requested (sum): {total_requested}")
print(f"Frames extracted (new this run): {total_extracted}")
print(f"Local output: {OUTPUT_ROOT}")
print(f"Total wall time: {timedelta(seconds=int(outer_t1-outer_t0))}")

if rows:
    print("\n[uid | req | new | imgs_now | total_frames | download_s | extract_s | note]")
    for uid, req, new, imgs, tf, dls, exs, note in rows[:60]:
        tf_disp = f"{tf}" if tf not in (None, 0) else "unknown"
        print(f"{uid} | {req:4d} | {new:4d} | {imgs:7d} | {tf_disp:12} | {dls:10.1f} | {exs:9.1f} | {note}")

print("=============================================")

Source: clip_540 → dataset='clips', media dir='/content/drive/MyDrive/ego4d_data/v2/clips_540/clips'
Selected 10 item(s) for mode='from_lists'
Parallel extraction with 4 workers ...

  0%|          | 0/10 [00:00<?, ?it/s]

  004e8f11-9d56-4208-aeaf-77b03ced000c: 1440x1080, 27.18 MB, total≈5305 | requested=35 new=35 now=35
  005efbab-c314-48d8-8dd9-bfc1263ec5df: 1440x1080, 46.56 MB, total≈9480 | requested=100 new=100 now=100
  00819273-b88a-4d51-97fb-a394cf0f3118: 1440x1080, 33.01 MB, total≈7172 | requested=40 new=40 now=40
  002e11bc-deef-45f7-9af8-59421a606d69: 1920x1440, 48.33 MB, total≈9239 | requested=124 new=124 now=124
  00600a90-0934-4d5f-aa9d-1cdea46ab740: 1440x1080, 51.85 MB, total≈9480 | requested=41 new=41 now=41
  00be9fe7-617c-46cf-a0de-7432896c1705: 1440x1080, 39.01 MB, total≈8159 | requested=120 new=120 now=120
  011041b5-08be-46dd-9bc6-b555df96fdb9: 1920x1080, 9.93 MB, total≈2398 | requested=80 new=80 now=80
  00f97226-7b7e-4cd4-a903-ed95759a138b: 1440x1080, 47.34 MB, total≈9480 | requested=74 new=74 now=74
  00f8134b-a739-4d41-b2fe-18c7bceb2b69: 1920x1080, 58.58 MB, total≈5675 | requested=19 new=19 now=19
  00ccfa33-b669-420a-ba8d-4767a1565f23: 1920x1440, 54.57 MB, total≈9480 | requested=68 new=68 now=68

========== SUMMARY ==========
Source: clip_540 (dataset=clips)
Mode: from_lists
Items processed: 10 / 10 selected
Frames requested (sum): 701
Frames extracted (new this run): 701
Local output: /content/extracted_frames
Total wall time: 0:09:15

[uid | req | new | imgs_now | total_frames | download_s | extract_s | note]
004e8f11-9d56-4208-aeaf-77b03ced000c |   35 |   35 |      35 | 5305         |        0.0 |     129.6 | ok
005efbab-c314-48d8-8dd9-bfc1263ec5df |  100 |  100 |     100 | 9480         |        0.0 |     221.6 | ok
00819273-b88a-4d51-97fb-a394cf0f3118 |   40 |   40 |      40 | 7172         |        0.0 |     157.2 | ok
002e11bc-deef-45f7-9af8-59421a606d69 |  124 |  124 |     124 | 9239         |        0.0 |     329.7 | ok
00600a90-0934-4d5f-aa9d-1cdea46ab740 |   41 |   41 |      41 | 9480         |        0.0 |     341.3 | ok
00be9fe7-617c-46cf-a0de-7432896c1705 |  120 |  120 |     120 | 8159         |        0.0 |     170.6 | ok
011041b5-08be-46dd-9bc6-b555df96fdb9 |   80 |   80 |      80 | 2398         |        0.0 |      65.6 | ok
00f97226-7b7e-4cd4-a903-ed95759a138b |   74 |   74 |      74 | 9480         |        0.0 |     178.3 | ok
00f8134b-a739-4d41-b2fe-18c7bceb2b69 |   19 |   19 |      19 | 5675         |        0.0 |     200.9 | ok
00ccfa33-b669-420a-ba8d-4767a1565f23 |   68 |   68 |      68 | 9480         |        0.0 |     262.8 | ok
=============================================

In [22]:
!rm -rf /content/extract_tmp

In [6]:
# ==============================================
# Ego4D — Resume-safe fast frame extraction (clips or video_540)
# - Uses GPU (Decord NVDEC) when available, falls back to CPU
# - Skips already-complete clips
# - Continues from last written frame number if partially done
# - Writes a run log to Drive
# ==============================================
import os, sys, json, time, csv, shutil, subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timedelta
from tqdm.auto import tqdm

# ---------------------- USER CONFIG ----------------------
EGO4D_ROOT   = "/content/drive/MyDrive/ego4d_data"
VERSION      = "v2"

SOURCE_KIND  = "clip_540"            # "clip_540" or "video_540"
EXTRACTION_MODE = "from_lists"       # 'from_lists' | 'first_n' | 'all'
NUM_ITEMS_TO_PROCESS = 12          # e.g., 100 (None = all)
NUM_FRAMES_TO_EXTRACT = 200          # used if EXTRACTION_MODE == 'first_n'
SPECIFIC_IDS = []                    # optional: subset

# Speed/quality knobs
SPEED_MODE         = "decord"        # "decord" | "ffmpeg_select_fast" | "ffmpeg_ranges"
USE_GPU_DECORD     = False            # try GPU (NVDEC) with decord when available
RESIZE_TO_540      = True
JPG_QUALITY        = 6               # 2..7 lower is better quality, 7 is fastest/smallest
N_EXTRACT_WORKERS  = 4
FFMPEG_TIMEOUT_SECS= 1800
PRINT_PER_ITEM_INFO= True

# ---------------------- PATHS ----------------------
if SOURCE_KIND == "clip_540":
    DATASET          = "clips"
    MEDIA_DIR        = f"{EGO4D_ROOT}/{VERSION}/clips_540/clips"   # <clip_uid>.mp4
    UID_LIST_FILE    = f"{EGO4D_ROOT}/sta_clip_uids.txt"           # list of clip_uids
    FRAME_LISTS_DIR  = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists/clips"
    FRAME_FILE_TPL   = "{uid}_clip_frames.txt"
elif SOURCE_KIND == "video_540":
    DATASET          = "video_540ss"
    MEDIA_DIR        = f"{EGO4D_ROOT}/{VERSION}/video_540ss"       # <video_uid>.mp4
    UID_LIST_FILE    = f"{EGO4D_ROOT}/sta_uids.txt"
    FRAME_LISTS_DIR  = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists/videos"
    FRAME_FILE_TPL   = "{uid}_frames.txt"
else:
    raise SystemExit("SOURCE_KIND must be 'clip_540' or 'video_540'")

FRAMES_DRIVE_ROOT = f"{EGO4D_ROOT}/{VERSION}/extracted_frames"
FRAMES_TMP_ROOT   = "/content/extract_tmp"   # fast local scratch
LOG_CSV           = f"{EGO4D_ROOT}/{VERSION}/extraction_log.csv"

# ---------------------- PREP ----------------------
for p in (MEDIA_DIR, FRAME_LISTS_DIR, FRAMES_DRIVE_ROOT, FRAMES_TMP_ROOT, os.path.dirname(LOG_CSV)):
    os.makedirs(p, exist_ok=True)

def which(cmd: str) -> bool:
    import shutil as _sh; return _sh.which(cmd) is not None

def list_existing_jpgs(folder):
    return sorted([f for f in os.listdir(folder) if f.lower().endswith(".jpg")]) if os.path.isdir(folder) else []

def ensure_log_header(path):
    if not os.path.exists(path):
        with open(path, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["timestamp","uid","source_kind","mode","speed_mode","requested","new_written","total_now","note"])

def append_log(uid, requested, new_written, total_now, note):
    ensure_log_header(LOG_CSV)
    with open(LOG_CSV, "a", newline="") as f:
        w = csv.writer(f)
        w.writerow([datetime.now().isoformat(timespec="seconds"), uid, SOURCE_KIND,
                    EXTRACTION_MODE, SPEED_MODE, requested, new_written, total_now, note])

def load_ids():
    if SPECIFIC_IDS:
        base = list(dict.fromkeys([x for x in SPECIFIC_IDS if x]))
    else:
        if not os.path.exists(UID_LIST_FILE):
            raise SystemExit(f"UID list not found: {UID_LIST_FILE}")
        base = [ln.strip() for ln in open(UID_LIST_FILE) if ln.strip()]

    if EXTRACTION_MODE == "from_lists":
        kept = []
        for u in base:
            if os.path.exists(os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=u))):
                kept.append(u)
        base = kept

    if NUM_ITEMS_TO_PROCESS:
        base = base[:NUM_ITEMS_TO_PROCESS]
    return base

def load_frames_for(uid):
    p = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
    if not os.path.exists(p): return []
    with open(p) as f:
        return [int(x.strip()) for x in f if x.strip()]

def ffprobe_nb_frames(path):
    cmd = ["ffprobe","-v","error","-select_streams","v:0",
           "-show_entries","stream=nb_frames,r_frame_rate,width,height:format=duration",
           "-of","json", path]
    try:
        out = subprocess.run(cmd, text=True, capture_output=True, check=True, timeout=60)
        data = json.loads(out.stdout or "{}")
        nb = None
        if data.get("streams"):
            s = data["streams"][0]
            nb = s.get("nb_frames")
            if nb is not None:
                try: nb = int(nb)
                except: nb = None
        if nb is None and "format" in data and data["format"].get("duration"):
            fps = None
            s = data["streams"][0]
            if s.get("r_frame_rate"):
                a,b = s["r_frame_rate"].split("/")
                fps = float(a)/max(float(b),1.0)
            if fps:
                nb = int(float(data["format"]["duration"])*fps)
        return nb
    except:
        return None

def to_ranges(indices):
    if not indices: return []
    xs = sorted(set(int(i) for i in indices))
    runs, s, p = [], xs[0], xs[0]
    for k in xs[1:]:
        if k == p+1: p = k
        else: runs.append((s, p)); s = p = k
    runs.append((s,p))
    return runs

# ---------------------- DEC0RD PATH (GPU-aware, resume-safe) ----------------------
def ensure_decord():
    try:
        import decord  # noqa
        import imageio, PIL  # noqa
        return True
    except Exception:
        print("[setup] Installing decord, pillow, imageio ...")
        rc = os.system(f"{sys.executable} -m pip install -q decord pillow imageio")
        return rc == 0

def _resize_short_side(arr, short=540):
    from PIL import Image
    h, w = arr.shape[:2]
    if h <= 0 or w <= 0: return arr
    if h <= w:
        new_h = short; new_w = int(round(w * (short/float(h))))
    else:
        new_w = short; new_h = int(round(h * (short/float(w))))
    return Image.fromarray(arr).resize((new_w, new_h), Image.BILINEAR)

def _choose_decord_ctx():
    # Try GPU (NVDEC) if requested and available; else CPU
    try:
        from decord import gpu, cpu
        if USE_GPU_DECORD:
            # Quick sanity: check NVIDIA runtime presence
            has_gpu_runtime = os.path.isdir("/usr/local/cuda") or os.path.exists("/proc/driver/nvidia/version")
            if has_gpu_runtime:
                try:
                    return gpu(0)
                except Exception:
                    pass
        return cpu(0)
    except Exception:
        from decord import cpu
        return cpu(0)

def extract_with_decord(media_path, indices, out_dir, start_number):
    ok = ensure_decord()
    if not ok:
        return 0, 0.0, "no_decord"
    import imageio.v2 as imageio
    from decord import VideoReader

    ctx = _choose_decord_ctx()
    t0 = time.time()

    try:
        vr = VideoReader(media_path, ctx=ctx)
    except Exception as e:
        return 0, 0.0, f"decord_open_failed:{str(e)[:80]}"

    n_total = len(vr)

    # choose picks
    if EXTRACTION_MODE == "all":
        picks = list(range(n_total))
    elif EXTRACTION_MODE == "first_n":
        picks = list(range(min(NUM_FRAMES_TO_EXTRACT, n_total)))
    else:
        picks = sorted(set([i for i in indices if 0 <= i < n_total]))

    if not picks:
        return 0, 0.0, "no_frames"

    # write
    B = 256
    written = 0
    os.makedirs(out_dir, exist_ok=True)

    for i in range(0, len(picks), B):
        batch_idx = picks[i:i+B]
        try:
            batch_nd = vr.get_batch(batch_idx)      # NDArray on (gpu/cpu)
            batch_np = batch_nd.asnumpy()           # transfer to host
        except Exception as e:
            return written, (time.time()-t0), f"decord_batch_failed:{str(e)[:80]}"

        for j in range(batch_np.shape[0]):
            arr = batch_np[j]
            if RESIZE_TO_540:
                arr = _resize_short_side(arr, short=540)
            # map JPG_QUALITY (2..7) to imageio quality ~ (76..16); keep high-ish quality
            outpath = os.path.join(out_dir, f"{start_number+written:07d}.jpg")
            try:
                imageio.imwrite(outpath, arr, quality=max(1, 100 - JPG_QUALITY*12))
            except Exception as e:
                return written, (time.time()-t0), f"image_write_failed:{str(e)[:80]}"
            written += 1

    return written, (time.time()-t0), ("ok_gpu" if "gpu" in str(ctx).lower() else "ok_cpu")

# ---------------------- FFMPEG PATHS (resume-safe) ----------------------
def ffmpeg_select_fast(media_path, indices, out_dir, start_number):
    os.makedirs(out_dir, exist_ok=True)
    if EXTRACTION_MODE == "all":
        vf = []
    elif EXTRACTION_MODE == "first_n":
        vf = ["-vframes", str(int(NUM_FRAMES_TO_EXTRACT))]
    else:
        frames = sorted(set(int(x) for x in indices))
        if not frames: return 0, 0.0, "no_frames"
        eqn = "+".join([f"eq(n\\,{int(n)})" for n in frames])
        filt = f"select='{eqn}',setpts=N/FRAME_RATE/TB"
        if RESIZE_TO_540:
            filt += ",scale='if(gt(iw,ih),-1,540)':'if(gt(iw,ih),540,-1)'"
        vf = ["-vf", filt]
    q = ["-q:v", str(int(JPG_QUALITY))]
    t0 = time.time()
    before = len(list_existing_jpgs(out_dir))
    cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
           "-threads","2","-i", media_path] + vf + q + \
          ["-vsync","0","-start_number", str(int(start_number)),
           os.path.join(out_dir, "%07d.jpg")]
    subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=FFMPEG_TIMEOUT_SECS)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after-before), (time.time()-t0), "ok"

def ffmpeg_ranges(media_path, indices, out_dir, start_number):
    runs = to_ranges(indices)
    if not runs:
        return 0, 0.0, "no_frames"
    written_total, t0 = 0, time.time()
    for (a,b) in runs:
        filt = f"select='between(n\\,{a}\\,{b})',setpts=N/FRAME_RATE/TB"
        if RESIZE_TO_540:
            filt += ",scale='if(gt(iw,ih),-1,540)':'if(gt(iw,ih),540,-1)'"
        cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
               "-threads","2","-i", media_path,
               "-vf", filt, "-q:v", str(int(JPG_QUALITY)),
               "-vsync","0","-start_number", str(int(start_number + written_total)),
               os.path.join(out_dir, "%07d.jpg")]
        subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=FFMPEG_TIMEOUT_SECS)
        written_total += (b - a + 1)
    return written_total, (time.time()-t0), "ok"

# ---------------------- REQUEST SIZE & RESUME LOGIC ----------------------
def requested_count_for(uid, media_path):
    if EXTRACTION_MODE == "from_lists":
        return len(load_frames_for(uid))
    elif EXTRACTION_MODE == "first_n":
        return int(NUM_FRAMES_TO_EXTRACT)
    else:
        nb = ffprobe_nb_frames(media_path)
        return nb if isinstance(nb, int) and nb > 0 else 0

def remaining_indices_for(uid, existing_final_ct):
    """For 'from_lists': drop the first 'existing_final_ct' indices to continue in order."""
    if EXTRACTION_MODE != "from_lists":
        return []
    idx_all = sorted(set(load_frames_for(uid)))
    if existing_final_ct <= 0:
        return idx_all
    if existing_final_ct >= len(idx_all):
        return []
    return idx_all[existing_final_ct:]

# ---------------------- MAIN EXTRACTOR ----------------------
def extract_one(uid):
    media_path = os.path.join(MEDIA_DIR, f"{uid}.mp4")
    if not os.path.exists(media_path):
        note = "media_missing"
        append_log(uid, 0, 0, 0, note)
        return uid, 0, 0.0, note

    out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)
    out_tmp   = os.path.join(FRAMES_TMP_ROOT, uid)
    os.makedirs(out_tmp, exist_ok=True)

    # Resume / Skip logic
    req_ct = requested_count_for(uid, media_path)
    existing_final_ct = len(list_existing_jpgs(out_final))
    if existing_final_ct >= req_ct > 0:
        note = "skip_already_done"
        if PRINT_PER_ITEM_INFO:
            print(f"  {uid}: already complete ({existing_final_ct}/{req_ct}) → skip")
        append_log(uid, req_ct, 0, existing_final_ct, note)
        return uid, 0, 0.0, note

    # Determine indices still needed and base numbering
    if EXTRACTION_MODE == "from_lists":
        indices_needed = remaining_indices_for(uid, existing_final_ct)
        base_start = existing_final_ct
    elif EXTRACTION_MODE == "first_n":
        indices_needed = []
        base_start = existing_final_ct
    else:  # 'all'
        indices_needed = []
        base_start = existing_final_ct

    try:
        # Extract to local tmp using the correct start_number
        if SPEED_MODE == "decord":
            new_ct, secs, note = extract_with_decord(media_path, indices_needed, out_tmp, start_number=base_start)
            if (note not in ("ok", "ok_gpu", "ok_cpu")) or new_ct == 0:
                # fallback to ffmpeg
                if SPEED_MODE == "ffmpeg_ranges" and EXTRACTION_MODE == "from_lists":
                    new_ct, secs, note = ffmpeg_ranges(media_path, indices_needed, out_tmp, start_number=base_start)
                else:
                    new_ct, secs, note = ffmpeg_select_fast(media_path, indices_needed, out_tmp, start_number=base_start)
        elif SPEED_MODE == "ffmpeg_ranges" and EXTRACTION_MODE == "from_lists":
            new_ct, secs, note = ffmpeg_ranges(media_path, indices_needed, out_tmp, start_number=base_start)
        else:
            new_ct, secs, note = ffmpeg_select_fast(media_path, indices_needed, out_tmp, start_number=base_start)

        # Move to Drive (merge, don't overwrite)
        os.makedirs(out_final, exist_ok=True)
        for f in os.listdir(out_tmp):
            src = os.path.join(out_tmp, f)
            dst = os.path.join(out_final, f)
            if not os.path.exists(dst):
                shutil.move(src, dst)
        shutil.rmtree(out_tmp, ignore_errors=True)

        total_now = len(list_existing_jpgs(out_final))
        if PRINT_PER_ITEM_INFO:
            nb = ffprobe_nb_frames(media_path) or "unknown"
            print(f"  {uid}: wrote {new_ct} jpgs → now={total_now}/{req_ct} | total≈{nb} | {note} in {secs:.1f}s")
        append_log(uid, req_ct, new_ct, total_now, note)
        return uid, new_ct, secs, note

    except subprocess.CalledProcessError:
        note = "ffmpeg_failed"
        append_log(uid, req_ct, 0, len(list_existing_jpgs(out_final)), note)
        return uid, 0, 0.0, note
    except Exception as e:
        note = f"error:{str(e)[:120]}"
        append_log(uid, req_ct, 0, len(list_existing_jpgs(out_final)), note)
        return uid, 0, 0.0, note

# ---------------------- RUN ----------------------
ids_all = load_ids()
print(f"Source: {SOURCE_KIND} (dataset={DATASET})")
print(f"Speed mode: {SPEED_MODE} | Use GPU: {USE_GPU_DECORD} | Resize to 540: {RESIZE_TO_540} | JPG quality: {JPG_QUALITY}")
print(f"Selected {len(ids_all)} item(s); mode='{EXTRACTION_MODE}'")

t0 = time.time()
rows = []
if ids_all:
    with ThreadPoolExecutor(max_workers=max(1, int(N_EXTRACT_WORKERS))) as ex:
        futs = [ex.submit(extract_one, u) for u in ids_all]
        for fut in tqdm(as_completed(futs), total=len(futs)):
            rows.append(fut.result())

t1 = time.time()
total_new = sum(r[1] for r in rows)
print("\n========== SUMMARY ==========")
print(f"Items processed: {len(rows)}")
print(f"Frames extracted (new): {total_new}")
print(f"Local scratch used: {FRAMES_TMP_ROOT} → merged into: {FRAMES_DRIVE_ROOT}")
print(f"Log: {LOG_CSV}")
print(f"Total wall time: {timedelta(seconds=int(t1-t0))}")
if rows:
    print("\n[uid | new | note]")
    for uid, new_ct, secs, note in rows[:60]:
        print(f"{uid} | {new_ct:4d} | {note}")
print("=============================================")

Source: clip_540 (dataset=clips)
Speed mode: decord | Use GPU: False | Resize to 540: True | JPG quality: 6
Selected 12 item(s); mode='from_lists'
  002e11bc-deef-45f7-9af8-59421a606d69: already complete (124/124) → skip

  0%|          | 0/12 [00:00<?, ?it/s]

  005efbab-c314-48d8-8dd9-bfc1263ec5df: already complete (100/100) → skip
  00600a90-0934-4d5f-aa9d-1cdea46ab740: already complete (41/41) → skip
  004e8f11-9d56-4208-aeaf-77b03ced000c: already complete (35/35) → skip
  00819273-b88a-4d51-97fb-a394cf0f3118: already complete (40/40) → skip
  00be9fe7-617c-46cf-a0de-7432896c1705: already complete (120/120) → skip
  00ccfa33-b669-420a-ba8d-4767a1565f23: already complete (68/68) → skip
  00f8134b-a739-4d41-b2fe-18c7bceb2b69: already complete (19/19) → skip
  0125dda9-8b16-4f12-8373-35f8e1c5acc7: wrote 31 jpgs → now=31/31 | total≈9239 | ok_cpu in 28.0s
  011041b5-08be-46dd-9bc6-b555df96fdb9: wrote 80 jpgs → now=80/80 | total≈2398 | ok_cpu in 44.0s
  00f97226-7b7e-4cd4-a903-ed95759a138b: wrote 74 jpgs → now=74/74 | total≈9480 | ok_cpu in 47.9s
  011eaceb-42c9-41b3-a038-87ea17c6e15d: wrote 56 jpgs → now=56/56 | total≈9480 | ok_cpu in 50.9s

========== SUMMARY ==========
Items processed: 12
Frames extracted (new): 241
Local scratch used: /content/extract_tmp → merged into: /content/drive/MyDrive/ego4d_data/v2/extracted_frames
Log: /content/drive/MyDrive/ego4d_data/v2/extraction_log.csv
Total wall time: 0:00:51

[uid | new | note]
002e11bc-deef-45f7-9af8-59421a606d69 |    0 | skip_already_done
005efbab-c314-48d8-8dd9-bfc1263ec5df |    0 | skip_already_done
00600a90-0934-4d5f-aa9d-1cdea46ab740 |    0 | skip_already_done
004e8f11-9d56-4208-aeaf-77b03ced000c |    0 | skip_already_done
00819273-b88a-4d51-97fb-a394cf0f3118 |    0 | skip_already_done
00be9fe7-617c-46cf-a0de-7432896c1705 |    0 | skip_already_done
00ccfa33-b669-420a-ba8d-4767a1565f23 |    0 | skip_already_done
00f8134b-a739-4d41-b2fe-18c7bceb2b69 |    0 | skip_already_done
0125dda9-8b16-4f12-8373-35f8e1c5acc7 |   31 | ok_cpu
011041b5-08be-46dd-9bc6-b555df96fdb9 |   80 | ok_cpu
00f97226-7b7e-4cd4-a903-ed95759a138b |   74 | ok_cpu
011eaceb-42c9-41b3-a038-87ea17c6e15d |   56 | ok_cpu
=============================================

In [12]:
import decord
from decord import gpu, VideoReader
vr = VideoReader("/path/to/video.mp4", ctx=gpu(0))
print("Loaded OK:", len(vr))

RuntimeError: Error reading /path/to/video.mp4...

In [ ]:
!ffmpeg -hwaccel cuda -i /content/video.mp4 /content/frames/frame_%05d.jpg

# Main download

In [13]:
import math

# Input file
input_path = "/content/drive/MyDrive/ego4d_data/sta_clip_uids_part2.txt"

# Read all UIDs (remove blanks)
with open(input_path) as f:
    lines = [line.strip() for line in f if line.strip()]

# Split into 3 roughly equal parts
n = len(lines)
split_size = math.ceil(n / 3)

parts = [
    lines[i*split_size : (i+1)*split_size]
    for i in range(3)
]

# Output paths
output_paths = [
    "/content/drive/MyDrive/ego4d_data/sta_clip_uids_part2_1.txt",
    "/content/drive/MyDrive/ego4d_data/sta_clip_uids_part2_2.txt",
    "/content/drive/MyDrive/ego4d_data/sta_clip_uids_part2_3.txt",
]

# Write each part
for i, part in enumerate(parts):
    with open(output_paths[i], "w") as f:
        f.write("\n".join(part))
    print(f"✅ Saved {len(part)} lines to {output_paths[i]}")

print(f"\nTotal lines: {n} (split roughly equally into 3 files)")

✅ Saved 259 lines to /content/drive/MyDrive/ego4d_data/sta_clip_uids_part2_1.txt
✅ Saved 259 lines to /content/drive/MyDrive/ego4d_data/sta_clip_uids_part2_2.txt
✅ Saved 257 lines to /content/drive/MyDrive/ego4d_data/sta_clip_uids_part2_3.txt

Total lines: 775 (split roughly equally into 3 files)

In [73]:
!ego4d --output_directory="/content" --datasets clips --version v2 --video_uid_file /content/drive/MyDrive/ego4d_data/sta_clip_uids_part2_1.txt  -y

Datasets to download: {'clips'}
Download Path: /content/v2
Ego4D Metadata: /content/ego4d.json
Checking requested datasets and versions...
Created download directory for version 'v2' of dataset: 'clips' at: /content/v2/clips
Only downloading a subset of the video files because the 'video_uids' flag has been set on the command line or in the config file. A total of 775 video files will be downloaded.

Retrieving object metadata from S3...
100% 775/775 [00:01<00:00, 668.00object/s]
Checking if latest file versions are already downloaded...
 99% 768/775 [00:13<00:00, 110.48file/s]WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-iiith.s3.ap-south-1.amazonaws.com. Connection pool size: 10
100% 775/775 [00:13<00:00, 58.10file/s]
No existing videos to filter.
Downloading 775 files..
100% 32.7G/32.7G [12:46<00:00, 47.5MiB/s]Checking file integrity...
100% 32.7G/32.7G [13:00<00:00, 45.0MiB/s]

In [74]:
!mkdir -p "/content/drive/MyDrive/ego4d_data/v2/clips_540"

In [8]:
!rsync -avh --progress /content/v2/clips/ "/content/drive/MyDrive/ego4d_data/v2/clips_540/clips/"

sending incremental file list
./
27e3cde9-c408-4cad-8f3e-0d72a7feed05.mp4
         12.49M 100%   60.90MB/s    0:00:00 (xfr#1, to-chk=416/778)
27ff0076-1dcd-45bf-8806-1d2249d74b98.mp4
         22.06M 100%   36.84MB/s    0:00:00 (xfr#2, to-chk=415/778)
28280aa2-5f01-44da-9b47-fef7487ba7df.mp4
         43.68M 100%   33.38MB/s    0:00:01 (xfr#3, to-chk=414/778)
2837ef15-fb03-4c1e-b89e-46424ba6b05c.mp4
         15.73M 100%   27.48MB/s    0:00:00 (xfr#4, to-chk=413/778)
2864df06-c979-4f3b-872d-208869499bc0.mp4
         16.17M 100%   21.27MB/s    0:00:00 (xfr#5, to-chk=412/778)
287cd66a-38b2-4fb9-95e9-44da2d6c307c.mp4
         48.96M 100%   25.71MB/s    0:00:01 (xfr#6, to-chk=411/778)
28b0cf55-a50e-46bb-be51-ddf0060a6b71.mp4
         41.37M 100%   29.03MB/s    0:00:01 (xfr#7, to-chk=410/778)
28d039f1-5eb0-4b3f-a13d-cbf3e25b570d.mp4
         47.20M 100%   37.42MB/s    0:00:01 (xfr#8, to-chk=409/778)
28d34d38-13bd-4b0a-b7c2-0309458cd1d7.mp4
         45.84M 100%   65.26MB/s    0:00:00 (xfr#9, to-chk=408/778)
29501ed1-77bb-4f53-aeb2-d062d5f568a9.mp4
         19.70M 100%   15.06MB/s    0:00:01 (xfr#10, to-chk=407/778)
2951a80f-f965-4e34-b393-7a2a222387df.mp4
         70.64M 100%   53.89MB/s    0:00:01 (xfr#11, to-chk=406/778)
2956f42d-e6a3-4c3d-b955-a82c69dfc941.mp4
         48.94M 100%   63.16MB/s    0:00:00 (xfr#12, to-chk=405/778)
2977601c-53f5-436e-8b3f-3c6549d00ea6.mp4
         70.92M 100%   49.44MB/s    0:00:01 (xfr#13, to-chk=404/778)
298197ce-22ce-4eed-a56a-dcd9a431ce99.mp4
         24.32M 100%   19.04MB/s    0:00:01 (xfr#14, to-chk=403/778)
29a18b1c-579a-49c9-965d-7cbd54fce6f6.mp4
         20.47M 100%   23.57MB/s    0:00:00 (xfr#15, to-chk=402/778)
29ab413c-dcd0-4b4a-92d6-a49c4095bf28.mp4
         48.21M 100%   25.11MB/s    0:00:01 (xfr#16, to-chk=401/778)
29bbe1b5-a683-470a-9229-d9c806597d62.mp4
         23.12M 100%   16.77MB/s    0:00:01 (xfr#17, to-chk=400/778)
29e5c17a-a4fa-419e-b7ce-43e77359e802.mp4
          5.19M 100%   10.13MB/s    0:00:00 (xfr#18, to-chk=399/778)
29ee7dec-5e5f-47c1-a584-a48be14b3162.mp4
         36.45M 100%   22.47MB/s    0:00:01 (xfr#19, to-chk=398/778)
29f73828-c430-422c-9766-f595657c5899.mp4
         47.73M 100%   24.20MB/s    0:00:01 (xfr#20, to-chk=397/778)
2a2b65b8-fcd8-469b-9db3-c08026a3d80f.mp4
         49.79M 100%   29.35MB/s    0:00:01 (xfr#21, to-chk=396/778)
2a39bf76-6938-4780-ae00-d2b01ea70333.mp4
         34.14M 100%   32.30MB/s    0:00:01 (xfr#22, to-chk=395/778)
2a513bb8-1ba7-4019-93d2-ed59f02c9cdf.mp4
         37.53M 100%   52.63MB/s    0:00:00 (xfr#23, to-chk=394/778)
2a5dfc1d-b484-4bc3-aab3-b2eaca79edc2.mp4
         52.70M 100%   30.98MB/s    0:00:01 (xfr#24, to-chk=393/778)
2a8aa41a-2758-41df-b15b-98d46439f68f.mp4
         10.18M 100%   13.74MB/s    0:00:00 (xfr#25, to-chk=392/778)
2a8e15dc-9b10-4932-86a9-931cb68e055d.mp4
         77.82M 100%   41.00MB/s    0:00:01 (xfr#26, to-chk=391/778)
2acc5677-5972-4e4a-833a-bb12b76c33f6.mp4
         44.18M 100%   25.66MB/s    0:00:01 (xfr#27, to-chk=390/778)
2ad12599-94cc-4148-942e-0f7eca99903f.mp4
         44.55M 100%   33.37MB/s    0:00:01 (xfr#28, to-chk=389/778)
2ae6c03e-7003-4d80-923f-bfcc9c30dde8.mp4
         45.90M 100%   43.04MB/s    0:00:01 (xfr#29, to-chk=388/778)
2ae97f2a-b16d-467b-b73a-721cb00996f1.mp4
         40.61M 100%   88.43MB/s    0:00:00 (xfr#30, to-chk=387/778)
2aea720f-38b0-4bc6-b406-f6551608e385.mp4
         44.04M 100%   37.07MB/s    0:00:01 (xfr#31, to-chk=386/778)
2aeab721-4af8-4f83-ba03-493a7f4974c5.mp4
         81.31M 100%   39.62MB/s    0:00:01 (xfr#32, to-chk=385/778)
2b4821a1-d623-46f3-91ce-ad8d2cddf287.mp4
         44.31M 100%   26.20MB/s    0:00:01 (xfr#33, to-chk=384/778)
2b9534c3-bd47-4f30-8b80-62f068dfb08c.mp4
         17.36M 100%   20.37MB/s    0:00:00 (xfr#34, to-chk=383/778)
2bbe54ee-398a-4e5d-bfa6-7bd8d20a1a95.mp4
         23.52M 100%   13.67MB/s    0:00:01 (xfr#35, to-chk=382/778)
2be34254-88ee-4b20-8d8e-284aaa85cd12.mp4
         50.97M 100%   37.48MB/s    0:00:01 (xfr#36, to-chk=381/778)
2c05b95c-02a3-46c5-b68b-6130cc1d05ea.mp4
         51.46M 100%   43.78MB/s    0:00:01 (xfr#37, to-chk=380/778)
2c0d46ac-adc8-4f0a-a2be-33893cefffc7.mp4
         51.95M 100%   35.34MB/s    0:00:01 (xfr#38, to-chk=379/778)
2c2b3c66-4c17-4044-a9b9-164178fc180f.mp4
         52.44M 100%   29.23MB/s    0:00:01 (xfr#39, to-chk=378/778)
2c3a9643-eac0-4a6c-bdc7-7f3b95c8d3bd.mp4
         45.69M 100%   26.12MB/s    0:00:01 (xfr#40, to-chk=377/778)
2c3d9cd1-e935-4023-bb4c-c957173e0743.mp4
        132.39M 100%   54.35MB/s    0:00:02 (xfr#41, to-chk=376/778)
2c42498a-f7ef-495c-a13e-382600c87999.mp4
         48.90M 100%   49.51MB/s    0:00:00 (xfr#42, to-chk=375/778)
2c4a160e-7403-4ecc-b557-d420ea1a1fa4.mp4
         52.66M 100%   38.66MB/s    0:00:01 (xfr#43, to-chk=374/778)
2c733d3c-22b5-4628-88a8-44e364dadbce.mp4
         50.37M 100%   53.97MB/s    0:00:00 (xfr#44, to-chk=373/778)
2c7363b6-8269-4673-8030-673fb698a9fe.mp4
         39.86M 100%   29.65MB/s    0:00:01 (xfr#45, to-chk=372/778)
2c95dcd6-4c91-45a0-8a3f-7c8bf7c5401f.mp4
         50.35M 100%   67.63MB/s    0:00:00 (xfr#46, to-chk=371/778)
2c9debe0-65a6-4afb-8d86-e32c63b3b5d1.mp4
          4.22M 100%    4.86MB/s    0:00:00 (xfr#47, to-chk=370/778)
2c9f4a73-8bdf-4ad1-a8d9-91b38cf58cd8.mp4
         63.67M 100%   41.67MB/s    0:00:01 (xfr#48, to-chk=369/778)
2cb41602-6542-4d44-bba2-5891ba63dbae.mp4
         44.06M 100%   53.46MB/s    0:00:00 (xfr#49, to-chk=368/778)
2cc33c07-45d7-4d3f-9ef5-46289c4d3394.mp4
         51.50M 100%   41.17MB/s    0:00:01 (xfr#50, to-chk=367/778)
2ce440d8-ef8e-40a4-ae6b-b482dc81ab0f.mp4
         50.76M 100%  106.15MB/s    0:00:00 (xfr#51, to-chk=366/778)
2d4e853f-1b81-4813-85b1-24ae1a09b621.mp4
         46.46M 100%   10.61MB/s    0:00:04 (xfr#52, to-chk=365/778)
2d51a36b-b569-47ef-894d-ea2107a9c601.mp4
         48.73M 100%   95.23MB/s    0:00:00 (xfr#53, to-chk=364/778)
2d541012-29d9-421a-a7f1-f69717335507.mp4
         23.40M 100%   29.72MB/s    0:00:00 (xfr#54, to-chk=363/778)
2d59aeda-b325-43b0-b8bf-2ee20b9af05a.mp4
         48.22M 100%   27.32MB/s    0:00:01 (xfr#55, to-chk=362/778)
2d83c911-739c-41c1-ac1d-d936633be25b.mp4
         43.20M 100%   23.16MB/s    0:00:01 (xfr#56, to-chk=361/778)
2d8cab71-ef0e-4505-903d-76fcb697975b.mp4
         48.91M 100%   22.56MB/s    0:00:02 (xfr#57, to-chk=360/778)
2dbb6d58-9dff-42f9-85cf-5992260dd15d.mp4
         48.93M 100%   42.85MB/s    0:00:01 (xfr#58, to-chk=359/778)
2dbd4f59-1aa8-4fe9-b161-21f3d4f517bf.mp4
         12.47M 100%   39.51MB/s    0:00:00 (xfr#59, to-chk=358/778)
2dd48569-e11d-409c-92db-d9a819b425da.mp4
         24.57M 100%   27.66MB/s    0:00:00 (xfr#60, to-chk=357/778)
2e168c7b-3c33-448a-9000-c2aea9fedb46.mp4
         39.45M 100%   22.47MB/s    0:00:01 (xfr#61, to-chk=356/778)
2e247b8c-e036-40e5-9f5a-d003a7131ff7.mp4
         41.85M 100%   30.10MB/s    0:00:01 (xfr#62, to-chk=355/778)
2e251736-6e5b-4f4a-b6de-0316eef17609.mp4
         73.99M 100%   61.90MB/s    0:00:01 (xfr#63, to-chk=354/778)
2e2ae4b4-e707-42c2-b71b-51cbb9228c03.mp4
         44.90M 100%   65.28MB/s    0:00:00 (xfr#64, to-chk=353/778)
2e2fe577-2c7f-4faa-b3ad-7f1f0d791c96.mp4
         40.34M 100%   40.45MB/s    0:00:00 (xfr#65, to-chk=352/778)
2e6cd544-2a5c-457b-8f6b-50f7e5195d31.mp4
         49.64M 100%   36.14MB/s    0:00:01 (xfr#66, to-chk=351/778)
2ea43b2f-bee9-4586-b418-da18bb7c41f6.mp4
         44.14M 100%   33.68MB/s    0:00:01 (xfr#67, to-chk=350/778)
2ead3530-7976-418f-8e13-1deb01b79353.mp4
         55.16M 100%   77.25MB/s    0:00:00 (xfr#68, to-chk=349/778)
2ead6736-5955-4dc4-b5d0-81204a48b5ce.mp4
         49.56M 100%   42.73MB/s    0:00:01 (xfr#69, to-chk=348/778)
2ebe6e35-0a09-4efb-8361-972afc9ee26c.mp4
         88.37M 100%   97.32MB/s    0:00:00 (xfr#70, to-chk=347/778)
2ec1d58b-9950-4b33-a49a-bc48d81176f5.mp4
          4.28M 100%    4.22MB/s    0:00:00 (xfr#71, to-chk=346/778)
2ec2b3cf-d230-43b5-aecc-23330c95ee89.mp4
         55.09M 100%   33.78MB/s    0:00:01 (xfr#72, to-chk=345/778)
2ec8565e-6e02-4795-a090-c7d2fffae8cf.mp4
         55.51M 100%   47.95MB/s    0:00:01 (xfr#73, to-chk=344/778)
2ed74bd6-0639-4607-bcad-40889c8622e3.mp4
         28.13M 100%   41.91MB/s    0:00:00 (xfr#74, to-chk=343/778)
2ee47e1d-5642-449b-9d80-bafccfe30c8d.mp4
          8.00M 100%    8.56MB/s    0:00:00 (xfr#75, to-chk=342/778)
2ef4a071-5717-4c9a-b7a3-c2a67a84158e.mp4
         48.11M 100%   32.63MB/s    0:00:01 (xfr#76, to-chk=341/778)
2f2b196c-a96b-45e5-bfab-0c271554611e.mp4
         48.19M 100%   39.11MB/s    0:00:01 (xfr#77, to-chk=340/778)
2f33d57d-37be-413d-b1ef-18d653ff5797.mp4
         32.39M 100%   56.07MB/s    0:00:00 (xfr#78, to-chk=339/778)
2f777742-eb9a-4d0e-97fe-8d5f71ec120b.mp4
         60.30M 100%   49.74MB/s    0:00:01 (xfr#79, to-chk=338/778)
2f8ab65c-af8c-4700-8e79-eeea480b60a4.mp4
         48.14M 100%   65.21MB/s    0:00:00 (xfr#80, to-chk=337/778)
2f928978-927f-46f6-87f9-79359d9f9abd.mp4
         98.29M 100%   47.82MB/s    0:00:01 (xfr#81, to-chk=336/778)
2f9a204c-10e3-4a24-8aec-6247cc02a7ae.mp4
         42.98M 100%   22.17MB/s    0:00:01 (xfr#82, to-chk=335/778)
2fa1c8d1-34c5-4450-847e-4cd3d5a8e46e.mp4
         46.07M 100%   21.52MB/s    0:00:02 (xfr#83, to-chk=334/778)
2faa0e0b-af43-4fc2-aab7-7f8d5b1d0bd0.mp4
          8.67M 100%   14.47MB/s    0:00:00 (xfr#84, to-chk=333/778)
2fbf3b39-bcdb-4392-bd1c-2fcc1ea4dd72.mp4
        108.04M 100%   40.11MB/s    0:00:02 (xfr#85, to-chk=332/778)
2ff02e72-3701-45c5-b752-8e91afb0f50e.mp4
         49.01M 100%   31.56MB/s    0:00:01 (xfr#86, to-chk=331/778)
2ff8c772-c1d6-464a-84c8-dcc1532fc5a1.mp4
         46.56M 100%   45.55MB/s    0:00:00 (xfr#87, to-chk=330/778)
30292399-a14c-4911-bf62-e9fc6b61e268.mp4
         34.17M 100%   23.56MB/s    0:00:01 (xfr#88, to-chk=329/778)
302cc305-2c85-4c74-888a-21fbe53bb7a3.mp4
         49.47M 100%   49.51MB/s    0:00:00 (xfr#89, to-chk=328/778)
303505b9-2cf3-488d-ae5f-d72d3bf73585.mp4
         44.56M 100%   30.59MB/s    0:00:01 (xfr#90, to-chk=327/778)
3065ebb0-cd16-48b2-a81d-ed71d74c2c0d.mp4
         43.20M 100%   59.80MB/s    0:00:00 (xfr#91, to-chk=326/778)
306a8c13-fbb8-4ad6-a1c8-b65a253b7289.mp4
         32.04M 100%   30.65MB/s    0:00:00 (xfr#92, to-chk=325/778)
30786c9e-737e-457e-8bd5-94d450fef39c.mp4
         29.39M 100%   22.38MB/s    0:00:01 (xfr#93, to-chk=324/778)
309d3618-a374-4f54-a02f-58971453736c.mp4
         51.68M 100%   69.71MB/s    0:00:00 (xfr#94, to-chk=323/778)
30b07ade-1c68-455c-990e-9f2f8f77f76f.mp4
         48.00M 100%   43.39MB/s    0:00:01 (xfr#95, to-chk=322/778)
30c0be6d-01b5-46d2-8307-862f9eab62ba.mp4
         40.31M 100%   24.90MB/s    0:00:01 (xfr#96, to-chk=321/778)
3121a918-44a3-446a-b809-95e1b5766cb0.mp4
         53.57M 100%   53.00MB/s    0:00:00 (xfr#97, to-chk=320/778)
3122b423-0fd4-46a9-94f0-6fd14a333b0a.mp4
         48.24M 100%   32.86MB/s    0:00:01 (xfr#98, to-chk=319/778)
312da1d0-9e56-4f5e-bb12-9cb67e8bc674.mp4
         58.96M 100%   41.01MB/s    0:00:01 (xfr#99, to-chk=318/778)
3148c4fe-6483-4985-b488-223ca861d27b.mp4
         50.33M 100%   40.85MB/s    0:00:01 (xfr#100, to-chk=317/778)
318dd659-4220-4dfa-b192-bc50745a7d06.mp4
         46.95M 100%   54.20MB/s    0:00:00 (xfr#101, to-chk=316/778)
3199c870-0756-4f33-b4e0-69b15d0e94ae.mp4
         40.69M 100%   31.44MB/s    0:00:01 (xfr#102, to-chk=315/778)
31ad4dc2-67d4-4e86-b846-df64a678d346.mp4
         48.48M 100%   45.91MB/s    0:00:01 (xfr#103, to-chk=314/778)
31cafb43-94d8-42e7-ac57-b923fb045fe5.mp4
         41.12M 100%  115.01MB/s    0:00:00 (xfr#104, to-chk=313/778)
31e357fd-c029-493f-bf1b-ed62757721d0.mp4
         18.77M 100%   33.52MB/s    0:00:00 (xfr#105, to-chk=312/778)
31f12c71-435d-47bb-9310-a502faa975fc.mp4
         49.97M 100%   33.59MB/s    0:00:01 (xfr#106, to-chk=311/778)
322b2a61-30ce-4973-8d3f-83cd30e4f4ed.mp4
         59.42M 100%   51.90MB/s    0:00:01 (xfr#107, to-chk=310/778)
322b4ed4-bd02-44d6-af7b-ab8ec35c08e4.mp4
         30.08M 100%   54.53MB/s    0:00:00 (xfr#108, to-chk=309/778)
32a5a027-093a-4913-abec-591348f1e3dc.mp4
         46.52M 100%   30.37MB/s    0:00:01 (xfr#109, to-chk=308/778)
32a94a5c-7d00-4af2-9acf-8533f0af0c60.mp4
         42.87M 100%   38.64MB/s    0:00:01 (xfr#110, to-chk=307/778)
32e25924-9d92-4030-a328-11e2c4c7ac56.mp4
         47.66M 100%   62.34MB/s    0:00:00 (xfr#111, to-chk=306/778)
3308d15b-ddc9-469a-8ed5-abf9348eaace.mp4
         46.38M 100%   27.37MB/s    0:00:01 (xfr#112, to-chk=305/778)
33435898-f587-40c0-bbe4-b81d99d02e10.mp4
         42.25M 100%   25.91MB/s    0:00:01 (xfr#113, to-chk=304/778)
334c9e94-49ac-4866-acaf-1303637b57a4.mp4
         45.00M 100%   46.96MB/s    0:00:00 (xfr#114, to-chk=303/778)
335a16ea-0419-4d97-94d7-c897fe439f9e.mp4
         45.59M 100%   30.34MB/s    0:00:01 (xfr#115, to-chk=302/778)
337f8d6a-b079-4b1d-827a-43061d130288.mp4
         49.84M 100%   46.05MB/s    0:00:01 (xfr#116, to-chk=301/778)
33970eb2-b963-4169-bbc4-421386bb179f.mp4
         69.40M 100%   91.80MB/s    0:00:00 (xfr#117, to-chk=300/778)
33b46d1c-b0d2-40c2-b10c-bfd651298e56.mp4
         46.18M 100%   34.19MB/s    0:00:01 (xfr#118, to-chk=299/778)
33b81950-d0be-487d-8f5f-ab38373cfa82.mp4
         49.30M 100%   53.43MB/s    0:00:00 (xfr#119, to-chk=298/778)
33d64405-654c-4cb0-a162-6d1755d7ab6d.mp4
         51.33M 100%   36.61MB/s    0:00:01 (xfr#120, to-chk=297/778)
33e19c22-799c-4471-b311-6f33126f2334.mp4
         27.28M 100%   28.31MB/s    0:00:00 (xfr#121, to-chk=296/778)
33e49529-d1c5-43b3-ba02-b5570a6ab5e6.mp4
         41.54M 100%   29.06MB/s    0:00:01 (xfr#122, to-chk=295/778)
33eff582-6b78-4d5a-9350-308d38576f0f.mp4
         43.22M 100%   44.22MB/s    0:00:00 (xfr#123, to-chk=294/778)
3404758d-72f4-4a8d-8a8e-81f1d1eef580.mp4
         46.44M 100%   32.38MB/s    0:00:01 (xfr#124, to-chk=293/778)
340cb94f-e55c-47e3-9d54-8a308a81681b.mp4
         40.84M 100%   40.15MB/s    0:00:00 (xfr#125, to-chk=292/778)
341a8ed5-5fd8-4b0f-81b2-2a0ec7e2e75e.mp4
         47.67M 100%   34.21MB/s    0:00:01 (xfr#126, to-chk=291/778)
34262ef4-0094-4cf8-a371-66262858ab77.mp4
         49.45M 100%   59.02MB/s    0:00:00 (xfr#127, to-chk=290/778)
342f509b-4aa9-47f0-8fb2-1efd1f3bdbfa.mp4
         24.51M 100%   18.37MB/s    0:00:01 (xfr#128, to-chk=289/778)
343c12fb-b65e-4f4e-80b0-985b1288e84d.mp4
         18.99M 100%   30.90MB/s    0:00:00 (xfr#129, to-chk=288/778)
348cdf01-20ea-419e-90c8-bffe3e146903.mp4
         48.91M 100%   21.26MB/s    0:00:02 (xfr#130, to-chk=287/778)
34a8915d-cd5f-447a-aa9a-cd9986dab943.mp4
         15.09M 100%   11.55MB/s    0:00:01 (xfr#131, to-chk=286/778)
34bce09d-7fd5-4bd1-a1ef-67ecabebebe1.mp4
         53.11M 100%   40.04MB/s    0:00:01 (xfr#132, to-chk=285/778)
352f1eea-606d-4cd7-906f-733affaf6823.mp4
         87.21M 100%   22.98MB/s    0:00:03 (xfr#133, to-chk=284/778)
353aa0ac-5706-4879-80b3-0f17cd8d0b39.mp4
         49.33M 100%   27.89MB/s    0:00:01 (xfr#134, to-chk=283/778)
3566903b-4bbc-4274-8d59-5669ad3ff789.mp4
         48.47M 100%   21.93MB/s    0:00:02 (xfr#135, to-chk=282/778)
357876b4-566d-406e-9ffc-9430e235d43a.mp4
         48.48M 100%   87.89MB/s    0:00:00 (xfr#136, to-chk=281/778)
359ea071-5769-473a-bdbd-709ab69bfc6a.mp4
        129.70M 100%   80.16MB/s    0:00:01 (xfr#137, to-chk=280/778)
359f9a27-c67b-434c-932a-b4792064ed91.mp4
          7.65M 100%   11.51MB/s    0:00:00 (xfr#138, to-chk=279/778)
35d3bc27-5241-49d9-af15-425a7547c069.mp4
         42.21M 100%   45.08MB/s    0:00:00 (xfr#139, to-chk=278/778)
35daf90c-4892-4991-80dd-fc9fe290b56c.mp4
         50.95M 100%   38.99MB/s    0:00:01 (xfr#140, to-chk=277/778)
35eaff03-a889-48fc-8e17-b22ee657e88e.mp4
          7.25M 100%   22.75MB/s    0:00:00 (xfr#141, to-chk=276/778)
35ef4c2a-2a3c-43fc-b8ab-62b8d69914fe.mp4
         50.15M 100%   58.04MB/s    0:00:00 (xfr#142, to-chk=275/778)
360ddf57-a1c1-4571-a480-32dd4b97737a.mp4
         50.38M 100%   39.90MB/s    0:00:01 (xfr#143, to-chk=274/778)
360fa068-df7b-4fa7-a120-9a3c4268c779.mp4
          9.41M 100%    8.40MB/s    0:00:01 (xfr#144, to-chk=273/778)
3619f6fe-9722-4e98-ac1a-372821f1ec78.mp4
         41.51M 100%  116.79MB/s    0:00:00 (xfr#145, to-chk=272/778)
362756f0-a1d4-4534-ba2f-422393d6d0ef.mp4
         18.96M 100%   38.24MB/s    0:00:00 (xfr#146, to-chk=271/778)
3653070d-1e2f-4245-828c-c28256e1c9dc.mp4
         21.17M 100%   31.65MB/s    0:00:00 (xfr#147, to-chk=270/778)
365d216f-3fd8-4c0f-a26c-421b290ab897.mp4
         51.10M 100%   40.88MB/s    0:00:01 (xfr#148, to-chk=269/778)
366775c0-6cbf-4739-9156-d8aeffcb8bdb.mp4
         73.98M 100%   84.09MB/s    0:00:00 (xfr#149, to-chk=268/778)
3685229d-b932-4588-8137-c51666e4b5d8.mp4
         51.92M 100%   41.12MB/s    0:00:01 (xfr#150, to-chk=267/778)
36b0edc8-b292-47dc-9a41-f08cc605df73.mp4
         44.59M 100%   63.95MB/s    0:00:00 (xfr#151, to-chk=266/778)
36b7c744-d167-43de-8f8f-e83ca3f8f2cc.mp4
         48.86M 100%   40.41MB/s    0:00:01 (xfr#152, to-chk=265/778)
36f8b38a-a408-48c2-863f-26397fd45bbf.mp4
         44.04M 100%   25.09MB/s    0:00:01 (xfr#153, to-chk=264/778)
36fc1c7f-5b53-482c-8627-577f2a01b643.mp4
         18.72M 100%   17.52MB/s    0:00:01 (xfr#154, to-chk=263/778)
370456d4-864e-4349-9cd0-aa80d01fe695.mp4
         78.38M 100%   39.45MB/s    0:00:01 (xfr#155, to-chk=262/778)
3744e276-67b6-439d-97e8-3df6f1720c55.mp4
         37.19M 100%   13.06MB/s    0:00:02 (xfr#156, to-chk=261/778)
375fa5e0-54ca-41b2-aa3d-1ba38997b387.mp4
         36.28M 100%   13.82MB/s    0:00:02 (xfr#157, to-chk=260/778)
3780315a-7bcb-49fa-a05c-1285976fcdd2.mp4
         47.98M 100%   22.15MB/s    0:00:02 (xfr#158, to-chk=259/778)
37ac4e6d-fba4-48c0-9c88-298489aae695.mp4
         36.64M 100%   38.44MB/s    0:00:00 (xfr#159, to-chk=258/778)
37c0d74c-48bb-487e-9bbe-1af871d69419.mp4
         24.04M 100%   18.49MB/s    0:00:01 (xfr#160, to-chk=257/778)
37d99746-23f5-4a33-89a9-c4c642afcc88.mp4
         42.91M 100%   56.60MB/s    0:00:00 (xfr#161, to-chk=256/778)
37ec3556-6af2-4a4d-b4a9-fe4fd75e8cc9.mp4
         47.32M 100%   40.51MB/s    0:00:01 (xfr#162, to-chk=255/778)
381e7ae9-2eae-4534-8df8-2e7793e8c5e9.mp4
         48.97M 100%   92.86MB/s    0:00:00 (xfr#163, to-chk=254/778)
3844e8d7-49dd-471d-a8bf-deb0e98c58e6.mp4
         18.40M 100%   27.21MB/s    0:00:00 (xfr#164, to-chk=253/778)
384d1c75-0b3c-45e6-b948-477917ab96a3.mp4
         20.36M 100%   22.29MB/s    0:00:00 (xfr#165, to-chk=252/778)
387f9c84-bb32-4265-ad89-43cfd3ec3292.mp4
         47.87M 100%   37.05MB/s    0:00:01 (xfr#166, to-chk=251/778)
38ac6476-0065-4e36-9563-2b43aa641c87.mp4
         44.99M 100%   31.37MB/s    0:00:01 (xfr#167, to-chk=250/778)
38c4e562-cfb0-4200-838d-c18ebd6514f9.mp4
         48.34M 100%   62.46MB/s    0:00:00 (xfr#168, to-chk=249/778)
38d34f4a-c53c-4529-9568-18d4aab9005a.mp4
         49.63M 100%   44.28MB/s    0:00:01 (xfr#169, to-chk=248/778)
38f9161a-dfa8-4c09-b608-ec40bbb2d0cd.mp4
         74.59M 100%   96.39MB/s    0:00:00 (xfr#170, to-chk=247/778)
38f9fee3-8ab2-424c-a17a-ebb8cbed22eb.mp4
         48.25M 100%   42.53MB/s    0:00:01 (xfr#171, to-chk=246/778)
391725ce-526b-4931-b899-d4ff25c97432.mp4
         47.60M 100%   88.15MB/s    0:00:00 (xfr#172, to-chk=245/778)
3933a38e-6f4c-4491-9e6f-bcd154dd8ff6.mp4
         48.46M 100%   49.11MB/s    0:00:00 (xfr#173, to-chk=244/778)
3962aebb-35fc-4b0c-a36e-e75316833497.mp4
         53.71M 100%   32.23MB/s    0:00:01 (xfr#174, to-chk=243/778)
3979214f-15fc-4f89-8226-eca1a9579a5e.mp4
         49.50M 100%   22.00MB/s    0:00:02 (xfr#175, to-chk=242/778)
39865b55-0b68-4cf9-a9fa-d55cfbc5909b.mp4
         40.43M 100%   34.00MB/s    0:00:01 (xfr#176, to-chk=241/778)
39b11c63-6bc7-4015-b5de-396572c6fa3b.mp4
         44.11M 100%   63.83MB/s    0:00:00 (xfr#177, to-chk=240/778)
39b59e2f-b2c2-4694-bbc0-ad0b136a6dd5.mp4
         38.76M 100%   25.22MB/s    0:00:01 (xfr#178, to-chk=239/778)
39bc2a2c-23a9-4f44-969f-aaaca09e6aab.mp4
         27.95M 100%   20.99MB/s    0:00:01 (xfr#179, to-chk=238/778)
39c49810-8570-4a5a-b4c8-6775268d587a.mp4
         51.97M 100%   31.59MB/s    0:00:01 (xfr#180, to-chk=237/778)
39c4a8dd-b479-401c-ab52-8a0fa77cadd6.mp4

In [10]:
!du -sh /content/v2/clips
!du -sh "/content/drive/MyDrive/ego4d_data/v2/clips_540/clips"

33G	/content/v2/clips
33G	/content/drive/MyDrive/ego4d_data/v2/clips_540/clips

In [11]:
!find /content/v2/clips -type f | wc -l
!find "/content/drive/MyDrive/ego4d_data/v2/clips_540/clips" -type f | wc -l

777
778

In [12]:
import os

# === Paths ===
content_dir = "/content/v2/clips/"
drive_dir = "/content/drive/MyDrive/ego4d_data/v2/clips_540/clips/"

# === Collect filenames (ignore folder structure) ===
def list_filenames(folder):
    all_files = []
    for root, _, files in os.walk(folder):
        for f in files:
            all_files.append(f)
    return set(all_files)

content_files = list_filenames(content_dir)
drive_files = list_filenames(drive_dir)

# === Compare ===
only_in_content = content_files - drive_files
only_in_drive = drive_files - content_files
common_files = content_files & drive_files

# === Summary ===
print(f"✅ Common files: {len(common_files)}")
print(f"📂 Only in /content: {len(only_in_content)}")
print(f"📁 Only in Drive: {len(only_in_drive)}")

# === Optional: show a few missing files ===

✅ Common files: 777
📂 Only in /content: 0
📁 Only in Drive: 1

In [61]:
import pandas as pd

# === File paths ===
manifest_path = "/content/v2/clip_256ss/manifest.csv"
sta_clip_path = "/content/drive/MyDrive/ego4d_data/sta_clip_uids.txt"
sta_uid_path = "/content/drive/MyDrive/ego4d_data/sta_uids.txt"

# === Load data ===
# CSV: assuming it has a column named 'video_uid'
manifest_df = pd.read_csv(manifest_path)
manifest_uids = set(manifest_df['video_uid'].astype(str))

# TXT files: one UID per line
def load_txt_uids(path):
    with open(path, 'r') as f:
        return set(line.strip() for line in f if line.strip())

sta_clip_uids = load_txt_uids(sta_clip_path)
sta_uid_uids = load_txt_uids(sta_uid_path)

# === Compare each pair ===
comparisons = {
    "manifest_vs_sta_clip": manifest_uids & sta_clip_uids,
    "manifest_vs_sta_uid": manifest_uids & sta_uid_uids,
    "sta_clip_vs_sta_uid": sta_clip_uids & sta_uid_uids,
}

# === Print summary ===
for name, overlap in comparisons.items():
    print(f"🔹 {name}")
    print(f"  Common video_uids: {len(overlap)}")
    if len(overlap) > 0:
        print(f"  Example: {list(overlap)[:5]}")
    print()

# === (Optional) Save results ===
pd.DataFrame({
    "pair": comparisons.keys(),
    "num_common_uids": [len(v) for v in comparisons.values()]
}).to_csv("/content/uid_overlap_summary.csv", index=False)

print("✅ Summary saved to /content/uid_overlap_summary.csv")

🔹 manifest_vs_sta_clip
  Common video_uids: 2324
  Example: ['463bea1c-1ebd-469d-aff9-500fa424c92d', '562dd092-9e12-4cb2-b3f1-9dfad30ade20', '4072124f-b305-414b-961e-c140d83a22b9', 'd28f8930-8998-4e52-a5e7-d28e6f251d78', '02618387-b9da-45dd-a642-cd164e6e44aa']

🔹 manifest_vs_sta_uid
  Common video_uids: 0

🔹 sta_clip_vs_sta_uid
  Common video_uids: 0

✅ Summary saved to /content/uid_overlap_summary.csv

# Clip uid code

In [55]:
# ==============================================
# Ego4D — FINAL single cell (video_540 OR clip_540)
# Uses existing UID list + *_frames.txt (NO JSON reading)
# Simplified: direct download (clips accept clip_uids via --video_uid_file)
# ==============================================
import os, subprocess, time, json, shutil
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import timedelta
from tqdm.auto import tqdm

# ---------------------- USER CONFIG ----------------------
EGO4D_ROOT   = "/content/drive/MyDrive/ego4d_data"
VERSION      = "v2"

# "video_540" -> dataset: video_540ss   (video-frame indices)
# "clip_540"  -> dataset: clips         (clip-frame indices @30 FPS)
SOURCE_KIND  = "clip_540"        # <<< "video_540" or "clip_540"

EXTRACTION_MODE = "from_lists"   # 'from_lists' | 'first_n' | 'all'
NUM_FRAMES_TO_EXTRACT = 200

NUM_ITEMS_TO_PROCESS = 2         # None = all
SPECIFIC_IDS = [
    # Example for SOURCE_KIND="clip_540":
    # "002e11bc-deef-45f7-9af8-59421a606d69",
]

DOWNLOAD_MISSING        = True
DELETE_MEDIA_AFTER      = False
USE_PARALLEL_DOWNLOADS  = True     # used for video_540 singles; clips rely on batch
USE_PARALLEL_EXTRACTION = True
BATCH_DOWNLOAD          = True
BATCH_CHUNK_SIZE        = 100

N_DOWNLOAD_WORKERS      = 4
N_EXTRACT_WORKERS       = 2
FFMPEG_TIMEOUT_SECS     = 1800
DOWNLOAD_TIMEOUT_SECS   = 3600
CHUNK_SIZE_FRAMES_SELECT= 800
PRINT_PER_ITEM_INFO     = True

# ---------------------- PATHS ----------------------
if SOURCE_KIND == "video_540":
    DATASET          = "video_540ss"
    MEDIA_DIR        = f"{EGO4D_ROOT}/{VERSION}/video_540ss"
    UID_LIST_FILE    = f"{EGO4D_ROOT}/sta_uids.txt"                       # video_uids
    FRAME_LISTS_DIR  = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists/videos"   # <video_uid>_frames.txt
    FRAME_FILE_TPL   = "{uid}_frames.txt"
    PROCESSED_LOG    = f"{EGO4D_ROOT}/{VERSION}/processed_uids_video540.txt"
    UID_FLAG_SINGLE  = "--video_uids"
    UID_FLAG_FILE    = "--video_uid_file"
elif SOURCE_KIND == "clip_540":
    # IMPORTANT: dataset is "clips", files live in .../v2/clips
    DATASET          = "clips"
    MEDIA_DIR        = f"{EGO4D_ROOT}/{VERSION}/clips"
    UID_LIST_FILE    = f"{EGO4D_ROOT}/sta_clip_uids.txt"                  # clip_uids
    FRAME_LISTS_DIR  = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists/clips"    # <clip_uid>_clip_frames.txt
    FRAME_FILE_TPL   = "{uid}_clip_frames.txt"
    PROCESSED_LOG    = f"{EGO4D_ROOT}/{VERSION}/processed_uids_clip540.txt"
    UID_FLAG_SINGLE  = "--video_uids"     # CLI accepts clip_uids here for dataset=clips
    UID_FLAG_FILE    = "--video_uid_file" # file can contain clip_uids
else:
    raise SystemExit("SOURCE_KIND must be 'video_540' or 'clip_540'")

FRAMES_DRIVE_ROOT = f"{EGO4D_ROOT}/{VERSION}/extracted_frames"
FRAMES_TMP_ROOT   = "/content/tmp_frames"

# ---------------------- PREP ----------------------
for p in (MEDIA_DIR, FRAME_LISTS_DIR, FRAMES_DRIVE_ROOT, FRAMES_TMP_ROOT):
    os.makedirs(p, exist_ok=True)

def which(cmd: str) -> bool:
    import shutil as _sh
    return _sh.which(cmd) is not None

def format_size(n):
    if n is None: return "N/A"
    for u in ["B","KB","MB","GB","TB"]:
        if n < 1024: return f"{n:.2f} {u}"
        n /= 1024
    return f"{n:.2f} PB"

def list_existing_jpgs(folder):
    return [f for f in os.listdir(folder) if f.lower().endswith(".jpg")] if os.path.isdir(folder) else []

def build_eqn_select(frames):
    return "+".join([f"eq(n\\,{int(n)})" for n in frames])

def ffprobe_media_info(path):
    info = {"nb_frames": None, "duration": None, "r_frame_rate": None,
            "width": None, "height": None, "size_bytes": None}
    if not os.path.exists(path):
        return info
    try: info["size_bytes"] = os.path.getsize(path)
    except: pass
    cmd = ["ffprobe","-v","error","-select_streams","v:0",
           "-show_entries","stream=nb_frames,r_frame_rate,width,height:format=duration",
           "-of","json", path]
    try:
        res = subprocess.run(cmd, text=True, capture_output=True, check=True)
        data = json.loads(res.stdout or "{}")
        if "streams" in data and data["streams"]:
            s = data["streams"][0]
            if s.get("nb_frames") is not None:
                try: info["nb_frames"] = int(s["nb_frames"])
                except: pass
            info["r_frame_rate"] = s.get("r_frame_rate")
            info["width"]  = int(s["width"])  if s.get("width")  else None
            info["height"] = int(s["height"]) if s.get("height") else None
        if "format" in data and data["format"].get("duration") is not None:
            try: info["duration"] = float(data["format"]["duration"])
            except: pass
        if info["nb_frames"] in (None, 0):
            fps = None
            if info["r_frame_rate"]:
                try:
                    a,b = info["r_frame_rate"].split("/")
                    a = float(a); b = float(b) if float(b) != 0 else 1.0
                    fps = a/b
                except: pass
            if fps and info["duration"]:
                info["nb_frames"] = int(fps * info["duration"])
    except: pass
    return info

# ---------------------- FFMPEG RUNNERS ----------------------
def run_ffmpeg_select(media_path, frames, out_dir, start_number=None, chunk=800, timeout=1800):
    os.makedirs(out_dir, exist_ok=True)
    frames = sorted(set(int(x) for x in frames))
    if not frames: return 0, 0.0
    before = len(list_existing_jpgs(out_dir))
    if start_number is None: start_number = before
    t0 = time.time()
    for i in range(0, len(frames), chunk):
        piece = frames[i:i+chunk]
        vf = f"select='{build_eqn_select(piece)}',setpts=N/FRAME_RATE/TB"
        cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
               "-i", media_path, "-vf", vf, "-vsync","0",
               "-start_number", str(start_number),
               os.path.join(out_dir, "%07d.jpg")]
        subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
        start_number += len(piece)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

def run_ffmpeg_first_n(media_path, n, out_dir, timeout=1800):
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
           "-i", media_path, "-vframes", str(int(n)),
           os.path.join(out_dir, "%07d.jpg")]
    t0 = time.time()
    subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

def run_ffmpeg_all(media_path, out_dir, timeout=1800):
    os.makedirs(out_dir, exist_ok=True)
    before = len(list_existing_jpgs(out_dir))
    cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
           "-i", media_path, "-vsync","0",
           os.path.join(out_dir, "%07d.jpg")]
    t0 = time.time()
    subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
    after = len(list_existing_jpgs(out_dir))
    return max(0, after - before), (time.time()-t0)

# ---------------------- DOWNLOAD HELPERS ----------------------
def download_one(uid, timeout=3600, aws_profile=None):
    """Single download (used only for video_540). For clips prefer batch."""
    path = os.path.join(MEDIA_DIR, f"{uid}.mp4")
    if os.path.exists(path):
        return uid, True, 0.0, "present"
    if not which("ego4d"):
        return uid, False, 0.0, "ego4d CLI not found"

    cmd = ["ego4d","--output_directory", EGO4D_ROOT, "--datasets", DATASET,
           "--version", VERSION, UID_FLAG_SINGLE, uid, "-y"]
    if aws_profile: cmd += ["--aws_profile_name", aws_profile]
    t0 = time.time()
    try:
        subprocess.run(cmd, check=True, text=True, capture_output=True, timeout=timeout)
        ok = os.path.exists(path); t1 = time.time()
        return uid, ok, (t1-t0), ("downloaded" if ok else "missing_after_dl")
    except subprocess.CalledProcessError:
        return uid, False, time.time()-t0, "ego4d failed"
    except subprocess.TimeoutExpired:
        return uid, False, time.time()-t0, "timeout"

def batch_download_ids(ids, chunk_size=100, timeout=3600, aws_profile=None):
    """Batch download using --video_uid_file.
       For dataset=clips the file contains clip_uids directly."""
    if not which("ego4d"):
        print("  !!! ego4d CLI not found; cannot batch download.")
        return 0, len(ids)
    ok_total = 0
    for i in range(0, len(ids), chunk_size):
        chunk = ids[i:i+chunk_size]
        tmpfile = f"/content/ego4d_ids_{i//chunk_size}.txt"
        with open(tmpfile,"w") as f: f.write("\n".join(chunk))
        cmd = ["ego4d","--output_directory", EGO4D_ROOT, "--datasets", DATASET,
               "--version", VERSION, UID_FLAG_FILE, tmpfile, "-y"]
        if aws_profile: cmd += ["--aws_profile_name", aws_profile]
        r = subprocess.run(cmd, text=True, capture_output=True)
        if r.returncode != 0:
            print(f"[batch {i//chunk_size}] CLI exited {r.returncode}. Showing stderr:")
            print(r.stderr or "")
        ok_total += sum(os.path.exists(os.path.join(MEDIA_DIR, f"{u}.mp4")) for u in chunk)
        try: os.remove(tmpfile)
        except: pass
    return ok_total, len(ids)

# ---------------------- LOAD/CHOOSE IDS ----------------------
def load_all_ids_from_file(path):
    if not os.path.exists(path): raise SystemExit(f"UID list not found: {path}")
    with open(path,"r") as f: return [ln.strip() for ln in f if ln.strip()]

def choose_ids():
    if SPECIFIC_IDS:
        seen, base = set(), []
        for u in SPECIFIC_IDS:
            if u not in seen:
                base.append(u); seen.add(u)
    else:
        base = load_all_ids_from_file(UID_LIST_FILE)

    if EXTRACTION_MODE == "from_lists":
        filtered = []
        for u in base:
            fpath = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=u))
            if os.path.exists(fpath): filtered.append(u)
        if len(filtered) != len(base):
            print(f"NOTE: {len(base)-len(filtered)} id(s) missing frame file → skipped.")
        base = filtered

    if NUM_ITEMS_TO_PROCESS: base = base[:NUM_ITEMS_TO_PROCESS]
    return base

ids_all = choose_ids()
print(f"Source: {SOURCE_KIND} → dataset='{DATASET}', media dir='{MEDIA_DIR}'")
print(f"Selected {len(ids_all)} item(s) for mode='{EXTRACTION_MODE}'")
if SPECIFIC_IDS: print(f"Using SPECIFIC_IDS (length={len(SPECIFIC_IDS)}).")

# ---------------------- PREFLIGHT ----------------------
if not which("ffmpeg"): raise SystemExit("Install ffmpeg first (e.g., `!apt-get -y install ffmpeg`).")
if DOWNLOAD_MISSING and not which("ego4d"):
    print("WARNING: ego4d CLI not found; downloads will be skipped.")

# ---------------------- DOWNLOAD PHASE ----------------------
outer_t0 = time.time()
downloaded_ct = 0

if DOWNLOAD_MISSING and ids_all:
    to_get = [u for u in ids_all if not os.path.exists(os.path.join(MEDIA_DIR, f"{u}.mp4"))]
    print(f"Need to download: {len(to_get)} file(s).")

    if BATCH_DOWNLOAD and to_get:
        ok_ct, total_ct = batch_download_ids(to_get, chunk_size=BATCH_CHUNK_SIZE, timeout=DOWNLOAD_TIMEOUT_SECS)
        downloaded_ct += ok_ct
        print(f"Batch 'ok' presence (post-check) {ok_ct}/{total_ct}.")
    elif USE_PARALLEL_DOWNLOADS and to_get and SOURCE_KIND == "video_540":
        print(f"Parallel downloading with {N_DOWNLOAD_WORKERS} workers ...")
        with ThreadPoolExecutor(max_workers=max(1, int(N_DOWNLOAD_WORKERS))) as ex:
            futures = [ex.submit(download_one, u, DOWNLOAD_TIMEOUT_SECS, None) for u in to_get]
            for fut in tqdm(as_completed(futures), total=len(futures)):
                uid, ok, secs, note = fut.result()
                downloaded_ct += int(ok)
                if PRINT_PER_ITEM_INFO:
                    print(f"  {uid} → {note} in {secs:.1f}s")
        print(f"Downloaded (parallel): {downloaded_ct}/{len(to_get)} new files.")
else:
    print("Skipping downloads.")

# ---------------------- FRAME LIST LOADER ----------------------
def load_frames_for(uid):
    p = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
    if not os.path.exists(p): return []
    with open(p) as f: return [int(x.strip()) for x in f if x.strip()]

# ---------------------- EXTRACTION ----------------------
def move_tmp_to_drive(out_tmp, out_final):
    if os.path.exists(out_final):
        for f in os.listdir(out_tmp):
            src = os.path.join(out_tmp, f)
            dst = os.path.join(out_final, f)
            if not os.path.exists(dst): shutil.move(src, dst)
        shutil.rmtree(out_tmp, ignore_errors=True)
    else:
        shutil.move(out_tmp, out_final)

def extract_one(uid):
    media_path = os.path.join(MEDIA_DIR, f"{uid}.mp4")
    if not os.path.exists(media_path):
        return uid, 0, 0.0, 0, "media_missing"

    info = ffprobe_media_info(media_path)
    total_frames_media = info["nb_frames"] if info["nb_frames"] else 0
    w, h, msize = info["width"], info["height"], info["size_bytes"]

    out_tmp   = os.path.join(FRAMES_TMP_ROOT, uid)
    out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)
    os.makedirs(out_tmp, exist_ok=True)

    try:
        if EXTRACTION_MODE == "all":
            new_count, secs = run_ffmpeg_all(media_path, out_tmp, timeout=FFMPEG_TIMEOUT_SECS)
            requested_ct = total_frames_media if total_frames_media else 0
        elif EXTRACTION_MODE == "first_n":
            new_count, secs = run_ffmpeg_first_n(media_path, NUM_FRAMES_TO_EXTRACT, out_tmp, timeout=FFMPEG_TIMEOUT_SECS)
            requested_ct = NUM_FRAMES_TO_EXTRACT
        elif EXTRACTION_MODE == "from_lists":
            frames = load_frames_for(uid)
            if not frames:
                return uid, 0, 0.0, total_frames_media, "no_frame_list"
            new_count, secs = run_ffmpeg_select(media_path, frames, out_tmp,
                                                chunk=CHUNK_SIZE_FRAMES_SELECT,
                                                timeout=FFMPEG_TIMEOUT_SECS)
            requested_ct = len(frames)
        else:
            return uid, 0, 0.0, total_frames_media, "bad_mode"

        move_tmp_to_drive(out_tmp, out_final)

        if DELETE_MEDIA_AFTER:
            try: os.remove(media_path)
            except: pass

        imgs_now = len(list_existing_jpgs(out_final))
        if PRINT_PER_ITEM_INFO:
            print(f"  {uid}: {w}x{h}, {format_size(msize)}, total≈{total_frames_media} | requested={requested_ct} new={new_count} now={imgs_now}")
        return uid, new_count, secs, total_frames_media, "ok"

    except subprocess.CalledProcessError:
        return uid, 0, 0.0, total_frames_media, "ffmpeg_failed"
    except Exception as e:
        return uid, 0, 0.0, total_frames_media, f"error:{str(e)[:80]}"

# ---------------------- RUN EXTRACTION ----------------------
rows = []
total_requested, total_extracted = 0, 0
if USE_PARALLEL_EXTRACTION and ids_all:
    print(f"Parallel extraction with {N_EXTRACT_WORKERS} workers ...")
    with ThreadPoolExecutor(max_workers=max(1, int(N_EXTRACT_WORKERS))) as ex:
        futures = [ex.submit(extract_one, u) for u in ids_all]
        for fut in tqdm(as_completed(futures), total=len(futures)):
            uid, new_ct, secs, tf_all, note = fut.result()
            if EXTRACTION_MODE == "first_n":
                req_ct = NUM_FRAMES_TO_EXTRACT
            elif EXTRACTION_MODE == "all":
                req_ct = tf_all if tf_all else 0
            else:
                fpath = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
                req_ct = sum(1 for _ in open(fpath)) if os.path.exists(fpath) else 0

            out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)
            imgs_now = len(list_existing_jpgs(out_final)) if os.path.exists(out_final) else 0

            rows.append((uid, req_ct, new_ct, imgs_now, tf_all, 0.0, secs, note))
            total_requested += req_ct
            total_extracted += new_ct
else:
    print("Serial extraction ...")
    for uid in tqdm(ids_all):
        uid, new_ct, secs, tf_all, note = extract_one(uid)
        if EXTRACTION_MODE == "first_n":
            req_ct = NUM_FRAMES_TO_EXTRACT
        elif EXTRACTION_MODE == "all":
            req_ct = tf_all if tf_all else 0
        else:
            fpath = os.path.join(FRAME_LISTS_DIR, FRAME_FILE_TPL.format(uid=uid))
            req_ct = sum(1 for _ in open(fpath)) if os.path.exists(fpath) else 0
        out_final = os.path.join(FRAMES_DRIVE_ROOT, uid)
        imgs_now = len(list_existing_jpgs(out_final)) if os.path.exists(out_final) else 0
        rows.append((uid, req_ct, new_ct, imgs_now, tf_all, 0.0, secs, note))
        total_requested += req_ct
        total_extracted += new_ct

# ---------------------- MARK DONE & SUMMARY ----------------------
with open(PROCESSED_LOG,"a") as f:
    for uid, *_ in rows:
        f.write(uid + "\n")

outer_t1 = time.time()
print("\n========== SUMMARY ==========")
print(f"Source: {SOURCE_KIND} (dataset={DATASET})")
print(f"Mode: {EXTRACTION_MODE}")
print(f"Items processed: {len(rows)} / {len(ids_all)} selected")
print(f"Frames requested (sum): {total_requested}")
print(f"Frames extracted (new this run): {total_extracted}")
print(f"Total wall time: {timedelta(seconds=int(outer_t1-outer_t0))}")

if rows:
    print("\n[uid | req | new | imgs_now | total_frames | download_s | extract_s | note]")
    for uid, req, new, imgs, tf, dls, exs, note in rows[:40]:
        tf_disp = f"{tf}" if tf not in (None, 0) else "unknown"
        print(f"{uid} | {req:4d} | {new:4d} | {imgs:7d} | {tf_disp:12} | {dls:10.1f} | {exs:9.1f} | {note}")

print(f"\nFrames on Drive: {FRAMES_DRIVE_ROOT}")
print(f"Processed log updated: {PROCESSED_LOG}")
print("=============================================")

Source: clip_540 → dataset='clips', media dir='/content/drive/MyDrive/ego4d_data/v2/clips'
Selected 2 item(s) for mode='from_lists'
Need to download: 2 file(s).
Batch 'ok' presence (post-check) 2/2.
Parallel extraction with 2 workers ...

  0%|          | 0/2 [00:00<?, ?it/s]

  004e8f11-9d56-4208-aeaf-77b03ced000c: 1440x1080, 27.18 MB, total≈5305 | requested=35 new=35 now=35
  002e11bc-deef-45f7-9af8-59421a606d69: 1920x1440, 48.33 MB, total≈9239 | requested=124 new=124 now=124

========== SUMMARY ==========
Source: clip_540 (dataset=clips)
Mode: from_lists
Items processed: 2 / 2 selected
Frames requested (sum): 159
Frames extracted (new this run): 159
Total wall time: 0:02:01

[uid | req | new | imgs_now | total_frames | download_s | extract_s | note]
004e8f11-9d56-4208-aeaf-77b03ced000c |   35 |   35 |      35 | 5305         |        0.0 |      60.5 | ok
002e11bc-deef-45f7-9af8-59421a606d69 |  124 |  124 |     124 | 9239         |        0.0 |     109.9 | ok

Frames on Drive: /content/drive/MyDrive/ego4d_data/v2/extracted_frames
Processed log updated: /content/drive/MyDrive/ego4d_data/v2/processed_uids_clip540.txt
=============================================

In [57]:
!ego4d --list-datasets

Downloading datasets.csv..

Available Ego4D datasets:
   annotations          	The full set of annotations for the majority of benchmarks.
   full_scale           	The full scale version of all videos.  (Provide `benchmarks` or `video_uids` filters to reduce the 5TB download size.)
   clips                	Clips available for benchmark training tasks.  (Provide `benchmarks` or `video_uids` filters to reduce the download size.)
   video_540ss          	The downscaled version of all videos - rescaled to 540px on the short side.  (Provide `benchmarks` or `video_uids` filters to reduce the 5TB download size.)
   annotations_540ss    	The annotations corresponding to the downscaled `video_540ss` videos - primarily differing only in spatial annotations (e.g. bounding boxes).
   3d                   	Annotations for the 3D VQ benchmark.
   3d_scans             	3D location scans for the 3D VQ benchmark.
   3d_scan_keypoints    	3D location scan keypoints for the 3D VQ benchmark.
   imu                  	IMU data for the subset of videos available
   slowfast8x8_r101_k400	Precomputed [action features](https://ego4d-data.org/docs/data/features/) for the Slowfast 8x8 (R101) model
   omnivore_video_swinl 	Precomputed [action features](https://ego4d-data.org/docs/data/features/) for the Omnivore Video model
   omnivore_image_swinl 	Precomputed [action features](https://ego4d-data.org/docs/data/features/) for the Omnivore Image model
   fut_loc              	Images and annotations for the future locomotion benchmark.
   av_models            	Model checkpoints for the AV/Social benchmark.
   lta_models           	Model checkpoints for the Long Term Anticipation benchmark.
   moments_models       	Model checkpoints for the Moments benchmark.
   nlq_models           	Model checkpoints for the NLQ benchmark.
   sta_models           	Model checkpoints for the Short Term Anticipation benchmark.
   vq2d_models          	Model checkpoints for the 2D VQ benchmark.
   clip_256ss           	Clips downscaled to 256px short side
   egotracks            	Egotracks dataset
   gaze                 	Eye gaze data
   imu                  	IMU data
   naq_datasets         	See https://github.com/srama2512/NaQ
   omnivore_video_swinl_fp16	Omnivore Video features in FP16 (half the size
   vq2d_detections      	VQ2D Preprocessed Detections

# Size does matter

In [ ]:
# === Estimate total frames & size for 540ss videos listed in sta_uids.txt ===
# Inputs:
#   - /content/drive/MyDrive/ego4d_data/sta_uids.txt        (list of video_uids)
#   - /content/drive/MyDrive/ego4d_data/v2/annotations_540ss/fho_sta_train_height-540.json
#   - /content/drive/MyDrive/ego4d_data/v2/annotations_540ss/fho_sta_val_height-540.json
#
# Output:
#   - pandas DataFrame with columns: ["video_uid", "number_of_frames", "estimated_size_mb"]
#   - printed totals
#   - CSV saved to: /content/drive/MyDrive/ego4d_data/v2/estimates_540ss.csv

import os, json
import pandas as pd

# --- Paths (edit if your structure differs) ---
ROOT = "/content/drive/MyDrive/ego4d_data"
VERSION = "v2"
UID_LIST_FILE = f"{ROOT}/sta_uids.txt"
ANN_DIR_540 = f"{ROOT}/{VERSION}/annotations_540ss"
TRAIN_JSON_540 = f"{ANN_DIR_540}/fho_sta_train_height-540.json"
VAL_JSON_540   = f"{ANN_DIR_540}/fho_sta_val_height-540.json"

# --- Heuristic: average megabytes per frame for 540ss videos (VP9, 720x540, ~30fps)
# You can tune this number using a few downloaded samples: MB_PER_FRAME = (video_size_MB / nb_frames)
MB_PER_FRAME_540 = 0.0055  # ~5.5 KB per frame; adjust if you measure a better average

# --- Load target video_uids from sta_uids.txt ---
if not os.path.exists(UID_LIST_FILE):
    raise FileNotFoundError(f"UID list not found: {UID_LIST_FILE}")
with open(UID_LIST_FILE, "r") as f:
    target_uids = [x.strip() for x in f if x.strip()]

target_set = set(target_uids)
print(f"Loaded {len(target_set)} video_uids from sta_uids.txt")

# --- Helper: scan one 540 JSON and update per-uid max frame estimate ---
def update_max_frames_from_json(json_path, frames_dict, target_set):
    if not os.path.exists(json_path):
        print(f"WARNING: annotation file not found: {json_path}")
        return
    with open(json_path, "r") as f:
        data = json.load(f)

    # Files are dicts with 'annotations' list
    anns = data.get("annotations", [])
    for a in anns:
        uid = a.get("video_uid")
        if uid not in target_set:
            continue

        # Candidate fields that can hint the farthest frame observed in annotations
        candidates = []
        for key in ("frame", "action_end_frame", "interval_end_frame", "clip_parent_end_frame"):
            v = a.get(key, None)
            if v is not None:
                try:
                    candidates.append(int(v))
                except Exception:
                    pass

        if not candidates:
            continue

        mf = max(candidates)
        # keep the maximum across all annotation entries for this uid
        if uid not in frames_dict or mf > frames_dict[uid]:
            frames_dict[uid] = mf

# --- Aggregate max frames per uid from both train/val 540 files ---
max_frames_per_uid = {}
update_max_frames_from_json(TRAIN_JSON_540, max_frames_per_uid, target_set)
update_max_frames_from_json(VAL_JSON_540,   max_frames_per_uid, target_set)

# --- Build DataFrame (only UIDs that appeared in the annotations) ---
rows = []
missing = []
for uid in target_uids:
    if uid in max_frames_per_uid:
        n_frames = int(max_frames_per_uid[uid])
        est_mb = n_frames * MB_PER_FRAME_540
        rows.append({
            "video_uid": uid,
            "number_of_frames": n_frames,
            "estimated_size_mb": round(est_mb, 2)
        })
    else:
        # No annotations encountered for this uid in the 540 files (rare but possible)
        missing.append(uid)
        rows.append({
            "video_uid": uid,
            "number_of_frames": None,
            "estimated_size_mb": None
        })

df = pd.DataFrame(rows)
# Optional: put known values first
df = df.sort_values(by=["number_of_frames"], ascending=False, na_position="last").reset_index(drop=True)

# --- Totals (only over rows with known frames) ---
known = df.dropna(subset=["number_of_frames"])
total_frames = int(known["number_of_frames"].sum()) if not known.empty else 0
total_size_mb = float((known["number_of_frames"] * MB_PER_FRAME_540).sum()) if not known.empty else 0.0
total_size_gb = total_size_mb / 1024.0

print("\n=== Per-video (head) ===")
print(df.head(10))

print("\n=== Totals (known videos) ===")
print(f"Total number of frames: {total_frames:,}")
print(f"Estimated total size:   {total_size_mb:,.2f} MB  (~{total_size_gb:,.2f} GB)")

if missing:
    print(f"\nNote: {len(missing)} video_uids from sta_uids.txt had no entries in the 540 annotation files. "
          f"They remain with unknown frames/size in the table.")

# --- Save CSV for later use ---
OUT_CSV = f"{ROOT}/{VERSION}/estimates_540ss.csv"
os.makedirs(os.path.dirname(OUT_CSV), exist_ok=True)
df.to_csv(OUT_CSV, index=False)
print(f"\nSaved: {OUT_CSV}")

Loaded 1311 video_uids from sta_uids.txt

=== Per-video (head) ===
                              video_uid  number_of_frames  estimated_size_mb
0  91155366-856d-445b-8324-f7db85a51628            560306            3081.68
1  bbb1bf06-41f6-46e5-a051-3e75e724b2d7            444063            2442.35
2  21dd0acb-4549-4439-90a9-9d920bbc603d            370862            2039.74
3  d9db7166-e5fe-4ce5-85eb-0c437c4ddf32            347275            1910.01
4  a77c0e56-3880-48bf-b6bf-9d46c6a42fc7            337315            1855.23
5  155f8d74-4c5c-4821-a18b-fceaa9c6199c            290546            1598.00
6  1e5bd816-e1dd-43d3-8709-42c83114dc7c            288368            1586.02
7  8c730e66-aa1b-4a0b-a4ee-db42b1b41f96            217692            1197.31
8  ed90c2e8-c608-423f-a565-7b4cfffbe438            215426            1184.84
9  8e58a7b3-43ef-406d-ad5d-901f83418261            207239            1139.81

=== Totals (known videos) ===
Total number of frames: 47,832,886
Estimated total size:   263,080.87 MB  (~256.91 GB)

Saved: /content/drive/MyDrive/ego4d_data/v2/estimates_540ss.csv

# Sanity check

In [26]:
# ==========================================
# Ego4D STA sanity checks: clip_uid/video_uid ↔ files ↔ frame lists ↔ manifest
# - Scans 540-STA JSONs (train/val)
# - Cross-checks presence in:
#     v2/clips/               (clip MP4s)
#     v2/video_540ss/         (video MP4s)
#     v2/tmp_frame_lists/...  (per-id frame lists)
#     v2/clips/manifest.csv   (exported_clip_uid ↔ parent_video/frame range)
# - Optional mini ffmpeg extraction smoke test (disabled by default)
# ==========================================
import os, json, csv, random, subprocess
from collections import defaultdict

# ---------------- USER PATHS ----------------
EGO4D_ROOT = "/content/drive/MyDrive/ego4d_data"
VERSION    = "v2"

ANN_DIR       = f"{EGO4D_ROOT}/{VERSION}/annotations_540ss"
TRAIN_JSON    = os.path.join(ANN_DIR, "fho_sta_train_height-540.json")
VAL_JSON      = os.path.join(ANN_DIR, "fho_sta_val_height-540.json")

CLIPS_DIR     = f"{EGO4D_ROOT}/{VERSION}/clips"          # ego4d --datasets clips
VIDEOS540_DIR = f"{EGO4D_ROOT}/{VERSION}/video_540ss"    # ego4d --datasets video_540ss

LISTS_BASE    = f"{EGO4D_ROOT}/{VERSION}/tmp_frame_lists"
VIDEO_LISTS   = os.path.join(LISTS_BASE, "videos")       # <video_uid>_frames.txt
CLIP_LISTS    = os.path.join(LISTS_BASE, "clips")        # <clip_uid>_clip_frames.txt

CLIPS_MANIFEST = os.path.join(CLIPS_DIR, "manifest.csv") # created by the clips dataset download

# Toggle a tiny extraction smoke test (extract 1 frame for one clip id & index)
RUN_SMOKE_TEST = True

# ---------------- HELPERS ----------------
def _load_anns(path):
    if not os.path.exists(path):
        print(f"!! Missing annotations: {path}")
        return []
    data = json.load(open(path, "r"))
    if isinstance(data, dict) and "annotations" in data:
        return data["annotations"]
    if isinstance(data, list):
        return data
    if isinstance(data, dict) and "data" in data and isinstance(data["data"], list):
        return data["data"]
    return []

def _list_stems(dirpath, ext=".mp4"):
    if not os.path.isdir(dirpath): return set()
    return {os.path.splitext(f)[0] for f in os.listdir(dirpath) if f.endswith(ext)}

def _has_file(p): return os.path.exists(p)

def _read_ints(path):
    try:
        with open(path) as f:
            return [int(x.strip()) for x in f if x.strip()]
    except:
        return []

def _ffprobe_nb_frames(path):
    cmd = ["ffprobe","-v","error","-select_streams","v:0","-show_entries","stream=nb_frames","-of","csv=p=0", path]
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, check=True).stdout.strip()
        return int(out) if out.isdigit() else None
    except:
        return None

# ---------------- LOAD JSONS ----------------
train = _load_anns(TRAIN_JSON)
val   = _load_anns(VAL_JSON)
all_recs = train + val
print(f"Loaded STA540 records: train={len(train)} val={len(val)} total={len(all_recs)}")

# gather sets & a few samples
clip_uids_json    = set()
video_uids_json   = set()
pairs_for_maptest = []  # (clip_uid, video_uid, clip_frame, video_frame)

for r in all_recs:
    cu = r.get("clip_uid")
    vu = r.get("video_uid")
    cf = r.get("clip_frame")
    vf = r.get("frame")
    if cu: clip_uids_json.add(str(cu))
    if vu: video_uids_json.add(str(vu))
    if cu is not None and vu is not None and cf is not None and vf is not None:
        pairs_for_maptest.append((str(cu), str(vu), int(cf), int(vf)))

print(f"Unique clip_uids in JSON:  {len(clip_uids_json)}")
print(f"Unique video_uids in JSON: {len(video_uids_json)}")

# ---------------- FILESYSTEM PRESENCE ----------------
clips_present     = _list_stems(CLIPS_DIR, ".mp4")
videos540_present = _list_stems(VIDEOS540_DIR, ".mp4")

clips_with_lists  = {os.path.splitext(f)[0].replace("_clip_frames","")
                     for f in os.listdir(CLIP_LISTS)} if os.path.isdir(CLIP_LISTS) else set()
videos_with_lists = {os.path.splitext(f)[0].replace("_frames","")
                     for f in os.listdir(VIDEO_LISTS)} if os.path.isdir(VIDEO_LISTS) else set()

print("\n--- Presence summary ---")
print(f"Clips present (mp4):          {len(clips_present)}")
print(f"Clips with frame lists:        {len(clips_with_lists)}")
print(f"Videos 540 present (mp4):      {len(videos540_present)}")
print(f"Videos with frame lists:       {len(videos_with_lists)}")

# JSON → list presence
clips_json_w_lists  = len([u for u in clip_uids_json  if u in clips_with_lists])
videos_json_w_lists = len([u for u in video_uids_json if u in videos_with_lists])
print(f"JSON clip_uids that have lists:   {clips_json_w_lists}/{len(clip_uids_json)}")
print(f"JSON video_uids that have lists:  {videos_json_w_lists}/{len(video_uids_json)}")

# JSON → mp4 presence
clips_json_w_mp4  = len([u for u in clip_uids_json  if u in clips_present])
videos_json_w_mp4 = len([u for u in video_uids_json if u in videos540_present])
print(f"JSON clip_uids that have mp4:     {clips_json_w_mp4}/{len(clip_uids_json)}")
print(f"JSON video_uids that have mp4:    {videos_json_w_mp4}/{len(video_uids_json)}")

# Show a few missing examples
def _head(iterable, k=5):
    out = []
    for x in iterable:
        out.append(x)
        if len(out) >= k: break
    return out

missing_clips_mp4 = [u for u in clip_uids_json if u not in clips_present and u in clips_with_lists]
missing_v540_mp4  = [u for u in video_uids_json if u not in videos540_present and u in videos_with_lists]

if missing_clips_mp4:
    print("\nExamples: have clip frame list but CLIP .mp4 is missing:", _head(missing_clips_mp4, 10))
if missing_v540_mp4:
    print("Examples: have video frame list but VIDEO_540 .mp4 is missing:", _head(missing_v540_mp4, 10))

# ---------------- CLIPS MANIFEST CHECK ----------------
manifest = {}
if os.path.exists(CLIPS_MANIFEST):
    with open(CLIPS_MANIFEST, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            # keys in manifest.csv (as per your sample): exported_clip_uid, parent_video_uid, parent_frame_start, parent_frame_end, ...
            try:
                exported = row["exported_clip_uid"]
            except KeyError:
                # fallback: sometimes "file_uid" is used interchangeably in older exports
                exported = row.get("file_uid")
            if not exported:
                continue
            pvu   = row.get("parent_video_uid")
            pfs   = row.get("parent_frame_start")
            pfe   = row.get("parent_frame_end")
            try:
                pfs = int(pfs) if pfs is not None and pfs != "" else None
                pfe = int(pfe) if pfe is not None and pfe != "" else None
            except:
                pfs, pfe = None, None
            manifest[exported] = (pvu, pfs, pfe)

    print(f"\nManifest rows loaded: {len(manifest)}")
else:
    print("\n!! clips manifest.csv not found; skipping mapping test.")

# Mapping test: clip_frame ≈ video_frame - parent_frame_start (only if manifest row exists)
ok_map = 0
bad_map = 0
samples_checked = 0
bad_examples = []
if manifest:
    # sample up to 200 pairs to keep it quick
    random.shuffle(pairs_for_maptest)
    for cu, vu, cf, vf in pairs_for_maptest[:200]:
        row = manifest.get(cu)
        if not row:
            continue
        pvu, pfs, pfe = row
        # parent video of clip should match JSON video_uid
        parent_match = (pvu == vu) if (pvu and vu) else True
        # simple arithmetic check
        if pfs is not None:
            pred_cf = vf - pfs
            ok = (pred_cf == cf)
        else:
            ok = True  # cannot check without pfs
        if parent_match and ok:
            ok_map += 1
        else:
            bad_map += 1
            if len(bad_examples) < 10:
                bad_examples.append((cu, vu, cf, vf, pvu, pfs, pfe))
        samples_checked += 1

    print(f"\nMapping test on {samples_checked} JSON pairs with manifest rows:")
    print(f"  OK:  {ok_map}")
    print(f"  BAD: {bad_map}")
    if bad_examples:
        print("  Examples of mismatches (clip_uid, video_uid(json), clip_frame, video_frame, parent_video_uid(manifest), parent_frame_start, parent_frame_end):")
        for x in bad_examples:
            print("   ", x)

# ---------------- FRAME LIST COUNTS + NB_FRAMES QUICK CHECKS ----------------
def _frame_count_from_list(dirroot, suffix):
    counts = []
    if not os.path.isdir(dirroot): return counts
    for fn in os.listdir(dirroot):
        if not fn.endswith(suffix): continue
        id_ = fn.replace(suffix, "")
        n = len(_read_ints(os.path.join(dirroot, fn)))
        counts.append((id_, n))
    return counts

clip_counts  = _frame_count_from_list(CLIP_LISTS, "_clip_frames.txt")
video_counts = _frame_count_from_list(VIDEO_LISTS, "_frames.txt")

if clip_counts:
    avg_clip = sum(n for _,n in clip_counts)/len(clip_counts)
    print(f"\nFrame-list stats (clips): files={len(clip_counts)} | avg indices per clip≈{avg_clip:.1f}")
if video_counts:
    avg_vid = sum(n for _,n in video_counts)/len(video_counts)
    print(f"Frame-list stats (videos): files={len(video_counts)} | avg indices per video≈{avg_vid:.1f}")

# Quick ffprobe nb_frames on a couple of present mp4s (no download)
def _head_present(stems, folder, k=3):
    out = []
    for s in stems:
        p = os.path.join(folder, f"{s}.mp4")
        if os.path.exists(p):
            out.append(p)
            if len(out) >= k: break
    return out

some_clips = _head_present(clip_uids_json, CLIPS_DIR, k=3)
some_vids  = _head_present(video_uids_json, VIDEOS540_DIR, k=3)

for p in some_clips:
    nb = _ffprobe_nb_frames(p); print(f"CLIP nb_frames: {os.path.basename(p)} -> {nb}")
for p in some_vids:
    nb = _ffprobe_nb_frames(p); print(f"VIDEO540 nb_frames: {os.path.basename(p)} -> {nb}")

# ---------------- OPTIONAL: one-frame extraction smoke test ----------------
if RUN_SMOKE_TEST and some_clips:
    clip_path = some_clips[0]
    clip_uid  = os.path.splitext(os.path.basename(clip_path))[0]
    lst_path  = os.path.join(CLIP_LISTS, f"{clip_uid}_clip_frames.txt")
    frames    = _read_ints(lst_path)
    if frames:
        test_idx = frames[0]
        out_dir  = os.path.join(EGO4D_ROOT, VERSION, "smoke_test_frames", clip_uid)
        os.makedirs(out_dir, exist_ok=True)
        vf = f"select='eq(n\\,{test_idx})',setpts=N/FRAME_RATE/TB"
        cmd = ["ffmpeg","-hide_banner","-loglevel","error","-y",
               "-i", clip_path, "-vf", vf, "-vsync","0",
               os.path.join(out_dir, "%07d.jpg")]
        try:
            subprocess.run(cmd, check=True, text=True, capture_output=True)
            print(f"\n[SMOKE TEST] Extracted 1 frame n={test_idx} → {out_dir}")
        except Exception as e:
            print(f"\n[SMOKE TEST] Failed: {e}")

print("\n=== Done checks ===")

Loaded STA540 records: train=98276 val=47395 total=145671
Unique clip_uids in JSON:  2324
Unique video_uids in JSON: 1311

--- Presence summary ---
Clips present (mp4):          1
Clips with frame lists:        2324
Videos 540 present (mp4):      4
Videos with frame lists:       1311
JSON clip_uids that have lists:   2324/2324
JSON video_uids that have lists:  1311/1311
JSON clip_uids that have mp4:     1/2324
JSON video_uids that have mp4:    4/1311

Examples: have clip frame list but CLIP .mp4 is missing: ['463bea1c-1ebd-469d-aff9-500fa424c92d', '562dd092-9e12-4cb2-b3f1-9dfad30ade20', '4072124f-b305-414b-961e-c140d83a22b9', 'd28f8930-8998-4e52-a5e7-d28e6f251d78', '02618387-b9da-45dd-a642-cd164e6e44aa', 'c76c8f0f-b976-4f1f-8be2-5839e9c50690', 'a0b252eb-3bf0-4788-9600-b29475a6f719', 'dfa58f3f-366f-4156-9a88-6a2a15fd9bd2', 'a341fa9c-f4c5-4982-be63-0386087240ef', '2c7363b6-8269-4673-8030-673fb698a9fe']
Examples: have video frame list but VIDEO_540 .mp4 is missing: ['79001765-abc6-439b-a987-367dd4d1d5f6', '4c2ea5f1-64a3-41d4-9ce4-e1ea443720b3', 'd256e7bd-131c-498b-8398-52e996264fa8', '19085a13-c91f-4a45-91ea-889ed9a2727f', '70d5b21a-832a-4f4d-af82-807731a08ece', 'fb5ca588-ca6d-48f4-b906-050c80363225', '407f8e81-9a21-4d21-ac02-dff9058fe61d', '2ee46838-6bf8-40a9-9ad0-fae834c7b52c', 'e7cda49b-1c03-4d74-a759-c2eeb96465b4', '3e1e342d-a221-4c40-af4f-7ccd633b466a']

Manifest rows loaded: 15133

Mapping test on 200 JSON pairs with manifest rows:
  OK:  186
  BAD: 14
  Examples of mismatches (clip_uid, video_uid(json), clip_frame, video_frame, parent_video_uid(manifest), parent_frame_start, parent_frame_end):
    ('1cddd647-6aaf-49ed-b09d-922d729453a8', '6a13b88e-fedc-4577-bd21-c158bf4c180e', 1064, 1064, '6a13b88e-fedc-4577-bd21-c158bf4c180e', -1, 1251)
    ('bb921707-a3e4-4edf-9a77-10cef14b7da1', 'c939aae4-e7c8-453c-8671-40573db0c656', 7580, 7580, 'c939aae4-e7c8-453c-8671-40573db0c656', -1, 9239)
    ('6f082d5d-5f31-4358-b2dc-16d320312ab3', 'f938bcd9-bf30-4dfb-9a99-d6b9ee53c046', 6465, 6465, 'f938bcd9-bf30-4dfb-9a99-d6b9ee53c046', -1, 9239)
    ('d2ebfa5c-961b-4759-a243-0ea66d074362', '11286c45-7869-4b84-81a5-7fcb9a247e9d', 3290, 3290, '11286c45-7869-4b84-81a5-7fcb9a247e9d', -1, 3602)
    ('a7e83c35-f261-4d1c-ab20-d7b11c61a517', 'e00d8164-9996-48ed-8645-bb88ab30cc09', 4499, 4499, 'e00d8164-9996-48ed-8645-bb88ab30cc09', -1, 9239)
    ('e8a2f157-a5a0-459a-a165-fe36c75ab348', '0831d387-a359-427c-832d-b306f4720f45', 2307, 2307, '0831d387-a359-427c-832d-b306f4720f45', -1, 6594)
    ('596218ea-6672-472e-aeff-e5fde94562c7', '64f466e5-99c9-4ed5-89be-7ef74d0dfdd3', 7686, 7686, '64f466e5-99c9-4ed5-89be-7ef74d0dfdd3', -1, 9239)
    ('b285d4f3-5ceb-4ef2-b335-42945607de29', 'aa3aa45a-ab0a-4f3e-9629-ed8e8e68b533', 2837, 2837, 'aa3aa45a-ab0a-4f3e-9629-ed8e8e68b533', -1, 9239)
    ('108e24ea-c3be-4bbc-8aaf-893ff4d018a1', 'e58a1cd6-cf82-4477-b8a3-8f749ebceffe', 5743, 5743, 'e58a1cd6-cf82-4477-b8a3-8f749ebceffe', -1, 9239)
    ('9683d857-148e-4086-ab24-e6d98bb37b4d', '3b4a581f-2de7-4089-a3aa-8a28cb920331', 6397, 6397, '3b4a581f-2de7-4089-a3aa-8a28cb920331', -1, 9239)

Frame-list stats (clips): files=2324 | avg indices per clip≈62.7
Frame-list stats (videos): files=1311 | avg indices per video≈111.1
CLIP nb_frames: 002e11bc-deef-45f7-9af8-59421a606d69.mp4 -> 9239
VIDEO540 nb_frames: 0031d268-818c-4ec4-a804-935be610a61a.mp4 -> 59638
VIDEO540 nb_frames: 002c3b5c-ed86-4af3-99a1-4b497b7c8a86.mp4 -> 82740
VIDEO540 nb_frames: 000cd456-ff8d-499b-b0c1-4acead128a8b.mp4 -> 28744

[SMOKE TEST] Extracted 1 frame n=3 → /content/drive/MyDrive/ego4d_data/v2/smoke_test_frames/002e11bc-deef-45f7-9af8-59421a606d69

=== Done checks ===